#!/usr/bin/env python3
import json, os

H = "<div style='font-family:Montserrat,Arial,sans-serif;max-width:600px;margin:0 auto;background:#f5f5f0;'><div style='background:linear-gradient(135deg,#7B5CF5,#9B7FF5);padding:28px 36px;text-align:center;'><img src='https://raw.githubusercontent.com/privi-doughnut/oneloveinitiative/main/OLI_LOGO.jpg' alt='OLI' style='width:64px;height:64px;border-radius:50%;object-fit:cover;border:3px solid rgba(255,255,255,0.3);'/><h1 style='color:#fff;font-size:18px;font-weight:800;margin:8px 0 0;letter-spacing:0.07em;'>ONE LOVE INITIATIVE</h1><p style='color:rgba(255,255,255,0.8);font-size:10px;margin:3px 0 0;letter-spacing:0.14em;text-transform:uppercase;'>Charlotte, NC &middot; Student-Led Nonprofit</p></div>"
F = "<div style='padding:16px 24px;background:#f5f5f0;text-align:center;border-top:1px solid #eee;'><p style='font-size:11px;color:#aaa;margin:0;'>2025 OLI &middot; <a href='https://oneloveinitative.org' style='color:#7B5CF5;text-decoration:none;'>Website</a> &middot; <a href='https://www.instagram.com/one.love.initiative/' style='color:#7B5CF5;text-decoration:none;'>Instagram</a> &middot; <a href='{{UNSUBSCRIBE_URL}}' style='color:#aaa;text-decoration:none;'>Unsubscribe</a></p></div></div>"

RECEIPT = ("<div style='background:#f8f8f8;border:1px solid #eee;border-radius:4px;padding:18px;margin:24px 0;'>"
    "<p style='font-size:10px;letter-spacing:0.15em;text-transform:uppercase;color:#999;margin:0 0 10px;font-weight:600;'>Donation Receipt</p>"
    "<table style='width:100%;border-collapse:collapse;'>"
    "<tr><td style='padding:5px 0;font-size:12px;color:#888;'>Donor</td><td style='padding:5px 0;font-size:12px;color:#333;text-align:right;font-weight:600;'>{{NAME}}</td></tr>"
    "<tr><td style='padding:5px 0;font-size:12px;color:#888;'>Amount</td><td style='padding:5px 0;font-size:12px;color:#7B5CF5;text-align:right;font-weight:700;'>${{AMOUNT}}</td></tr>"
    "<tr><td style='padding:5px 0;font-size:12px;color:#888;'>Date</td><td style='padding:5px 0;font-size:12px;color:#333;text-align:right;'>{{DONATION_DATE}}</td></tr>"
    "<tr><td style='padding:5px 0;font-size:12px;color:#888;'>Transaction</td><td style='padding:5px 0;font-size:11px;color:#333;text-align:right;font-family:monospace;'>{{TRANSACTION_ID}}</td></tr>"
    "</table>"
    "<p style='font-size:10px;color:#aaa;margin:10px 0 0;'>Note: One Love Initiative is not a registered 501(c)(3), so this donation is not tax-deductible.</p>"
    "</div>")

NUDGE = ("<div style='border-top:1px solid #eee;margin:24px 0 0;padding-top:20px;'>"
    "<p style='font-size:13px;color:#666;margin:0 0 12px;'>💌 Want to stay in the loop? Subscribe for monthly updates on our progress, drives, and community stories.</p>"
    "<a href='https://oneloveinitative.org' style='display:inline-block;background:#7B5CF5;color:#fff;padding:10px 22px;border-radius:5px;font-size:12px;font-weight:700;text-decoration:none;letter-spacing:0.06em;'>Stay Updated →</a>"
    "</div>")

def mkb(hl, sub, p1, p2, sg="The OLI Team"):
    return (H +
        "<div style='background:#fff;padding:32px 36px;'>"
        "<h2 style='color:#7B5CF5;font-size:22px;font-weight:800;margin:0 0 5px;line-height:1.3;'>" + hl + "</h2>"
        "<p style='color:#999;font-size:12px;font-style:italic;margin:0 0 18px;'>" + sub + "</p>"
        "<p style='color:#444;font-size:14px;line-height:1.7;margin:0 0 12px;'>" + p1 + "</p>"
        "<p style='color:#444;font-size:14px;line-height:1.7;margin:0 0 0;'>" + p2 + "</p>"
        + RECEIPT +
        "<p style='color:#888;font-size:12px;margin:0 0 0;'>With gratitude,<br/><strong style='color:#7B5CF5;'>" + sg + "</strong></p>"
        + NUDGE +
        "</div>" + F)

# (subject, headline, sub, p1, p2)
T = [
    ("Thank you, {{NAME}} — your generosity means the world 💜", "Your donation just made a difference 💜", "We are so deeply grateful", "{{NAME}}, thank you so much for your generous donation of ${{AMOUNT}} to One Love Initiative. Every dollar that comes into OLI goes directly toward assembling hygiene kits for Charlotte families in need — and yours is no exception.", "Your gift brings us one step closer to our goal of 20,000 Children's Hygiene Kits by end of summer 2025. Because of people like you, Charlotte families can count on having the basics they deserve. 💜"),
    ("{{NAME}}, you just changed something 🎯", "From our team to you: thank you 🎯", "Your ${{AMOUNT}} is going to work right now", "{{NAME}}, your donation of ${{AMOUNT}} landed in the right place at the right time. We're in the middle of our Children's Hygiene Kit Drive and every contribution fuels our push toward 20,000 kits.", "What you gave doesn't just sit in a bank account — it becomes toothbrushes, toothpaste, soap, and lotion in the hands of a Charlotte child who really needs it. Thank you for making that happen. 💜"),
    ("You gave — and Charlotte families benefit 💜", "Your generosity, their relief 💜", "Here's what ${{AMOUNT}} looks like in action", "{{NAME}}, thank you for your donation of ${{AMOUNT}} to One Love Initiative. What you gave is already being put to work — every dollar we receive goes straight toward assembling hygiene kits for families in hardship.", "Through our partner Crisis Assistance Ministry, your contribution reaches Charlotte families who need it most. You gave, and they benefit. That's the chain — and you started it. 💜"),
    ("{{NAME}}, this is a big deal. Thank you. 🙏", "We don't take this lightly 🙏", "Your donation of ${{AMOUNT}} matters more than you know", "{{NAME}}, we know there are a lot of places you could have donated. You chose One Love Initiative — and honestly, that means everything to our small, student-led team in Charlotte.", "Your ${{AMOUNT}} goes directly toward our Children's Hygiene Kit Drive: 20,000 kits for Charlotte families through Crisis Assistance Ministry. You made a big deal happen. Thank you. 🙏"),
    ("A personal thank you from our founder 💌", "Prithivi here — and I am so grateful 💌", "From OLI's founder to you", "{{NAME}}, I started One Love Initiative because I believed students could make a real difference in Charlotte. When someone like you donates ${{AMOUNT}}, it tells me that belief is right.", "Your donation goes toward 20,000 hygiene kits for Charlotte children through Crisis Assistance Ministry. I'm so glad you're part of this. Thank you, truly. — Prithivi, Founder 💜"),
    ("You believed in us — thank you, {{NAME}} 💜", "You believed in OLI 💜", "And your ${{AMOUNT}} proves it", "{{NAME}}, donating to a student-led nonprofit takes a certain kind of faith — faith that the team is real, the mission is genuine, and the impact is actual. Thank you for having that faith in us.", "Your ${{AMOUNT}} goes directly toward our Children's Hygiene Kit Drive. Through Crisis Assistance Ministry, it reaches Charlotte families who need it most. Your belief means the world. 💜"),
    ("The ripple starts with you, {{NAME}} 🌊", "One donation. Countless ripples. 🌊", "Here's what ${{AMOUNT}} sets in motion", "{{NAME}}, thank you for your generous donation of ${{AMOUNT}}. Here's the thing about giving to OLI — it doesn't stop at the kit. It ripples outward. A child gets supplies. A parent has less to worry about. A family feels less alone.", "Your donation ripples through Crisis Assistance Ministry's network and reaches families across Charlotte. One gift. Countless ripples. Thank you for starting it. 🌊"),
    ("Together we're getting closer to 20,000 🎯", "One donation closer to the goal 🎯", "{{NAME}}, your contribution moves us forward", "{{NAME}}, thank you so much for your donation of ${{AMOUNT}} to One Love Initiative. We're on a mission to deliver 20,000 Children's Hygiene Kits to Charlotte families this summer — and you just moved us closer.", "Every kit contains a toothbrush, toothpaste, soap, and lotion — all assembled by student volunteers and delivered through Crisis Assistance Ministry. Your ${{AMOUNT}} helps fill those boxes. Thank you. 💜"),
    ("You just helped pack more hygiene kits 📦", "More kits because of you 📦", "{{NAME}}, your donation goes straight to work", "{{NAME}}, thank you for your donation of ${{AMOUNT}}! At OLI, we don't have overhead or fancy offices — which means your gift goes almost entirely toward what matters: hygiene kits for Charlotte families.", "Through Crisis Assistance Ministry, those kits reach children and families experiencing hardship. Because of you, a few more of those kits are possible. Thank you for showing up for Charlotte. 📦"),
    ("Thank you from the entire OLI team 💜", "From all of us — thank you 💜", "{{NAME}}, your ${{AMOUNT}} lifted every single one of us", "{{NAME}}, every time OLI receives a donation, our whole team feels it. It's a reminder that people outside our small circle believe in what we're doing. Your ${{AMOUNT}} gave us that reminder today.", "We're working toward 20,000 hygiene kits for Charlotte families through Crisis Assistance Ministry. Your donation brings that goal closer. From Prithivi, Saket, Rishi, and every OLI volunteer — thank you. 💜"),
    ("{{NAME}}, you're the reason we keep going 💜", "You're the reason we keep going 💜", "Real talk: donations like yours are what fuel this mission", "{{NAME}}, we started OLI with zero funding and a lot of belief. Donations like your ${{AMOUNT}} gift are what transform belief into reality — into actual kits, actual drives, and actual impact.", "Your contribution goes toward our Children's Hygiene Kit Drive, with distribution through Crisis Assistance Ministry to Charlotte families who need it most. Thank you for keeping us going. 💜"),
    ("Your ${{AMOUNT}} is making hygiene possible 🧴", "Hygiene made possible — by you 🧴", "Here's what your donation looks like in a kit", "{{NAME}}, thank you for your donation of ${{AMOUNT}}! Inside every OLI Kit is a kids' toothbrush, toothpaste, soap, and lotion. Your gift directly funds the procurement and assembly of those items for Charlotte children.", "Through Crisis Assistance Ministry, those kits reach families in real need. You made it possible. And we're grateful beyond words. 💜"),
    ("A kit gets packed because of you, {{NAME}} 📦", "A kit gets packed because of you 📦", "Real, tangible impact from your gift", "{{NAME}}, thank you for your generous donation of ${{AMOUNT}} to One Love Initiative. Because of gifts like yours, OLI student volunteers can assemble more hygiene kits for Charlotte families experiencing hardship.", "Your contribution flows directly through our Children's Hygiene Kit Drive and out through Crisis Assistance Ministry. A kit gets packed. A family gets help. Because of you. 💜"),
    ("Charlotte is a little better because of you 🏙️", "Charlotte is a little better 🏙️", "Thanks to your donation, {{NAME}}", "{{NAME}}, thank you for donating ${{AMOUNT}} to One Love Initiative. That may feel like a small thing — but it's a part of a larger effort to make Charlotte a better place for families who are struggling.", "Our Children's Hygiene Kit Drive is working toward 20,000 kits, delivered through Crisis Assistance Ministry. You're part of why that goal is reachable. Thank you for investing in this city. 🏙️"),
    ("From our students to you — thank you 🎓", "From our students to you 💜", "This is what your support means to a student team", "{{NAME}}, our team is made up of students. We do this between classes, late at night, on weekends — because we believe it matters. When you donate ${{AMOUNT}} to OLI, it tells us we're right.", "Your gift goes toward hygiene kits for Charlotte families through Crisis Assistance Ministry. And it gives us the fuel to keep showing up. Thank you, {{NAME}}. 🎓"),
    ("You showed up for Charlotte — and we're grateful 🏙️", "You showed up for Charlotte 🏙️", "{{NAME}}, your donation of ${{AMOUNT}} is proof that communities care", "{{NAME}}, Charlotte is a city with heart — and your donation of ${{AMOUNT}} is proof of that. One Love Initiative exists to channel that heart into real action: hygiene kits for families in hardship.", "Through Crisis Assistance Ministry, your gift reaches the families who need it most. You showed up for Charlotte, and Charlotte's families benefit. Thank you. 💜"),
    ("Your generosity hit different, {{NAME}} 💜", "Your generosity hit different 💜", "We mean it — this one meant a lot to us", "{{NAME}}, we receive donations with gratitude every single time. But we want to take a moment to really let you know: your ${{AMOUNT}} donation to OLI genuinely moved us. Thank you.", "It goes toward our Children's Hygiene Kit Drive — 20,000 kits for Charlotte kids through Crisis Assistance Ministry. You gave. We felt it. They'll feel it too. 💜"),
    ("Because you gave, a child has more 🧒", "Because you gave, a child has more 🧒", "It's that direct, {{NAME}}", "{{NAME}}, your donation of ${{AMOUNT}} translates directly to hygiene kits for Charlotte children. OLI's model is intentionally lean — so your gift goes as far as possible toward toothbrushes, toothpaste, soap, and lotion.", "Through Crisis Assistance Ministry, those kits reach kids who genuinely need them. Because you gave, a child has more. That's the direct truth — and we're grateful for it. 💜"),
    ("We see you, {{NAME}} — and we thank you 💜", "We see you — and we thank you 💜", "Your donation doesn't go unnoticed", "{{NAME}}, some donations come in and get processed quietly. We don't want that to happen with yours. Your ${{AMOUNT}} contribution to OLI is seen, appreciated, and deeply valued by our entire team.", "It funds hygiene kits for Charlotte families through Crisis Assistance Ministry. And it fuels our drive toward 20,000 kits this summer. Thank you for being seen — and for seeing us. 💜"),
    ("${{AMOUNT}} and a world of gratitude 💜", "Your ${{AMOUNT}} and our gratitude 💜", "These are the things OLI is made of", "{{NAME}}, OLI runs on student energy, community belief, and donations like your ${{AMOUNT}} gift. All three are essential. All three are real. And today, yours made our team incredibly grateful.", "Your contribution goes straight toward hygiene kits for Charlotte families through Crisis Assistance Ministry. 20,000 kits by summer. Powered by people like you. Thank you. 💜"),
    ("You're part of the mission now, {{NAME}} 🎯", "You're officially part of the mission 🎯", "Your ${{AMOUNT}} put you in the story", "{{NAME}}, when you donate to OLI, you don't just support from the outside — you become part of the mission. Your ${{AMOUNT}} goes directly toward hygiene kits for Charlotte families.", "The kits are assembled by student volunteers and distributed through Crisis Assistance Ministry. You funded a piece of that chain. And we think that's worth celebrating. Thank you. 🎯"),
    ("Every kit needs a donor — today that's you 📦", "Every kit needs a donor — today that's you 📦", "{{NAME}}, your role in this is real", "{{NAME}}, behind every OLI Kit there's a student who packed it, a volunteer who coordinated, a partner who distributed it — and a donor who made it financially possible. Today, that donor is you.", "Your ${{AMOUNT}} donation to One Love Initiative goes toward our Children's Hygiene Kit Drive. 20,000 kits. Charlotte. Crisis Assistance Ministry. And you. Thank you. 📦"),
    ("Thank you for choosing OLI, {{NAME}} 💜", "Thank you for choosing OLI 💜", "There are a lot of causes — you picked ours", "{{NAME}}, we know you have choices when it comes to giving. The fact that you chose One Love Initiative with your ${{AMOUNT}} donation means more to us than a standard thank-you can convey.", "Your gift goes toward hygiene kits for Charlotte families in hardship, distributed through Crisis Assistance Ministry. We honor that choice — and we work hard to be worthy of it. Thank you. 💜"),
    ("You made our day, {{NAME}} 🌟", "You made our day 🌟", "And we don't say that lightly", "{{NAME}}, when your ${{AMOUNT}} donation came in, the OLI team genuinely lit up. It's a reminder that what we're building matters to people beyond our small team — and that feels incredible.", "Your donation goes toward our Children's Hygiene Kit Drive: 20,000 kits for Charlotte families through Crisis Assistance Ministry by summer's end. Thank you for making our day. 🌟"),
    ("Real impact, real gratitude — thank you 💜", "Real impact. Real gratitude. 💜", "{{NAME}}, your donation creates something tangible", "{{NAME}}, thank you for your donation of ${{AMOUNT}} to One Love Initiative. Here's what's real: your money becomes hygiene supplies, those supplies become kits, those kits become relief for Charlotte families.", "Through our partner Crisis Assistance Ministry, your contribution reaches people who need it most. Real impact. Real gratitude. Real thank-you. 💜"),
    ("Your donation is already working, {{NAME}} ⚡", "Your donation is already working ⚡", "No delays, no overhead — straight to the mission", "{{NAME}}, the moment your ${{AMOUNT}} donation came in, it joined the engine that powers OLI's Children's Hygiene Kit Drive. We keep our operations lean so your gift goes as far as possible.", "Through Crisis Assistance Ministry, it reaches Charlotte families in hardship — in the form of kids' toothbrushes, toothpaste, soap, and lotion. Already working. Thank you. ⚡"),
    ("{{NAME}}, you gave — and we're blown away 🙌", "You gave — and we're blown away 🙌", "Genuine gratitude from our entire team", "{{NAME}}, every donation to OLI feels meaningful. Your ${{AMOUNT}} gift is no exception — it's deeply appreciated by everyone on our team who has poured their energy into this mission.", "Your contribution goes toward 20,000 hygiene kits for Charlotte families through Crisis Assistance Ministry. You gave. We're blown away. Thank you. 🙌"),
    ("A family just got a little more hope 💜", "A family just got more hope 💜", "Because of your donation, {{NAME}}", "{{NAME}}, your ${{AMOUNT}} donation to One Love Initiative directly enables us to assemble more hygiene kits for Charlotte families in hardship. Those kits — assembled by student volunteers and delivered through Crisis Assistance Ministry — represent hope.", "A family gets a kit. A child gets a toothbrush. A parent has one less thing to worry about. Because of you. Thank you for making hope happen. 💜"),
    ("The numbers behind your gift are beautiful 🔢", "The numbers behind your gift 🔢", "{{NAME}}, here's the math of your ${{AMOUNT}} donation", "{{NAME}}, thank you for your donation of ${{AMOUNT}}! At OLI, we believe in transparency. Every dollar goes toward procuring and assembling hygiene kits — toothbrush, toothpaste, soap, lotion — for Charlotte children.", "Through Crisis Assistance Ministry, those kits reach families who need them. The numbers behind your gift add up to something beautiful. And we're grateful. 💜"),
    ("You're the backbone of this mission, {{NAME}} 💪", "You're the backbone of this mission 💪", "Donors make student nonprofits possible", "{{NAME}}, student nonprofits like OLI run on belief and energy — but they survive on support from people like you. Your ${{AMOUNT}} donation is the backbone that keeps our Children's Hygiene Kit Drive moving.", "Without donors, we don't have kits. Without kits, families don't get help. You're the link in that chain. Thank you, {{NAME}}. 💪"),
    ("We're working hard to be worthy of this, {{NAME}} 💜", "We're working hard to be worthy of this 💜", "Your trust inspires our best work", "{{NAME}}, every donation to OLI comes with a kind of trust — trust that we'll use it well, show up for Charlotte families, and keep pushing toward 20,000 hygiene kits. Your ${{AMOUNT}} just handed us that trust.", "We take it seriously. Your gift goes to Crisis Assistance Ministry distributions for Charlotte families in need. We're working hard every day to be worthy of it. Thank you. 💜"),
    ("You gave to something that gives forward 💜", "You gave to something that gives forward 💜", "The chain reaction of a ${{AMOUNT}} donation", "{{NAME}}, when you donate ${{AMOUNT}} to OLI, that money doesn't stop at us. It becomes a kit. The kit goes to Crisis Assistance Ministry. CAM gives it to a Charlotte family. A child's day gets better.", "Your gift gives forward. Multiple times. To multiple people. And it starts with you. Thank you for setting that chain in motion. 💜"),
    ("{{NAME}}, your heart is showing — in the best way 💜", "Your heart is showing 💜", "And Charlotte is better for it", "{{NAME}}, donating ${{AMOUNT}} to a student-led nonprofit says something about who you are — someone who sees need and decides to act. We're honored that OLI is where you directed that generosity.", "Your donation funds hygiene kits for Charlotte families through Crisis Assistance Ministry. Your heart is showing — and it's beautiful. Thank you. 💜"),
    ("This is how change happens, {{NAME}} ✊", "This is how change happens ✊", "One donation at a time", "{{NAME}}, change doesn't always start with a grand gesture. Sometimes it starts with a ${{AMOUNT}} donation to a student nonprofit trying to get hygiene kits to Charlotte families. That's your donation.", "That's how change happens — one kit, one family, one person deciding to give. You decided. We're grateful. Charlotte is better for it. ✊"),
    ("Your donation completes a circle, {{NAME}} 🔄", "Your donation completes a circle 🔄", "Here's how it all connects", "{{NAME}}, here's the circle: you donate → OLI assembles kits → Crisis Assistance Ministry distributes → a Charlotte family gets help → they have the dignity of basic hygiene. Your ${{AMOUNT}} completes that circle.", "We're honored to be the link that connects your generosity to families in need. Thank you for closing the loop. 💜"),
    ("You invested in Charlotte — thank you 🏙️", "You invested in Charlotte 🏙️", "And OLI is your vehicle for that investment", "{{NAME}}, think of your ${{AMOUNT}} donation as an investment in Charlotte. In its families. In the students who are trying to make it better. In the belief that community can close the gaps that systems leave behind.", "OLI and Crisis Assistance Ministry are your vehicle. 20,000 kits are the outcome. Thank you for investing in this city. 🏙️"),
    ("{{NAME}}, your support doesn't go unrecognized 💜", "Your support doesn't go unrecognized 💜", "We see every dollar — and we're grateful", "{{NAME}}, your ${{AMOUNT}} donation to One Love Initiative is recognized, appreciated, and celebrated by our team. We know that giving is a choice — and we don't take yours for granted.", "Every dollar goes toward hygiene kits for Charlotte families through Crisis Assistance Ministry. Every dollar is seen. Every dollar matters. Thank you. 💜"),
    ("Because of {{NAME}}, a child has cleaner hands 🧒", "Because of you, a child has cleaner hands 🧒", "That's the real outcome of your donation", "{{NAME}}, your generous donation of ${{AMOUNT}} helps us put hygiene supplies into the hands of Charlotte children who need them. Soap. Toothpaste. Toothbrush. Lotion. Simple things that make a real difference.", "Through Crisis Assistance Ministry, your gift reaches families in hardship. Because of you, a child has cleaner hands — and a little more dignity. Thank you. 💜"),
    ("We couldn't do this without donors like you 💜", "We couldn't do this without donors like you 💜", "And that's not a platitude — it's the truth", "{{NAME}}, One Love Initiative is student-powered, but it's donor-funded. Without contributions like your ${{AMOUNT}} gift, we can't procure supplies, assemble kits, or achieve our goal of 20,000 kits this summer.", "You make the mission financially possible. Through Crisis Assistance Ministry, your gift becomes real help for real families. We couldn't do this without you. Genuinely. Thank you. 💜"),
    ("Your ${{AMOUNT}} joins a growing fund of love 💜", "Your ${{AMOUNT}} joins a fund of love 💜", "{{NAME}}, this is what collective giving looks like", "{{NAME}}, one of the beautiful things about OLI's mission is that it's powered by collective giving — many people, each contributing what they can, all adding up to 20,000 hygiene kits for Charlotte families.", "Your ${{AMOUNT}} donation joins that collective. Through Crisis Assistance Ministry, it becomes part of the help that reaches families in hardship. Thank you for joining the fund of love. 💜"),
    ("OLI salutes you, {{NAME}} 🎖️", "OLI salutes you 🎖️", "Your donation puts you in the mission", "{{NAME}}, we want you to know that your ${{AMOUNT}} donation to One Love Initiative puts you in the mission. Not on the sidelines — in it. As a donor, you help make the Children's Hygiene Kit Drive a reality.", "Your gift flows through Crisis Assistance Ministry to Charlotte families who need it most. OLI salutes you for showing up. 🎖️"),
    ("You just made 20,000 feel closer, {{NAME}} 🎯", "You just made 20,000 feel closer 🎯", "Every donation moves the needle", "{{NAME}}, we're working toward 20,000 hygiene kits for Charlotte kids by end of summer — and your ${{AMOUNT}} donation just moved that number closer. Every donation does. But we feel every single one.", "Through Crisis Assistance Ministry, your contribution reaches Charlotte families in hardship. 20,000 feels closer because of you. Thank you. 🎯"),
    ("Your kindness echoes beyond this moment 💜", "Your kindness echoes beyond this moment 💜", "{{NAME}}, the reach of your donation is longer than you think", "{{NAME}}, your ${{AMOUNT}} donation to OLI doesn't just help one kit get packed. It enables an assembly process, a distribution chain through Crisis Assistance Ministry, and ultimately, relief for a Charlotte family.", "The echo of your kindness goes further than a dollar amount. It touches a child's morning routine, a family's day, a community's wellbeing. Thank you for that ripple. 💜"),
    ("You're exactly who OLI needs, {{NAME}} 💜", "You're exactly who OLI needs 💜", "And your donation proves it", "{{NAME}}, OLI needs students who care, community supporters who believe, and donors who give. You're in the last category today — and your ${{AMOUNT}} donation is exactly what we need to keep moving.", "Your gift funds hygiene kits for Charlotte families through Crisis Assistance Ministry. Exactly the right person. Exactly the right contribution. Thank you. 💜"),
    ("A student team says thank you, {{NAME}} 🎓", "A student team says thank you 🎓", "Your gift goes to the people actually doing the work", "{{NAME}}, the OLI team is made up of students — Prithivi, Saket, Rishi, and our growing volunteer family. When you donate ${{AMOUNT}}, you're directly supporting the work these students are doing for Charlotte.", "Your contribution fuels our Children's Hygiene Kit Drive and flows through Crisis Assistance Ministry to families in need. From our student team to you: a heartfelt thank you. 🎓"),
    ("We're holding your trust, {{NAME}} 💜", "We're holding your trust 💜", "And we take that seriously", "{{NAME}}, your ${{AMOUNT}} donation is more than money — it's trust. Trust that OLI is real, that we're doing what we say, that your gift will reach Charlotte families who need it. We hold that trust carefully.", "Your donation funds hygiene kits distributed through Crisis Assistance Ministry. We promise to honor your trust with every kit we pack. Thank you, {{NAME}}. 💜"),
    ("One Love Initiative thanks you with everything 💜", "One Love Initiative thanks you 💜", "{{NAME}}, we mean every word", "{{NAME}}, thank you for your donation of ${{AMOUNT}}. One Love Initiative thanks you with everything we have — with gratitude from our students, from the families we serve, and from the city of Charlotte.", "Your gift goes toward 20,000 Children's Hygiene Kits, distributed through Crisis Assistance Ministry. We mean every word of this thank-you. 💜"),
    ("You gave us momentum, {{NAME}} 🚀", "You gave us momentum 🚀", "And momentum is everything right now", "{{NAME}}, we're in the middle of our Children's Hygiene Kit Drive and every donation matters for momentum. Your ${{AMOUNT}} gift came at the right time and reminded our team why we're doing this.", "Through Crisis Assistance Ministry, your contribution flows to Charlotte families who need basic hygiene. You gave us momentum. And with it, more kits get packed. Thank you. 🚀"),
    ("Your donation is a vote for Charlotte families 🗳️", "Your donation is a vote for Charlotte families 🗳️", "{{NAME}}, you voted — and they benefit", "{{NAME}}, every donation to OLI is a vote — a statement that you believe Charlotte families deserve access to basic hygiene. Your ${{AMOUNT}} is a clear vote. And we hear it.", "That vote becomes hygiene kits, assembled by students and distributed through Crisis Assistance Ministry. We're proud to carry your vote forward. Thank you. 🗳️"),
    ("You made it real, {{NAME}} 💜", "You made it real 💜", "Belief is one thing. Giving makes it tangible.", "{{NAME}}, a lot of people believe in OLI's mission. But belief alone doesn't pack a kit. Your ${{AMOUNT}} donation takes belief and makes it tangible — real supplies, real kits, real help for Charlotte families.", "Through Crisis Assistance Ministry, your gift reaches families in hardship. You made the mission real today. Thank you. 💜"),
    ("Thank you for seeing us, {{NAME}} 💜", "Thank you for seeing us 💜", "OLI is a small team — your donation makes us feel seen", "{{NAME}}, One Love Initiative is small. We're students. We're figuring it out. So when someone donates ${{AMOUNT}} to support what we're building, it means more than the dollar amount — it means we've been seen.", "Your donation funds hygiene kits for Charlotte families through Crisis Assistance Ministry. Being seen keeps us going. Thank you for seeing OLI. 💜"),
    ("Your dollars become dignity, {{NAME}} 💜", "Your dollars become dignity 💜", "Here's the beautiful equation", "{{NAME}}, here's what ${{AMOUNT}} becomes when it comes to OLI: dignity. In the form of a child having a toothbrush. A family having soap. Basic things that too many people in Charlotte go without.", "Through our partner Crisis Assistance Ministry, your donation becomes those things — for real families, in real need. Dollars into dignity. Thank you, {{NAME}}. 💜"),
    ("You gave OLI exactly what we needed 💜", "You gave us exactly what we needed 💜", "{{NAME}}, your timing was perfect", "{{NAME}}, there's never a bad time to donate to OLI — but right now, mid-drive, every contribution counts double. Your ${{AMOUNT}} came exactly when we needed it, and we want you to know that.", "Your donation flows toward Children's Hygiene Kits distributed through Crisis Assistance Ministry. Your timing was perfect. Your generosity is everything. Thank you. 💜"),
    ("This is what community looks like, {{NAME}} 🤝", "This is what community looks like 🤝", "Your donation defines it", "{{NAME}}, community is a word that gets used a lot. Your ${{AMOUNT}} donation to One Love Initiative shows what it actually looks like: someone who sees a need in their city and decides to help.", "OLI channels that help into hygiene kits for Charlotte families through Crisis Assistance Ministry. You defined community today. Thank you. 🤝"),
    ("{{NAME}}, we won't forget this 💜", "We won't forget this 💜", "Your donation leaves a mark on our team", "{{NAME}}, your ${{AMOUNT}} donation to OLI leaves a mark on our team. It reminds us that the mission matters to people beyond our small circle — and it pushes us to keep showing up for Charlotte families.", "Your gift goes toward 20,000 hygiene kits, distributed through Crisis Assistance Ministry. We won't forget this. Thank you. 💜"),
    ("Your gift is wrapped in love, {{NAME}} 💜", "Your gift is wrapped in love 💜", "That's how OLI delivers it", "{{NAME}}, when your ${{AMOUNT}} donation becomes a hygiene kit for a Charlotte child, it carries something beyond the contents — the knowledge that someone cared enough to give. That's love wrapped in cardboard.", "Through Crisis Assistance Ministry, that kit reaches a family who needs it. Your gift, wrapped in love, delivered with care. Thank you, {{NAME}}. 💜"),
    ("We're building this together, {{NAME}} 🤝", "We're building this together 🤝", "Your ${{AMOUNT}} is a brick in the foundation", "{{NAME}}, OLI isn't built by one person or one team. It's built by a community of students, volunteers, and donors — people like you who put real resources toward a real mission.", "Your ${{AMOUNT}} donation is a brick in the foundation of 20,000 hygiene kits for Charlotte families. Through Crisis Assistance Ministry, it helps build something that lasts. Thank you. 🤝"),
    ("You funded something meaningful today, {{NAME}} 💜", "You funded something meaningful today 💜", "Not every dollar goes somewhere that matters this much", "{{NAME}}, your ${{AMOUNT}} donation to One Love Initiative went somewhere that matters — toward hygiene kits for Charlotte children who don't have access to the basics. That's meaningful. And we want you to know it.", "Through Crisis Assistance Ministry, your contribution reaches families in hardship. You funded something meaningful. We're grateful. 💜"),
    ("{{NAME}}, you added to the love 💜", "You added to the love 💜", "One Love Initiative just got a little stronger", "{{NAME}}, every donation to OLI adds to the collective force that drives our mission. Your ${{AMOUNT}} added to the love — the love for Charlotte, for its families, for the idea that basic hygiene should be available to everyone.", "Your donation goes toward 20,000 kits through Crisis Assistance Ministry. You added to the love. And it matters. Thank you. 💜"),
    ("Your confidence in OLI means everything 💜", "Your confidence in OLI means everything 💜", "{{NAME}}, thank you for trusting us with ${{AMOUNT}}", "{{NAME}}, choosing where to donate is a decision about trust. You trusted One Love Initiative with ${{AMOUNT}} — and we honor that. Your donation goes directly toward hygiene kits for Charlotte families.", "Through Crisis Assistance Ministry, it reaches people who need it most. Your confidence in OLI drives us to keep earning it. Thank you. 💜"),
    ("A little note from our volunteer team 💜", "From our volunteers — thank you 💜", "{{NAME}}, the people packing kits thank you too", "{{NAME}}, when OLI student volunteers pack kits, they often think about the donors who made those kits possible. Your ${{AMOUNT}} is one of those. They would want you to know: thank you.", "Your donation funds the kits they pack. Crisis Assistance Ministry gets those kits to Charlotte families. The volunteer team says thank you — right alongside the official team. 💜"),
    ("{{NAME}}, you're written into the OLI story 📖", "You're written into the OLI story 📖", "Every donor is part of this chapter", "{{NAME}}, One Love Initiative is writing a story about what a student team can build when the community shows up. Your ${{AMOUNT}} donation writes you into that story — as someone who chose to show up.", "Your chapter: funding hygiene kits for Charlotte families through Crisis Assistance Ministry. We're honored to include you. Thank you. 📖"),
    ("You gave from the heart — we give it forward 💜", "You gave from the heart 💜", "And OLI gives it forward to Charlotte families", "{{NAME}}, your ${{AMOUNT}} donation to One Love Initiative came from a place of generosity. We receive it with gratitude and give it forward — as hygiene kits, through Crisis Assistance Ministry, to Charlotte families in hardship.", "Heartfelt in. Hygiene out. Impact all around. Thank you for being the start of that chain. 💜"),
    ("Your donation shows up for people who need it 💜", "Your donation shows up for people 💜", "{{NAME}}, here's where your ${{AMOUNT}} goes", "{{NAME}}, your ${{AMOUNT}} donation doesn't sit around. It shows up — in the form of hygiene kits assembled by OLI volunteers, delivered through Crisis Assistance Ministry to Charlotte families who genuinely need them.", "You gave. We put it to work. Families get help. That's OLI's promise — and your donation makes it possible. Thank you. 💜"),
    ("We're inspired by you, {{NAME}} 💜", "We're inspired by you 💜", "Your donation fuels more than kits", "{{NAME}}, your ${{AMOUNT}} donation does two things: it funds hygiene kits for Charlotte families, and it inspires our team to push harder. Knowing that people like you are behind us makes a real difference.", "Through Crisis Assistance Ministry, your contribution reaches families in hardship. And it reaches the OLI team too — as inspiration. Thank you, {{NAME}}. 💜"),
    ("This is your impact, {{NAME}} ✨", "This is your impact ✨", "We want you to see what your ${{AMOUNT}} does", "{{NAME}}, your ${{AMOUNT}} donation to One Love Initiative has real, traceable impact: it funds hygiene kit procurement, enables student assembly, and flows through Crisis Assistance Ministry to Charlotte families in need.", "You donated. Here's what that means — in kits, in families helped, in a mission moving forward. This is your impact. Thank you. ✨"),
    ("No words are enough — but we'll try, {{NAME}} 💜", "No words are enough — but we'll try 💜", "Thank you for your generous donation", "{{NAME}}, there isn't a thank-you that fully captures what your ${{AMOUNT}} donation means to One Love Initiative. But we'll try: you made a difference. You chose Charlotte families. You chose OLI. And we're honored.", "Your donation funds hygiene kits through Crisis Assistance Ministry. No words are enough — but this one is real: thank you. 💜"),
    ("You're making 20,000 possible, {{NAME}} 🎯", "You're making 20,000 possible 🎯", "Our goal needs people like you", "{{NAME}}, OLI's goal of 20,000 hygiene kits for Charlotte families by summer 2025 doesn't happen without donors. Your ${{AMOUNT}} contribution is part of what makes that number possible.", "Through Crisis Assistance Ministry, every kit reaches a family who needs it. 20,000 is possible because you're in it. Thank you. 🎯"),
    ("Your act of giving creates an act of receiving 💜", "Your giving creates receiving 💜", "{{NAME}}, that's the simple beauty of what you did", "{{NAME}}, you gave ${{AMOUNT}}. Somewhere in Charlotte, a family will receive a hygiene kit. That's the direct, beautiful connection your donation creates — through OLI's assembly process and Crisis Assistance Ministry's distribution network.", "One act of giving. One act of receiving. One more family helped. Thank you for being the giving side of that equation. 💜"),
    ("Because of donors like you, OLI flies 💜", "Because of donors like you, OLI flies 💜", "{{NAME}}, your ${{AMOUNT}} gives us wings", "{{NAME}}, student nonprofits are powered by belief — but they fly on donations. Your ${{AMOUNT}} gift gives OLI the fuel to keep assembling kits, coordinating drives, and partnering with Crisis Assistance Ministry to reach Charlotte families.", "Because of donors like you, OLI flies. Thank you for the lift. 💜"),
    ("{{NAME}}, you're the reason this works 💜", "You're the reason this works 💜", "Community support is OLI's engine", "{{NAME}}, behind every hygiene kit OLI delivers is a donor who made it possible. Behind the donor is the belief that access to hygiene matters. Your ${{AMOUNT}} puts you in that line of belief — and we're grateful.", "Through Crisis Assistance Ministry, your donation reaches Charlotte families in hardship. You're the reason this works. Thank you. 💜"),
    ("Your donation is felt, {{NAME}} 💜", "Your donation is felt 💜", "Deep in the mission — and deep in our hearts", "{{NAME}}, we want you to know that your ${{AMOUNT}} donation is felt. By our team, who sees the donation and feels renewed purpose. By the volunteers who pack kits knowing support is behind them.", "And eventually, by the Charlotte families who receive those kits through Crisis Assistance Ministry. Felt all the way through. Thank you. 💜"),
    ("You gave {{NAME}} — now watch what happens 🌱", "You gave — now watch what happens 🌱", "Your ${{AMOUNT}} sets things in motion", "{{NAME}}, your ${{AMOUNT}} donation to OLI doesn't sit still. It's immediately put toward hygiene kit procurement. Those kits get assembled by student volunteers. They go to Crisis Assistance Ministry. Families receive them.", "You gave. Now watch what happens. And thank you for being the start of it. 🌱"),
    ("Your generosity is the fuel we run on 💜", "Your generosity is the fuel we run on 💜", "{{NAME}}, OLI is powered by people like you", "{{NAME}}, OLI runs on student energy and community generosity. Your ${{AMOUNT}} donation is the kind of generosity that keeps our Children's Hygiene Kit Drive moving forward — toward 20,000 kits, toward families in need.", "Through Crisis Assistance Ministry, your gift reaches Charlotte families. Your generosity is the fuel. We're grateful to run on it. Thank you. 💜"),
    ("Thank you for the gift of basics, {{NAME}} 🧴", "Thank you for the gift of basics 🧴", "Hygiene is basic. Not everyone has it. You helped.", "{{NAME}}, thank you for your donation of ${{AMOUNT}} to One Love Initiative. Hygiene is basic — but not everyone in Charlotte has access to it. Your gift helps close that gap, one kit at a time.", "Through Crisis Assistance Ministry, your contribution becomes a kids' toothbrush, toothpaste, soap, and lotion in the hands of a child who needs it. Thank you for giving the gift of basics. 🧴"),
    ("You showed up when it mattered, {{NAME}} 💜", "You showed up when it mattered 💜", "And right now, every donation matters", "{{NAME}}, we're in the active phase of our Children's Hygiene Kit Drive — and every donation that comes in right now accelerates our progress toward 20,000 kits. Your ${{AMOUNT}} showed up when it mattered.", "Through Crisis Assistance Ministry, your contribution reaches Charlotte families in hardship. Thank you for showing up. 💜"),
    ("From your wallet to a child's hand — thank you 🧒", "From your wallet to a child's hand 🧒", "{{NAME}}, this is the direct line your donation travels", "{{NAME}}, here's the path your ${{AMOUNT}} travels: from your donation → to OLI's procurement → to a student volunteer's hands assembling a kit → to Crisis Assistance Ministry → to a Charlotte child's hand.", "That's it. That's the whole chain. And you started it. From your wallet to a child's hand — thank you. 🧒"),
    ("This thank-you is just the beginning, {{NAME}} 💜", "This thank-you is just the beginning 💜", "We'll show you where your donation goes", "{{NAME}}, this email is the first of many thank-yous. Not from us — but from the mission itself. As OLI packs more kits, hits milestones, and reaches families through Crisis Assistance Ministry, you'll see where your ${{AMOUNT}} went.", "The real thank-you is the impact. And it's coming. For now — thank you, {{NAME}}, for being part of it. 💜"),
    ("${{AMOUNT}} well spent — we promise 💜", "${{AMOUNT}} well spent 💜", "{{NAME}}, we take that trust seriously", "{{NAME}}, when you donate to OLI, we understand you're trusting us to use that money well. Your ${{AMOUNT}} goes to hygiene kits for Charlotte families — not to overhead, not to administration, but to the mission itself.", "Through Crisis Assistance Ministry, it reaches families who need it most. ${{AMOUNT}} well spent. We promise. Thank you. 💜"),
    ("You gave. We're grateful. Charlotte wins. 💜", "You gave. We're grateful. Charlotte wins. 💜", "{{NAME}}, it's that simple — and that powerful", "{{NAME}}, thank you for your ${{AMOUNT}} donation to One Love Initiative. The equation is simple: you give, OLI assembles kits, Crisis Assistance Ministry distributes, Charlotte families win.", "You gave. We're grateful. Charlotte wins. Simple, powerful, and real. Thank you, {{NAME}}. 💜"),
    ("Your donation outlasts this moment 💜", "Your donation outlasts this moment 💜", "{{NAME}}, the impact is ongoing", "{{NAME}}, your ${{AMOUNT}} donation to OLI doesn't end when the kit is packed. Its impact outlasts the moment — in a child's dental health, a family's wellbeing, a community's slow but steady improvement.", "Through Crisis Assistance Ministry, your gift reaches Charlotte families and keeps giving. Thank you for a donation that outlasts the moment. 💜"),
    ("The OLI team is so thankful for you, {{NAME}} 💜", "The OLI team is so thankful for you 💜", "From Prithivi, Saket, Rishi, and every volunteer", "{{NAME}}, One Love Initiative is a team effort — Prithivi, Saket, Rishi, and a growing family of volunteers who show up for Charlotte families. On behalf of all of them: your ${{AMOUNT}} donation means everything to us.", "Your gift funds hygiene kits distributed through Crisis Assistance Ministry. The whole team feels this thank-you. Thank you, {{NAME}}. 💜"),
    ("You made the mission more possible, {{NAME}} 💜", "You made the mission more possible 💜", "One donation at a time — this is how it happens", "{{NAME}}, every donation to OLI makes the mission a little more possible. Your ${{AMOUNT}} is one of those donations — and with it, 20,000 hygiene kits for Charlotte families through Crisis Assistance Ministry becomes more achievable.", "One donation at a time. This is how it happens. Thank you for being one. 💜"),
    ("You're part of the 20,000 story, {{NAME}} 📖", "You're part of the 20,000 story 📖", "A milestone isn't reached without people like you", "{{NAME}}, when OLI delivers its 20,000th hygiene kit to a Charlotte family through Crisis Assistance Ministry, the story of how we got there will include donations like your ${{AMOUNT}} gift.", "You're a character in that story. The chapter is still being written. And we're so glad you're in it. Thank you, {{NAME}}. 💜"),
    ("Every Charlotte kit has a donor behind it 💜", "Every kit has a donor behind it 💜", "Today, {{NAME}}, you're that donor", "{{NAME}}, behind every OLI Kit delivered to a Charlotte family through Crisis Assistance Ministry is a student volunteer who packed it — and a donor who made it financially possible. Today, that donor is you.", "Your ${{AMOUNT}} funds those kits. The child who opens one doesn't know your name — but they benefit from your generosity. Thank you. 💜"),
    ("What you gave matters more than the amount, {{NAME}} 💜", "What you gave matters more than the amount 💜", "The act of giving is the most important thing", "{{NAME}}, the specific dollar amount of your donation matters — but what matters more is that you chose to give. You saw OLI's mission and decided it was worth supporting. That decision, regardless of size, is what drives us.", "Your ${{AMOUNT}} goes toward hygiene kits for Charlotte families through Crisis Assistance Ministry. And your choice to give goes toward our belief that what we're doing matters. Thank you. 💜"),
    ("You made today a great day for OLI, {{NAME}} 🎉", "You made today a great day 🎉", "And we want you to know it", "{{NAME}}, your ${{AMOUNT}} donation made today a great day for the One Love Initiative team. It's a reminder that the mission resonates, that the community is with us, and that Charlotte families will have more kits because of it.", "Through Crisis Assistance Ministry, your contribution reaches families in need. You made today great. Thank you. 🎉"),
    ("Your donation is a high five to the OLI team 🙌", "Your donation is a high five 🙌", "{{NAME}}, we felt it", "{{NAME}}, every donation to OLI is like a high five to our team — a signal that says 'keep going, you're doing something right.' Your ${{AMOUNT}} just sent that signal loud and clear.", "Your gift funds hygiene kits for Charlotte families through Crisis Assistance Ministry. High five received. Thank you, {{NAME}}. 🙌"),
    ("Thank you for caring about hygiene, {{NAME}} 💜", "Thank you for caring about hygiene 💜", "It's a more radical act than it sounds", "{{NAME}}, caring about whether Charlotte families have access to hygiene is more radical than it sounds. It means caring about dignity, about equity, about who gets the basics and who doesn't. Your ${{AMOUNT}} donation says you care about all of that.", "Through OLI and Crisis Assistance Ministry, your care reaches families who need it most. Thank you for caring about hygiene — and about Charlotte. 💜"),
    ("Every dollar you gave is working right now, {{NAME}} ⚡", "Every dollar is working right now ⚡", "No delays, no waste — straight to the mission", "{{NAME}}, the moment your ${{AMOUNT}} donation arrived, it joined the engine powering OLI's Children's Hygiene Kit Drive. There's no waiting around at OLI — your dollars go to work immediately.", "Through Crisis Assistance Ministry, your contribution reaches Charlotte families in hardship. Every dollar working. Right now. Thank you. ⚡"),
    ("Thank you for choosing to make a difference, {{NAME}} 💜", "You chose to make a difference 💜", "And that choice is the most important thing", "{{NAME}}, you had the choice to keep scrolling — and instead you donated ${{AMOUNT}} to One Love Initiative. That choice is what OLI is built on: people who see a need and decide to act.", "Your donation funds hygiene kits for Charlotte families through Crisis Assistance Ministry. Your choice made a difference. Thank you. 💜"),
    ("We're on the same team, {{NAME}} 🤝", "We're on the same team 🤝", "Your donation made it official", "{{NAME}}, there are donors and there are partners. We think of donors who give to OLI as partners — people who share our belief that Charlotte families deserve better. Your ${{AMOUNT}} donation made it official.", "You're on the team now. 20,000 hygiene kits. Crisis Assistance Ministry. Charlotte families. And you. Thank you for suiting up. 🤝"),
    ("Your gift lands with a family in Charlotte, {{NAME}} 💜", "Your gift lands with a family 💜", "Here's where it actually goes", "{{NAME}}, your ${{AMOUNT}} donation doesn't stay with OLI. It travels: to procurement, to assembly, to Crisis Assistance Ministry, and finally — to a Charlotte family experiencing hardship. Your gift lands there.", "In their hands. In their home. In a child's backpack. That's where your generosity goes. Thank you, {{NAME}}. 💜"),
    ("One last thing before we go, {{NAME}} — thank you 💜", "One last thing — thank you 💜", "We could say more. But this is the most important part.", "{{NAME}}, we could fill this email with impact data and mission updates — and we love sharing those things. But right now, the most important thing we want to say is simple: thank you for your ${{AMOUNT}} donation to OLI.", "It goes toward hygiene kits for Charlotte families through Crisis Assistance Ministry. It means the world to our team. And it makes a real difference. Thank you, {{NAME}}. 💜"),
    ("You're the reason families get kits, {{NAME}} 💜", "You're the reason families get kits 💜", "Your donation is the link that makes it all work", "{{NAME}}, the assembly line that creates OLI Kits — student volunteers, supplies, Crisis Assistance Ministry distribution — exists because of donor support. Your ${{AMOUNT}} is a critical link in that chain.", "Because of your donation, a Charlotte family that needed a hygiene kit got one. You're the reason that happened. Thank you. 💜"),
    ("Your donation planted a seed, {{NAME}} 🌱", "Your donation planted a seed 🌱", "And OLI will help it grow", "{{NAME}}, your ${{AMOUNT}} donation to One Love Initiative planted something. A kit that reaches a child. A belief that communities can close gaps. A mission that grows stronger every time someone gives.", "Through Crisis Assistance Ministry, your seed reaches Charlotte families in hardship. Watch it grow. And thank you for planting it. 🌱"),
    ("We're proud to have donors like you, {{NAME}} 💜", "We're proud to have donors like you 💜", "Genuinely — you represent the best of Charlotte", "{{NAME}}, the kind of person who donates to a student-led nonprofit doing hygiene kit drives — that's the best of Charlotte. Your ${{AMOUNT}} gift represents that community spirit, and we're proud to have you in OLI's corner.", "Your donation goes toward 20,000 kits distributed through Crisis Assistance Ministry. We're proud. And we're grateful. Thank you. 💜"),
    ("From OLI to you — a genuine thank you 💜", "From OLI to you — genuine gratitude 💜", "{{NAME}}, no template can capture this fully", "{{NAME}}, we use systems to send these emails — but the gratitude is completely genuine. Your ${{AMOUNT}} donation is felt by every member of the OLI team, from our founder Prithivi to every student volunteer who's ever packed a kit.", "That gratitude flows outward to Charlotte families through Crisis Assistance Ministry. Genuine thanks. Always. 💜"),
    ("You believed, you gave, and it matters 💜", "You believed, you gave, it matters 💜", "{{NAME}}, three simple truths about your donation", "{{NAME}}, three things are true: you believed in OLI enough to donate ${{AMOUNT}}. You gave — and we received it with full gratitude. And it matters — to our mission, to our team, and to the Charlotte families your donation will help.", "Through Crisis Assistance Ministry, your gift becomes hygiene kits for families in hardship. You believed. You gave. It matters. Thank you. 💜"),
    ("Thank you for being the change, {{NAME}} 💜", "Thank you for being the change 💜", "Gandhi was right — and so are you", "{{NAME}}, 'be the change you wish to see' gets quoted a lot. But you lived it — by donating ${{AMOUNT}} to One Love Initiative, you decided that Charlotte families deserve better and then did something about it.", "Your donation goes toward hygiene kits distributed through Crisis Assistance Ministry. You are the change. And we're deeply grateful for it. 💜"),
]

out = [{"id": f"thankyou-{i+1:03d}", "subject": t[0], "body": mkb(t[1], t[2], t[3], t[4])} for i, t in enumerate(T)]
path = os.path.join(os.path.dirname(__file__), "thankyou.json")
with open(path, "w", encoding="utf-8") as f:
    json.dump(out, f, indent=2, ensure_ascii=False)
print(f"Wrote {len(out)} thank-you templates to {path}")
