#!/usr/bin/env python3
import json, os

H = "<div style='font-family:Montserrat,Arial,sans-serif;max-width:600px;margin:0 auto;background:#f5f5f0;'><div style='background:linear-gradient(135deg,#7B5CF5,#9B7FF5);padding:28px 36px;text-align:center;'><img src='https://raw.githubusercontent.com/privi-doughnut/oneloveinitiative/main/OLI_LOGO.jpg' alt='OLI' style='width:64px;height:64px;border-radius:50%;object-fit:cover;border:3px solid rgba(255,255,255,0.3);'/><h1 style='color:#fff;font-size:18px;font-weight:800;margin:8px 0 0;letter-spacing:0.07em;'>ONE LOVE INITIATIVE</h1><p style='color:rgba(255,255,255,0.8);font-size:10px;margin:3px 0 0;letter-spacing:0.14em;text-transform:uppercase;'>Charlotte, NC &middot; Student-Led Nonprofit</p></div>"
F = "<div style='padding:16px 24px;background:#f5f5f0;text-align:center;border-top:1px solid #eee;'><p style='font-size:11px;color:#aaa;margin:0;'>2025 OLI &middot; <a href='https://oneloveinitative.org' style='color:#7B5CF5;text-decoration:none;'>Website</a> &middot; <a href='https://www.instagram.com/one.love.initiative/' style='color:#7B5CF5;text-decoration:none;'>Instagram</a> &middot; <a href='{{UNSUBSCRIBE_URL}}' style='color:#aaa;text-decoration:none;'>Unsubscribe</a></p></div></div>"

STATS = ("<div style='display:flex;gap:10px;margin:20px 0;'>"
    "<div style='flex:1;background:#f0ebff;border-radius:6px;padding:14px;text-align:center;'>"
    "<p style='color:#7B5CF5;font-size:20px;font-weight:800;margin:0 0 3px;'>{{KIT_COUNT}}</p>"
    "<p style='color:#888;font-size:10px;margin:0;letter-spacing:0.1em;text-transform:uppercase;'>Kits Packed</p>"
    "</div>"
    "<div style='flex:1;background:#f0ebff;border-radius:6px;padding:14px;text-align:center;'>"
    "<p style='color:#7B5CF5;font-size:20px;font-weight:800;margin:0 0 3px;'>{{VOLUNTEER_COUNT}}</p>"
    "<p style='color:#888;font-size:10px;margin:0;letter-spacing:0.1em;text-transform:uppercase;'>Volunteers</p>"
    "</div>"
    "<div style='flex:1;background:#f0ebff;border-radius:6px;padding:14px;text-align:center;'>"
    "<p style='color:#7B5CF5;font-size:20px;font-weight:800;margin:0 0 3px;'>{{KIT_GOAL}}</p>"
    "<p style='color:#888;font-size:10px;margin:0;letter-spacing:0.1em;text-transform:uppercase;'>Goal</p>"
    "</div>"
    "</div>")

def mkb(hl, sub, p1, p2, cta="See What's Ahead →", sg="The OLI Team"):
    return (H +
        "<div style='background:#fff;padding:32px 36px;'>"
        "<p style='color:#7B5CF5;font-size:10px;font-weight:700;letter-spacing:0.15em;text-transform:uppercase;margin:0 0 8px;'>{{MONTH}} {{YEAR}} &mdash; Monthly Update</p>"
        "<h2 style='color:#080808;font-size:22px;font-weight:800;margin:0 0 5px;line-height:1.3;'>" + hl + "</h2>"
        "<p style='color:#999;font-size:12px;font-style:italic;margin:0 0 18px;'>" + sub + "</p>"
        + STATS +
        "<p style='color:#444;font-size:14px;line-height:1.7;margin:0 0 12px;'>" + p1 + "</p>"
        "<p style='color:#444;font-size:14px;line-height:1.7;margin:0 0 24px;'>" + p2 + "</p>"
        "<div style='text-align:center;'><a href='https://oneloveinitative.org' style='background:#7B5CF5;color:#fff;padding:11px 26px;border-radius:5px;font-size:13px;font-weight:700;text-decoration:none;'>" + cta + "</a></div>"
        "<p style='color:#888;font-size:12px;margin:22px 0 0;'>With love,<br/><strong style='color:#7B5CF5;'>" + sg + "</strong></p>"
        "</div>" + F)

# (subject, headline, sub, p1, p2, cta)
T = [
    ("OLI {{MONTH}} Update — here's what happened 💜", "Here's what happened in {{MONTH}} 💜", "Your monthly dispatch from One Love Initiative", "Hey {{NAME}}! {{MONTH}} {{YEAR}} was another month of real progress for OLI. We packed {{KIT_COUNT}} hygiene kits this month — each one filled with a toothbrush, toothpaste, soap, and lotion for a Charlotte child in need.", "We're at {{KIT_COUNT}} total kits toward our goal of {{KIT_GOAL}}, powered by {{VOLUNTEER_COUNT}} amazing volunteers. Thank you for being part of this community. Here's what's coming next. 💜", "See What's Ahead →"),
    ("{{MONTH}} at OLI: the numbers + the story 🔢", "{{MONTH}} by the numbers — and by the heart 🔢", "Stats don't tell the full story. We'll tell both.", "{{NAME}}, here are {{MONTH}}'s numbers: {{KIT_COUNT}} kits packed, {{VOLUNTEER_COUNT}} volunteers who showed up. But behind those numbers is something numbers can't capture — students who stayed late, families who received supplies they couldn't afford.", "We're at {{KIT_COUNT}} of {{KIT_GOAL}} total kits. The numbers are moving. The mission is real. Thank you for following along. 💜", "See Our Full Progress →"),
    ("{{NAME}}, look what we did together in {{MONTH}} 🎯", "Look what we did in {{MONTH}} 🎯", "This is what your community support made possible", "{{NAME}}, {{MONTH}} {{YEAR}} is in the books — and it was a good one. OLI packed {{KIT_COUNT}} hygiene kits and welcomed {{VOLUNTEER_COUNT}} volunteers. Every single one matters. And you, as part of this community, made it possible.", "We're building toward {{KIT_GOAL}} kits total. Each month is a chapter. {{MONTH}} was a great one. Here's to what's next. 🎯", "See What's Coming →"),
    ("{{MONTH}} newsletter — progress, stories, what's next 💜", "{{MONTH}} at OLI — progress and stories 💜", "Your monthly front-row seat to the mission", "{{NAME}}, welcome to {{MONTH}}'s update from One Love Initiative! This month we packed {{KIT_COUNT}} kits with the help of {{VOLUNTEER_COUNT}} dedicated volunteers. Every kit goes to a Charlotte family through Crisis Assistance Ministry.", "Our total is climbing toward {{KIT_GOAL}}. The energy is incredible. The community is growing. And you're part of why. Thank you. 💜", "Read the Full Update →"),
    ("We've got good news, {{NAME}} — {{MONTH}} recap 🌟", "Good news from {{MONTH}} 🌟", "OLI had a month worth celebrating", "{{NAME}}, we've got good news for you: {{MONTH}} {{YEAR}} was a strong month for One Love Initiative. We packed {{KIT_COUNT}} hygiene kits and had {{VOLUNTEER_COUNT}} volunteers show up for Charlotte families. That's worth celebrating.", "We're on our way to {{KIT_GOAL}} total kits — and every month like this one gets us closer. Thank you for cheering us on. 🌟", "Celebrate With Us →"),
    ("Your monthly OLI update is here 📬", "Your {{MONTH}} OLI update 📬", "Everything you need to know from this past month", "{{NAME}}, here's your monthly update from One Love Initiative. In {{MONTH}} {{YEAR}}, we packed {{KIT_COUNT}} hygiene kits for Charlotte families in need, supported by {{VOLUNTEER_COUNT}} incredible volunteers across our drives.", "We're tracking toward our goal of {{KIT_GOAL}} total kits. The progress is real, and your support — as a subscriber and community member — is part of it. 💜", "See the Full Picture →"),
    ("{{MONTH}}: OLI packs kits and builds community 💜", "Kits packed. Community built. {{MONTH}} recap. 💜", "Two things happened this month — both matter", "{{NAME}}, two things happened in {{MONTH}} at OLI: we packed {{KIT_COUNT}} hygiene kits for Charlotte families, and we built a stronger community around the mission. {{VOLUNTEER_COUNT}} volunteers joined us this month.", "That community — including you — is what keeps OLI going. Total kits so far: {{KIT_COUNT}} of {{KIT_GOAL}}. Here's what we're planning next. 💜", "See Our Next Steps →"),
    ("From Charlotte, with love — {{MONTH}} update 🏙️", "From Charlotte, with love — {{MONTH}} 🏙️", "Another month of showing up for our city", "{{NAME}}, OLI showed up for Charlotte again in {{MONTH}} {{YEAR}}. {{KIT_COUNT}} hygiene kits packed, {{VOLUNTEER_COUNT}} student volunteers who gave their time and energy for families in need.", "This is what showing up for a city looks like — one kit, one volunteer, one family at a time. {{KIT_COUNT}} of {{KIT_GOAL}} total. We're getting there. 🏙️", "Follow Our Journey →"),
    ("{{NAME}}, here's your {{MONTH}} impact report 📊", "Your {{MONTH}} impact report 📊", "Real numbers. Real impact. Real people.", "{{NAME}}, here's the real-number impact of {{MONTH}} {{YEAR}} at One Love Initiative: {{KIT_COUNT}} hygiene kits assembled and delivered to Charlotte families through Crisis Assistance Ministry. {{VOLUNTEER_COUNT}} volunteers who made it happen.", "We're at {{KIT_COUNT}} of our {{KIT_GOAL}} kit goal. The impact is tangible. The progress is real. Thank you for being part of the story. 📊", "See Your Impact →"),
    ("Another month, another step forward — {{MONTH}} recap 🚀", "Another month. Another step forward. 🚀", "OLI's {{MONTH}} {{YEAR}} update", "{{NAME}}, every month at OLI is a step forward — and {{MONTH}} was no exception. We packed {{KIT_COUNT}} hygiene kits and had {{VOLUNTEER_COUNT}} volunteers join our drives. Charlotte families benefit from every step.", "We're at {{KIT_COUNT}} of {{KIT_GOAL}} total kits. The steps are adding up. Here's what the next month holds. 🚀", "See What's Next →"),
    ("{{MONTH}} was real — here's what happened at OLI 💜", "{{MONTH}} was real 💜", "A month of genuine progress and community", "{{NAME}}, we want to be honest with you: {{MONTH}} at OLI was a real, genuine effort. {{KIT_COUNT}} kits. {{VOLUNTEER_COUNT}} volunteers. Real families in Charlotte who received basic hygiene supplies through Crisis Assistance Ministry.", "No fluff, no spin — just progress. {{KIT_COUNT}} of {{KIT_GOAL}} total. And a team that's all in. Thank you for following along. 💜", "Read the Real Update →"),
    ("Students showed up in {{MONTH}} — see the results 🎓", "Students showed up in {{MONTH}} 🎓", "And the results are worth sharing", "{{NAME}}, {{VOLUNTEER_COUNT}} student volunteers showed up in {{MONTH}} and did real work for Charlotte families. Together, they packed {{KIT_COUNT}} hygiene kits — each one containing a toothbrush, toothpaste, soap, and lotion.", "We're at {{KIT_COUNT}} of our {{KIT_GOAL}} goal. And we're proving, month by month, that students can move mountains. Or at least, a lot of kits. 🎓", "See What They Did →"),
    ("{{NAME}}, OLI's {{MONTH}} numbers are in 🔢", "{{MONTH}} numbers are in 🔢", "And they tell a story worth reading", "{{NAME}}, the numbers for {{MONTH}} {{YEAR}} are in: {{KIT_COUNT}} kits packed, {{VOLUNTEER_COUNT}} volunteers, and a community that keeps growing. Each number represents real families helped in Charlotte through Crisis Assistance Ministry.", "Total progress: {{KIT_COUNT}} of {{KIT_GOAL}} kits. We love sharing these numbers because they're proof. Proof the mission is working. 💜", "See All the Numbers →"),
    ("The {{MONTH}} update — packed with good news 📦", "Packed with good news — {{MONTH}} update 📦", "Literally. We packed things. And there's good news.", "{{NAME}}, this month's newsletter is packed — literally. OLI packed {{KIT_COUNT}} hygiene kits in {{MONTH}} {{YEAR}}, with {{VOLUNTEER_COUNT}} volunteers making it happen. Each kit now lives with a Charlotte family through Crisis Assistance Ministry.", "The drive continues. {{KIT_COUNT}} down, {{KIT_GOAL}} is the target. Here's what the next chapter looks like. 📦", "See What's Packed →"),
    ("Charlotte's getting more kits — {{MONTH}} recap 🤍", "Charlotte's getting more kits 🤍", "Because of this community — month after month", "{{NAME}}, Charlotte is getting more hygiene kits because of OLI — and because of supporters like you who spread the word, volunteer, and donate. In {{MONTH}} {{YEAR}}, we packed {{KIT_COUNT}} kits with {{VOLUNTEER_COUNT}} volunteers.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}}. The city is getting more, because we're doing more. Thank you for being part of that. 🤍", "See Our Charlotte Impact →"),
    ("OLI's {{MONTH}} highlights — you'll want to see this 💜", "{{MONTH}} highlights at OLI 💜", "The moments worth sharing from this past month", "{{NAME}}, {{MONTH}} {{YEAR}} had some moments worth celebrating: {{KIT_COUNT}} hygiene kits packed and delivered, {{VOLUNTEER_COUNT}} volunteers who made drives run smoothly, and families in Charlotte who now have basic supplies.", "Highlights like these are what keep us going. {{KIT_COUNT}} of {{KIT_GOAL}} total. More to come. 💜", "See the Highlights →"),
    ("Behind the scenes of {{MONTH}} at OLI 🎬", "Behind the scenes of {{MONTH}} 🎬", "What it really looks like to run a kit drive", "{{NAME}}, behind the {{KIT_COUNT}} kits we packed in {{MONTH}} {{YEAR}} is a lot of unglamorous work — folding tables, supply inventories, volunteer coordination, and very long to-do lists. {{VOLUNTEER_COUNT}} volunteers made it all possible.", "But the result is real: more kits, more families helped, closer to {{KIT_GOAL}} total. Here's a behind-the-scenes look at what {{MONTH}} really looked like. 🎬", "Go Behind the Scenes →"),
    ("Progress report: {{MONTH}} at One Love Initiative 📈", "Progress report — {{MONTH}} {{YEAR}} 📈", "Transparency is part of who we are", "{{NAME}}, here's OLI's honest progress report for {{MONTH}} {{YEAR}}: {{KIT_COUNT}} hygiene kits packed. {{VOLUNTEER_COUNT}} volunteers engaged. Kits delivered through Crisis Assistance Ministry to Charlotte families in need.", "Total progress: {{KIT_COUNT}} of {{KIT_GOAL}}. Transparent, real, and moving in the right direction. Thank you for holding us accountable — and for cheering us on. 📈", "See Full Progress →"),
    ("{{MONTH}} flew by — here's what OLI accomplished 🕐", "{{MONTH}} flew by — here's what happened 🕐", "Fast month. Real results.", "{{NAME}}, {{MONTH}} went fast — but we made every week count. OLI packed {{KIT_COUNT}} hygiene kits and mobilized {{VOLUNTEER_COUNT}} volunteers for Charlotte families in need. Through Crisis Assistance Ministry, those kits are in homes now.", "{{KIT_COUNT}} of {{KIT_GOAL}} total kits. The month flew by. The impact didn't. 💜", "See What We Accomplished →"),
    ("This is what community does in {{MONTH}} 🤝", "This is what community does 🤝", "{{MONTH}} was a community effort — here's the proof", "{{NAME}}, {{MONTH}} at OLI was a community effort in every sense. {{VOLUNTEER_COUNT}} people gave their time. Donors gave resources. Partners like Crisis Assistance Ministry gave distribution infrastructure. The result: {{KIT_COUNT}} hygiene kits for Charlotte families.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}}. Community in action. And you're part of it. 🤝", "See the Community in Action →"),
    ("{{NAME}}, the OLI family had a great {{MONTH}} 💜", "The OLI family had a great {{MONTH}} 💜", "And you're part of this family", "{{NAME}}, the OLI family had a great {{MONTH}} {{YEAR}}: {{KIT_COUNT}} kits packed, {{VOLUNTEER_COUNT}} volunteers involved, and Charlotte families receiving hygiene supplies through Crisis Assistance Ministry. Great by any measure.", "Family progress: {{KIT_COUNT}} of {{KIT_GOAL}} kits. You're part of this family — and we wanted you to see what the family accomplished. 💜", "See the Family Update →"),
    ("Momentum is building — {{MONTH}} OLI recap 🚀", "Momentum is building 🚀", "{{MONTH}} shows it — here's the evidence", "{{NAME}}, the momentum at OLI is building — and {{MONTH}} {{YEAR}} is evidence. {{KIT_COUNT}} kits packed. {{VOLUNTEER_COUNT}} volunteers mobilized. Charlotte families receiving hygiene supplies through Crisis Assistance Ministry.", "Total kits: {{KIT_COUNT}} of {{KIT_GOAL}}. Momentum is what gets us there. Thank you for being part of it. 🚀", "Ride the Momentum →"),
    ("A recap of {{MONTH}} — and a look ahead 🔭", "{{MONTH}} recap and a look ahead 🔭", "Where we've been and where we're going", "{{NAME}}, let's look at {{MONTH}} {{YEAR}} first: {{KIT_COUNT}} hygiene kits packed, {{VOLUNTEER_COUNT}} volunteers, and real impact for Charlotte families through Crisis Assistance Ministry. That's where we've been.", "Now here's where we're going: {{KIT_GOAL}} total kits, more drives, more partnerships. {{KIT_COUNT}} down. Here's what's ahead. 🔭", "Look Ahead With Us →"),
    ("{{MONTH}} OLI update — because you should know 💜", "You should know what happened in {{MONTH}} 💜", "Transparency is how we build trust", "{{NAME}}, we share these monthly updates because you should know what OLI is doing with your attention, your support, and your community engagement. {{MONTH}} {{YEAR}}: {{KIT_COUNT}} kits, {{VOLUNTEER_COUNT}} volunteers, families helped.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}} kits. You should know — and now you do. Thank you for trusting us. 💜", "Stay in the Know →"),
    ("OLI's {{MONTH}} impact — from our team to your inbox 💜", "{{MONTH}} impact — from our team to you 💜", "Straight from the students doing the work", "{{NAME}}, straight from the OLI team to your inbox: {{MONTH}} {{YEAR}} was productive. {{KIT_COUNT}} hygiene kits packed by student volunteers. {{VOLUNTEER_COUNT}} people who gave their time. Kits delivered through Crisis Assistance Ministry to Charlotte families.", "From our team to yours: thank you for following the mission. {{KIT_COUNT}} of {{KIT_GOAL}} total kits. 💜", "Read Our Team Report →"),
    ("The kits keep coming — {{MONTH}} OLI newsletter 📦", "The kits keep coming 📦", "{{MONTH}} {{YEAR}} — OLI doesn't stop", "{{NAME}}, OLI doesn't stop — and {{MONTH}} is proof. {{KIT_COUNT}} hygiene kits packed and delivered to Charlotte families through Crisis Assistance Ministry. {{VOLUNTEER_COUNT}} volunteers who showed up. Another month of keeping the mission alive.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}}. The kits keep coming. So does our gratitude for your support. 💜", "See the Kits →"),
    ("{{MONTH}} was a chapter — here's how it reads 📖", "{{MONTH}} was a chapter 📖", "The OLI story, one month at a time", "{{NAME}}, every month at OLI is a chapter in a larger story. {{MONTH}} {{YEAR}}'s chapter: {{KIT_COUNT}} kits packed, {{VOLUNTEER_COUNT}} volunteers involved, Charlotte families helped through Crisis Assistance Ministry.", "The story so far: {{KIT_COUNT}} of {{KIT_GOAL}} total kits. The next chapter starts now. 📖", "Read the Next Chapter →"),
    ("You followed OLI — here's {{MONTH}}'s reward 🎁", "Here's your {{MONTH}} reward for following OLI 🎁", "Real updates, real progress, real community", "{{NAME}}, the reward for following One Love Initiative is getting to see real progress — not polished marketing, but genuine month-by-month impact. {{MONTH}} {{YEAR}}: {{KIT_COUNT}} kits, {{VOLUNTEER_COUNT}} volunteers, Charlotte families receiving hygiene supplies.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}}. Real updates. Real reward. Thank you for staying with us. 💜", "Claim Your Update →"),
    ("Small nonprofit. Big {{MONTH}}. Here's the recap. 💜", "Small nonprofit. Big {{MONTH}}. 💜", "Don't let our size fool you", "{{NAME}}, OLI is small — but don't let that fool you. In {{MONTH}} {{YEAR}}, we packed {{KIT_COUNT}} hygiene kits and mobilized {{VOLUNTEER_COUNT}} volunteers for Charlotte families in need. That's not small. That's a big deal.", "Total kits: {{KIT_COUNT}} of {{KIT_GOAL}}. Small nonprofit. Big heart. Even bigger results. 💜", "See What Small Can Do →"),
    ("OLI this {{MONTH}}: packed with purpose 💜", "Packed with purpose — {{MONTH}} at OLI 💜", "Literal and figurative", "{{NAME}}, OLI in {{MONTH}} {{YEAR}} was packed — literally ({{KIT_COUNT}} hygiene kits) and figuratively ({{VOLUNTEER_COUNT}} volunteers, drives, energy, purpose). All of it directed at getting hygiene supplies to Charlotte families through Crisis Assistance Ministry.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}}. Packed with purpose. Thank you for being part of it. 💜", "See What Purpose Looks Like →"),
    ("Every month at OLI is a gift — {{MONTH}} recap 🎁", "Every month is a gift 🎁", "{{MONTH}} {{YEAR}} gave us a lot to be grateful for", "{{NAME}}, every month of progress at OLI feels like a gift — and {{MONTH}} {{YEAR}} was generous. {{KIT_COUNT}} kits packed. {{VOLUNTEER_COUNT}} volunteers. Charlotte families receiving hygiene supplies through Crisis Assistance Ministry.", "Total kits gifted to Charlotte: {{KIT_COUNT}} toward {{KIT_GOAL}}. We're grateful for every month like this one. 🎁", "See the Gift →"),
    ("The {{MONTH}} highlights reel 🎬", "{{MONTH}} highlights reel 🎬", "The best moments from the past month at OLI", "{{NAME}}, here are {{MONTH}} {{YEAR}}'s best moments at OLI: {{KIT_COUNT}} hygiene kits packed and delivered, {{VOLUNTEER_COUNT}} volunteers who gave their time, and Charlotte families who received basic supplies through Crisis Assistance Ministry.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}} kits. The highlights reel is worth watching — and the best parts are yet to come. 🎬", "Watch the Highlights →"),
    ("{{NAME}}, this is what OLI did in {{MONTH}} 💜", "This is what OLI did in {{MONTH}} 💜", "Proof, in numbers and in story", "{{NAME}}, proof of OLI's {{MONTH}} {{YEAR}} work: {{KIT_COUNT}} hygiene kits assembled by student volunteers, {{VOLUNTEER_COUNT}} people who showed up, and Charlotte families who received those kits through Crisis Assistance Ministry.", "Total progress: {{KIT_COUNT}} of {{KIT_GOAL}} kits. This is what OLI does. Month after month. Thank you for watching. 💜", "See the Proof →"),
    ("One Love, one month — {{MONTH}} at OLI 💜", "One Love, one month 💜", "Here's what {{MONTH}} looked like at One Love Initiative", "{{NAME}}, one month, one love, one update: OLI packed {{KIT_COUNT}} hygiene kits in {{MONTH}} {{YEAR}}, supported by {{VOLUNTEER_COUNT}} volunteers. All of it powered by the belief that Charlotte families deserve basic hygiene.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}}. One Love. Every month. Thank you. 💜", "See One Month →"),
    ("Update: OLI hit milestones in {{MONTH}} 🎯", "Milestones in {{MONTH}} 🎯", "We're tracking toward something significant", "{{NAME}}, {{MONTH}} {{YEAR}} saw OLI hit real milestones: {{KIT_COUNT}} hygiene kits packed, {{VOLUNTEER_COUNT}} volunteers engaged, and continued progress toward our {{KIT_GOAL}}-kit goal for Charlotte families.", "Total: {{KIT_COUNT}} toward {{KIT_GOAL}}. Milestones are what momentum looks like. Thank you for being part of the march. 🎯", "Celebrate the Milestones →"),
    ("OLI recap: {{MONTH}} was loud 🔊", "{{MONTH}} was loud 🔊", "The quiet work made noise this month", "{{NAME}}, {{MONTH}} was loud at OLI — in the best way. {{KIT_COUNT}} kits packed. {{VOLUNTEER_COUNT}} volunteers mobilized. Charlotte families receiving hygiene supplies through Crisis Assistance Ministry. All of it adding up to something that's hard to ignore.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}}. Loud progress. Real impact. Thank you for listening. 🔊", "Hear About It →"),
    ("{{MONTH}} taught us something, {{NAME}} — here it is 💡", "{{MONTH}} taught us something 💡", "A lesson from the field at OLI", "{{NAME}}, every month of running kit drives teaches OLI something. {{MONTH}} {{YEAR}}'s lesson: {{VOLUNTEER_COUNT}} dedicated volunteers can pack {{KIT_COUNT}} kits and make a real, lasting difference for Charlotte families.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}} kits. Lesson learned. Applied next month. Thank you for following the learning curve. 💡", "Learn With Us →"),
    ("What {{MONTH}} looked like at OLI — a picture 🖼️", "What {{MONTH}} looked like at OLI 🖼️", "Paint this picture: students, kits, families, love", "{{NAME}}, here's a picture of {{MONTH}} {{YEAR}} at OLI: students at folding tables packing hygiene kits. {{VOLUNTEER_COUNT}} of them. {{KIT_COUNT}} kits assembled. All destined for Charlotte families through Crisis Assistance Ministry.", "Picture that scene multiplied by every month this summer. Total: {{KIT_COUNT}} of {{KIT_GOAL}} kits. That's the picture. 🖼️", "See the Picture →"),
    ("{{MONTH}} was about showing up — and we did 💜", "{{MONTH}} was about showing up 💜", "And OLI showed up — big time", "{{NAME}}, some months are about strategy and planning. {{MONTH}} {{YEAR}} was about showing up. OLI showed up: {{KIT_COUNT}} kits packed, {{VOLUNTEER_COUNT}} volunteers mobilized, Charlotte families helped through Crisis Assistance Ministry.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}}. Showing up is how we get there. And we showed up. 💜", "Show Up With Us →"),
    ("The {{MONTH}} OLI newsletter — from the heart 💜", "{{MONTH}} newsletter — from the heart 💜", "Not just data. The feeling behind it too.", "{{NAME}}, the feeling behind OLI's {{MONTH}} {{YEAR}} numbers: gratitude. For {{VOLUNTEER_COUNT}} volunteers who gave their time. For {{KIT_COUNT}} kits that will reach Charlotte families. For a community that keeps showing up.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}}. The data is real. The feeling is realer. Thank you. 💜", "Feel It With Us →"),
    ("You're watching OLI grow — {{MONTH}} update 🌱", "You're watching OLI grow 🌱", "And {{MONTH}} is another proof point", "{{NAME}}, as an OLI subscriber, you have a front-row seat to something growing. {{MONTH}} {{YEAR}} grew: {{KIT_COUNT}} kits packed, {{VOLUNTEER_COUNT}} volunteers recruited, Charlotte families helped through Crisis Assistance Ministry.", "Growth total: {{KIT_COUNT}} of {{KIT_GOAL}} kits. You're watching it in real time. We're glad you're here for it. 🌱", "Watch the Growth →"),
    ("OLI's {{MONTH}} dispatch — straight from Charlotte 🏙️", "{{MONTH}} dispatch from Charlotte 🏙️", "Real news from a real student nonprofit", "{{NAME}}, dispatching from Charlotte: OLI's {{MONTH}} {{YEAR}} update. {{KIT_COUNT}} hygiene kits packed and delivered through Crisis Assistance Ministry. {{VOLUNTEER_COUNT}} volunteers who put in real time for real families.", "Total kits: {{KIT_COUNT}} of {{KIT_GOAL}}. Real news from a real team doing real work. Thank you for receiving it. 🏙️", "Read the Dispatch →"),
    ("Good things came out of {{MONTH}} — here's what 💜", "Good things came out of {{MONTH}} 💜", "We want to share every one of them", "{{NAME}}, good things came out of {{MONTH}} {{YEAR}} at OLI, and we want to share them: {{KIT_COUNT}} kits packed, {{VOLUNTEER_COUNT}} volunteers, Charlotte families with more hygiene supplies thanks to Crisis Assistance Ministry.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}}. Good things. All of them worth sharing. Thank you for being here for them. 💜", "See All the Good →"),
    ("The OLI engine ran hard in {{MONTH}} ⚙️", "The OLI engine ran hard in {{MONTH}} ⚙️", "Under the hood of the Children's Hygiene Kit Drive", "{{NAME}}, the OLI engine ran hard in {{MONTH}} {{YEAR}}: {{KIT_COUNT}} kits assembled, {{VOLUNTEER_COUNT}} volunteers keeping the gears turning, and Charlotte families receiving hygiene supplies through Crisis Assistance Ministry.", "Total kits: {{KIT_COUNT}} of {{KIT_GOAL}}. The engine doesn't stop. And neither do we. ⚙️", "See the Engine →"),
    ("{{MONTH}} wrapped up — here's what we learned 📚", "{{MONTH}} wrapped — here's what we learned 📚", "Growth is a part of every OLI month", "{{NAME}}, {{MONTH}} {{YEAR}} wrapped up at OLI, and we always take a moment to reflect. What we learned: {{VOLUNTEER_COUNT}} volunteers can accomplish a lot. {{KIT_COUNT}} kits is a strong month. And the community's support is everything.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}} kits. Learned. Applied. Moving forward. Thank you for growing with us. 📚", "See What We Learned →"),
    ("OLI's {{MONTH}} was powered by community 🤝", "{{MONTH}} was powered by community 🤝", "Here's what that community accomplished", "{{NAME}}, OLI's community is what makes everything possible — and {{MONTH}} {{YEAR}} proved it. {{VOLUNTEER_COUNT}} community members gave their time. {{KIT_COUNT}} kits were packed and delivered to Charlotte families through Crisis Assistance Ministry.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}}. Community-powered. Community-proud. Thank you for being part of it. 🤝", "Join the Community →"),
    ("{{MONTH}} at OLI — raw and real 💜", "{{MONTH}} at OLI — raw and real 💜", "We don't sugarcoat. We just share.", "{{NAME}}, raw update from {{MONTH}} {{YEAR}}: {{KIT_COUNT}} kits packed. {{VOLUNTEER_COUNT}} volunteers. Some drives ran smoothly. Some were chaotic. All of them produced hygiene kits that reached Charlotte families through Crisis Assistance Ministry.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}}. Raw. Real. Always worth sharing. 💜", "Read the Real Update →"),
    ("Every month adds up — {{MONTH}} contribution 🔢", "Every month adds up 🔢", "{{MONTH}} is OLI's latest contribution to the total", "{{NAME}}, here's how progress works at OLI: each month adds kits to the total. {{MONTH}} {{YEAR}} added {{KIT_COUNT}} kits and {{VOLUNTEER_COUNT}} volunteer-hours to the mission. All destined for Charlotte families through Crisis Assistance Ministry.", "Running total: {{KIT_COUNT}} of {{KIT_GOAL}}. Adding up. Month by month. Thank you for watching. 🔢", "See the Running Total →"),
    ("OLI is on track — {{MONTH}} update says so 📈", "OLI is on track — {{MONTH}} confirms it 📈", "The numbers tell a story of real momentum", "{{NAME}}, {{MONTH}} {{YEAR}} confirms that OLI is on track. {{KIT_COUNT}} kits packed, {{VOLUNTEER_COUNT}} volunteers, Charlotte families helped through Crisis Assistance Ministry — all pointing in the right direction.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}} kits. On track. On mission. On it. Thank you for following. 📈", "See the Track →"),
    ("What a month, {{NAME}} — {{MONTH}} at OLI 🎉", "What a month — {{MONTH}} at OLI 🎉", "Here's why we're excited about this update", "{{NAME}}, we're excited about this month's update. {{MONTH}} {{YEAR}} brought {{KIT_COUNT}} kits, {{VOLUNTEER_COUNT}} volunteers, and continued progress toward getting hygiene supplies to Charlotte families through Crisis Assistance Ministry. What a month.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}}. We're excited. Hope you are too. 🎉", "Share the Excitement →"),
    ("OLI's {{MONTH}} story: students, kits, families 💜", "Students, kits, families — {{MONTH}}'s story 💜", "The three-part narrative of every OLI month", "{{NAME}}, every OLI month is a three-part story: students who show up ({{VOLUNTEER_COUNT}} this month), kits that get packed ({{KIT_COUNT}} this month), and Charlotte families who receive them through Crisis Assistance Ministry.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}}. Three parts. One mission. Always the same story — with better numbers each month. 💜", "Read This Month's Story →"),
    ("Real talk: OLI's {{MONTH}} update 💬", "Real talk: {{MONTH}} at OLI 💬", "Honest, straight-up update from the team", "{{NAME}}, real talk: {{MONTH}} {{YEAR}} was a solid month for OLI. {{KIT_COUNT}} kits packed. {{VOLUNTEER_COUNT}} volunteers. Charlotte families helped through Crisis Assistance Ministry. No exaggeration — just the honest truth of what we accomplished.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}}. Real talk. Real progress. Real gratitude. 💬", "Get the Real Update →"),
    ("OLI built something in {{MONTH}} — take a look 🏗️", "OLI built something in {{MONTH}} 🏗️", "{{KIT_COUNT}} kits and counting", "{{NAME}}, in {{MONTH}} {{YEAR}}, OLI built something: {{KIT_COUNT}} hygiene kits, an assembly of {{VOLUNTEER_COUNT}} volunteers, and real impact for Charlotte families through Crisis Assistance Ministry. That's not nothing. That's everything.", "Total built so far: {{KIT_COUNT}} of {{KIT_GOAL}} kits. Take a look at what we're constructing. 🏗️", "See What We're Building →"),
    ("The OLI train didn't stop in {{MONTH}} 🚂", "The OLI train didn't stop in {{MONTH}} 🚂", "Full speed toward {{KIT_GOAL}} kits", "{{NAME}}, the OLI train stayed on the tracks in {{MONTH}} {{YEAR}}: {{KIT_COUNT}} kits packed, {{VOLUNTEER_COUNT}} volunteers aboard, Charlotte families receiving hygiene supplies at every stop through Crisis Assistance Ministry.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}}. The train doesn't stop until we hit the goal. Thank you for riding with us. 🚂", "Stay on the Train →"),
    ("{{MONTH}} at OLI: how we did, what's next 🔭", "{{MONTH}} at OLI — how we did, what's next 🔭", "Honest assessment and forward look", "{{NAME}}, how OLI did in {{MONTH}} {{YEAR}}: {{KIT_COUNT}} kits, {{VOLUNTEER_COUNT}} volunteers, Charlotte families helped. Honest assessment: strong month. Room to grow. What's next: more drives, more kits, more families reached through Crisis Assistance Ministry.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}}. How we did. What's next. Thank you for being part of both. 🔭", "Look Ahead →"),
    ("OLI's monthly love letter — {{MONTH}} edition 💌", "A monthly love letter — {{MONTH}} edition 💌", "From OLI to the Charlotte community", "{{NAME}}, consider this a love letter — from OLI to the Charlotte community that makes our mission possible. {{MONTH}} {{YEAR}} brought {{KIT_COUNT}} kits, {{VOLUNTEER_COUNT}} volunteers, and families receiving hygiene supplies through Crisis Assistance Ministry.", "Total letters of love (kits): {{KIT_COUNT}} of {{KIT_GOAL}}. Thank you for being our inspiration for every single one. 💌", "Read the Love Letter →"),
    ("{{MONTH}}: the quiet work is adding up 💜", "The quiet work is adding up 💜", "{{MONTH}} at OLI — behind the scenes", "{{NAME}}, OLI's work is often quiet — volunteers packing kits, supplies being sorted, drives being coordinated. But the results of that quiet work are loud: {{KIT_COUNT}} kits in {{MONTH}} {{YEAR}}, {{VOLUNTEER_COUNT}} volunteers, Charlotte families helped.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}} kits. The quiet work adds up. Thank you for paying attention to it. 💜", "See the Quiet Work →"),
    ("{{MONTH}} numbers are moving in the right direction 📊", "Numbers moving in the right direction 📊", "{{MONTH}} {{YEAR}} — OLI's progress update", "{{NAME}}, OLI's {{MONTH}} {{YEAR}} numbers are moving in the right direction: {{KIT_COUNT}} kits packed (up from prior months), {{VOLUNTEER_COUNT}} volunteers engaged, Charlotte families receiving supplies through Crisis Assistance Ministry.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}}. Right direction. Right pace. Right mission. Thank you for following along. 📊", "See the Trend →"),
    ("We packed love into {{MONTH}} 💜", "We packed love into {{MONTH}} 💜", "Every kit was assembled with intention", "{{NAME}}, in {{MONTH}} {{YEAR}}, OLI packed {{KIT_COUNT}} hygiene kits with {{VOLUNTEER_COUNT}} volunteers who gave their time and energy for Charlotte families. Every kit assembled with intention — and with love.", "Total love packed: {{KIT_COUNT}} kits of {{KIT_GOAL}} total. More coming every month. Thank you for being part of the love. 💜", "See What Was Packed →"),
    ("OLI's {{MONTH}} in three words: kits, community, love 💜", "{{MONTH}} in three words: kits, community, love 💜", "Here's the full story behind those three words", "{{NAME}}, OLI's {{MONTH}} {{YEAR}} in three words: kits ({{KIT_COUNT}} packed), community ({{VOLUNTEER_COUNT}} volunteers), love (for Charlotte families receiving hygiene supplies through Crisis Assistance Ministry).", "Total: {{KIT_COUNT}} of {{KIT_GOAL}}. Three words. One mission. Always. 💜", "Read the Full Story →"),
    ("{{MONTH}} — OLI's quietest month was its best yet 💜", "Our quietest month — and our best 💜", "Sometimes the best work happens without fanfare", "{{NAME}}, {{MONTH}} {{YEAR}} wasn't our loudest month — it was our steadiest. {{KIT_COUNT}} kits packed, {{VOLUNTEER_COUNT}} volunteers, all quietly delivering impact for Charlotte families through Crisis Assistance Ministry.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}}. Quiet. Consistent. Building. Thank you for paying attention to the steady work. 💜", "See the Steady Progress →"),
    ("{{MONTH}} was a team effort — meet the team 🤝", "{{MONTH}} was a team effort 🤝", "The people behind the {{KIT_COUNT}} kits", "{{NAME}}, behind OLI's {{KIT_COUNT}} kits in {{MONTH}} {{YEAR}} is a team: {{VOLUNTEER_COUNT}} volunteers, our core staff, and partners at Crisis Assistance Ministry. Every single person matters to the final number.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}}. Team effort. Team result. Thank you for cheering the team on. 🤝", "Meet the Team →"),
    ("Another month, another step toward {{KIT_GOAL}} 🎯", "Another step toward {{KIT_GOAL}} 🎯", "{{MONTH}} at OLI — forward progress", "{{NAME}}, OLI is marching toward {{KIT_GOAL}} hygiene kits for Charlotte families — and {{MONTH}} {{YEAR}} was another step in that march. {{KIT_COUNT}} kits packed. {{VOLUNTEER_COUNT}} volunteers. Progress.", "Current step: {{KIT_COUNT}} of {{KIT_GOAL}} total kits. Every month is a step. Thank you for marching with us. 🎯", "March With Us →"),
    ("The {{MONTH}} OLI update — no fluff, all facts 📋", "No fluff — all facts about {{MONTH}} 📋", "Here's exactly what happened", "{{NAME}}, no fluff: OLI in {{MONTH}} {{YEAR}} packed {{KIT_COUNT}} hygiene kits with {{VOLUNTEER_COUNT}} volunteers and delivered them to Charlotte families through Crisis Assistance Ministry. That's the full fact set.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}}. All facts. No fluff. The way we like to communicate with you. 📋", "Get the Facts →"),
    ("{{MONTH}} was a proving ground for OLI 💪", "{{MONTH}} was a proving ground 💪", "We keep proving the mission is real", "{{NAME}}, every month OLI proves the mission is real — and {{MONTH}} {{YEAR}} was another proof point. {{KIT_COUNT}} kits packed, {{VOLUNTEER_COUNT}} volunteers mobilized, Charlotte families helped through Crisis Assistance Ministry.", "Total proof: {{KIT_COUNT}} of {{KIT_GOAL}} kits. Proven month after month. Thank you for believing in the proof. 💪", "See the Proof →"),
    ("OLI {{MONTH}}: building a record to be proud of 🏆", "Building a record to be proud of 🏆", "{{MONTH}} added to OLI's track record", "{{NAME}}, OLI is building a record — month by month, kit by kit. {{MONTH}} {{YEAR}} added {{KIT_COUNT}} kits and {{VOLUNTEER_COUNT}} volunteers to that record. Charlotte families received those kits through Crisis Assistance Ministry.", "Record total: {{KIT_COUNT}} of {{KIT_GOAL}}. We're proud of it. We think you should be too. 🏆", "See the Record →"),
    ("{{MONTH}}: Charlotte was cared for by OLI 🏙️", "Charlotte was cared for in {{MONTH}} 🏙️", "Here's how we showed up for the city", "{{NAME}}, in {{MONTH}} {{YEAR}}, OLI showed up for Charlotte: {{KIT_COUNT}} hygiene kits packed and delivered to families in need through Crisis Assistance Ministry. {{VOLUNTEER_COUNT}} volunteers who put the city first.", "Total care: {{KIT_COUNT}} of {{KIT_GOAL}} kits. Charlotte was cared for. It will continue to be. Thank you for being part of that commitment. 🏙️", "See How We Cared →"),
    ("OLI took {{MONTH}} seriously — here's the proof 💜", "We took {{MONTH}} seriously 💜", "Serious work for serious impact", "{{NAME}}, OLI takes every month seriously — because Charlotte families need real help, not performative effort. {{MONTH}} {{YEAR}}: {{KIT_COUNT}} kits, {{VOLUNTEER_COUNT}} volunteers, real impact through Crisis Assistance Ministry.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}}. Serious work. Real proof. Thank you for caring about what we do. 💜", "See the Serious Work →"),
    ("A student team's {{MONTH}} — dedicated to Charlotte 🎓", "A student team's {{MONTH}} — dedicated to Charlotte 🎓", "This is what dedication looks like", "{{NAME}}, dedication at OLI looks like this: students packing {{KIT_COUNT}} kits in {{MONTH}} {{YEAR}}, {{VOLUNTEER_COUNT}} volunteers giving up free time, and a consistent commitment to delivering hygiene supplies to Charlotte families.", "Total dedication: {{KIT_COUNT}} of {{KIT_GOAL}} kits. Dedicated. Every single month. 🎓", "See the Dedication →"),
    ("Every {{MONTH}} at OLI is a promise kept 💜", "Every month at OLI is a promise kept 💜", "We promised impact — {{MONTH}} proves we're delivering", "{{NAME}}, OLI made a promise: to pack hygiene kits for Charlotte families and do it with integrity. {{MONTH}} {{YEAR}} kept that promise: {{KIT_COUNT}} kits, {{VOLUNTEER_COUNT}} volunteers, distribution through Crisis Assistance Ministry.", "Total promises kept: {{KIT_COUNT}} of {{KIT_GOAL}} kits. We don't break promises. Thank you for holding us to them. 💜", "See the Promise Kept →"),
    ("OLI's {{MONTH}} season of giving 🎁", "{{MONTH}}'s season of giving 🎁", "Every month is a season of giving at OLI", "{{NAME}}, at OLI, every month is a season of giving — and {{MONTH}} {{YEAR}} was generous. {{KIT_COUNT}} hygiene kits given to Charlotte families through Crisis Assistance Ministry. {{VOLUNTEER_COUNT}} volunteers who gave their time.", "Total given: {{KIT_COUNT}} of {{KIT_GOAL}} kits. Giving season. Always. Thank you for giving your attention. 🎁", "See the Season →"),
    ("OLI in {{MONTH}}: we're not slowing down 🚀", "We're not slowing down 🚀", "{{MONTH}} {{YEAR}} keeps the momentum alive", "{{NAME}}, OLI is not slowing down — and {{MONTH}} {{YEAR}} is proof. {{KIT_COUNT}} hygiene kits packed, {{VOLUNTEER_COUNT}} volunteers involved, Charlotte families helped through Crisis Assistance Ministry. Full speed.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}} kits. Not slowing. Not stopping. Thank you for keeping up with us. 🚀", "Keep Up With Us →"),
    ("The people of OLI in {{MONTH}} — a tribute 💜", "A tribute to the people of {{MONTH}} 💜", "Behind the kits are people worth celebrating", "{{NAME}}, behind OLI's {{KIT_COUNT}} kits in {{MONTH}} {{YEAR}} are people worth celebrating: {{VOLUNTEER_COUNT}} volunteers who gave their time for Charlotte families. This update is dedicated to them — and to you, for following their work.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}} kits. People-first. Always. Thank you for being one of those people. 💜", "Celebrate the People →"),
    ("{{MONTH}} OLI: what we packed, why it matters 💜", "What we packed in {{MONTH}} — and why it matters 💜", "The meaning behind the numbers", "{{NAME}}, in {{MONTH}} {{YEAR}}, OLI packed {{KIT_COUNT}} hygiene kits. Here's why that matters: every kit contains a toothbrush, toothpaste, soap, and lotion — basics that {{VOLUNTEER_COUNT}} volunteers ensured Charlotte families would have.", "Through Crisis Assistance Ministry, those kits reach the families who need them most. Total: {{KIT_COUNT}} of {{KIT_GOAL}}. It matters. Always. 💜", "See Why It Matters →"),
    ("The OLI community had a strong {{MONTH}} 💜", "The OLI community had a strong {{MONTH}} 💜", "Community strength shows in the numbers", "{{NAME}}, the OLI community showed its strength in {{MONTH}} {{YEAR}}: {{VOLUNTEER_COUNT}} people gave their time, {{KIT_COUNT}} kits were packed, and Charlotte families received hygiene supplies through Crisis Assistance Ministry.", "Total community impact: {{KIT_COUNT}} of {{KIT_GOAL}} kits. Strong community. Strong month. Thank you for being part of the strength. 💜", "Join the Strong Community →"),
    ("OLI wraps {{MONTH}} — the numbers, the story, the future 💜", "{{MONTH}} wrapped — numbers, story, future 💜", "The complete {{MONTH}} OLI update", "{{NAME}}, the complete {{MONTH}} {{YEAR}} OLI update: Numbers ({{KIT_COUNT}} kits, {{VOLUNTEER_COUNT}} volunteers). Story (Charlotte families receiving hygiene supplies through Crisis Assistance Ministry). Future (more drives, more kits, more impact).", "Total: {{KIT_COUNT}} of {{KIT_GOAL}}. Complete picture. Thank you for wanting the full story. 💜", "Get the Complete Picture →"),
    ("OLI in {{MONTH}}: keeping the promise to Charlotte 💜", "Keeping the promise to Charlotte 💜", "Month by month, kit by kit", "{{NAME}}, OLI's promise to Charlotte: consistent, real impact for families in hardship. {{MONTH}} {{YEAR}} honored that promise: {{KIT_COUNT}} kits packed, {{VOLUNTEER_COUNT}} volunteers engaged, families helped through Crisis Assistance Ministry.", "Total promise kept: {{KIT_COUNT}} of {{KIT_GOAL}} kits. Month by month. Kit by kit. Thank you for holding us to it. 💜", "Hold Us to It →"),
    ("{{MONTH}}: OLI's best work yet 🌟", "{{MONTH}} — OLI's best work yet 🌟", "We keep getting better", "{{NAME}}, {{MONTH}} {{YEAR}} might be OLI's best month yet: {{KIT_COUNT}} kits packed, {{VOLUNTEER_COUNT}} volunteers, and Charlotte families receiving hygiene supplies through Crisis Assistance Ministry. The best keeps getting better.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}} kits. Best yet. Next month: even better. Thank you for watching us grow. 🌟", "See the Best →"),
    ("OLI's heart was on full display in {{MONTH}} 💜", "OLI's heart on full display in {{MONTH}} 💜", "The numbers show it — the stories prove it", "{{NAME}}, in {{MONTH}} {{YEAR}}, OLI's heart was on full display: {{VOLUNTEER_COUNT}} students who showed up, {{KIT_COUNT}} kits packed with intention, and Charlotte families receiving hygiene supplies with care through Crisis Assistance Ministry.", "Total heart shown: {{KIT_COUNT}} of {{KIT_GOAL}} kits. Full display. Every month. Thank you for seeing it. 💜", "See OLI's Heart →"),
    ("{{MONTH}} proves OLI means business 💪", "{{MONTH}} proves OLI means business 💪", "Results, month after month", "{{NAME}}, OLI means business — and {{MONTH}} {{YEAR}} proves it. {{KIT_COUNT}} hygiene kits. {{VOLUNTEER_COUNT}} volunteers. Charlotte families helped through Crisis Assistance Ministry. Results that speak for themselves.", "Total results: {{KIT_COUNT}} of {{KIT_GOAL}} kits. We mean business. Thank you for believing in our business. 💪", "See the Results →"),
    ("OLI {{MONTH}} — the community carried us 💜", "The community carried OLI in {{MONTH}} 💜", "And we're so grateful", "{{NAME}}, the OLI community carried us through {{MONTH}} {{YEAR}}: {{VOLUNTEER_COUNT}} volunteers who showed up, donors who gave resources, and supporters like you who spread the word. The result: {{KIT_COUNT}} kits for Charlotte families.", "Total carried: {{KIT_COUNT}} of {{KIT_GOAL}} kits. The community carried us. You're part of that community. Thank you. 💜", "Be the Community →"),
    ("OLI's {{MONTH}} — a month of action 🔥", "{{MONTH}} — a month of action 🔥", "No talk. Just kits.", "{{NAME}}, {{MONTH}} {{YEAR}} at OLI was a month of action — not talk. {{KIT_COUNT}} kits packed. {{VOLUNTEER_COUNT}} volunteers in action. Charlotte families receiving hygiene supplies through Crisis Assistance Ministry. All action.", "Total action: {{KIT_COUNT}} of {{KIT_GOAL}} kits. No talk. Just kits. Thank you for supporting the action. 🔥", "See the Action →"),
    ("{{MONTH}} at OLI: small acts, giant impact 💜", "Small acts, giant impact — {{MONTH}} at OLI 💜", "Here's what small acts add up to", "{{NAME}}, every kit packed in {{MONTH}} {{YEAR}} was a small act — one toothbrush, one bar of soap, one package of toothpaste, one bottle of lotion. But {{KIT_COUNT}} of those small acts, by {{VOLUNTEER_COUNT}} volunteers, creates giant impact.", "Through Crisis Assistance Ministry, that impact reaches Charlotte families. Total: {{KIT_COUNT}} of {{KIT_GOAL}}. Small acts. Giant impact. Thank you. 💜", "See the Giant Impact →"),
    ("The best part of {{MONTH}} was the people 💜", "The best part of {{MONTH}} was the people 💜", "And the people include you", "{{NAME}}, the best part of OLI's {{MONTH}} {{YEAR}} wasn't the {{KIT_COUNT}} kits (impressive as those are) — it was the {{VOLUNTEER_COUNT}} people who made them possible, and the community of supporters who cheer them on. Including you.", "Total people-powered kits: {{KIT_COUNT}} of {{KIT_GOAL}}. The people are the best part. Thank you for being one of them. 💜", "Thank the People →"),
    ("What we'll remember about {{MONTH}} at OLI 💜", "What we'll remember about {{MONTH}} 💜", "Some months leave a mark", "{{NAME}}, some months at OLI stand out. {{MONTH}} {{YEAR}} will be remembered for {{KIT_COUNT}} kits, {{VOLUNTEER_COUNT}} volunteers who pushed the mission forward, and Charlotte families who received hygiene supplies through Crisis Assistance Ministry.", "Total memories packed: {{KIT_COUNT}} of {{KIT_GOAL}} kits. We'll remember {{MONTH}}. Thank you for being part of it. 💜", "Help Us Remember →"),
    ("OLI's {{MONTH}}: from first kit to last — a recap 💜", "From first kit to last — {{MONTH}} recap 💜", "The complete picture of OLI's {{MONTH}} {{YEAR}}", "{{NAME}}, from the first kit packed to the last one delivered in {{MONTH}} {{YEAR}}, OLI's process is consistent: student volunteers assemble hygiene kits, Crisis Assistance Ministry distributes them, Charlotte families receive them.", "{{KIT_COUNT}} kits in {{MONTH}} alone. {{VOLUNTEER_COUNT}} volunteers who made it happen. Total: {{KIT_COUNT}} of {{KIT_GOAL}}. First to last. Always. 💜", "See the Full Picture →"),
    ("OLI's heart beats for Charlotte — {{MONTH}} update 💜", "OLI's heart beats for Charlotte 💜", "{{MONTH}} {{YEAR}} — the pulse of the mission", "{{NAME}}, OLI's heart beats for Charlotte — and {{MONTH}} {{YEAR}} is the pulse check: {{KIT_COUNT}} kits packed, {{VOLUNTEER_COUNT}} volunteers engaged, families receiving hygiene supplies through Crisis Assistance Ministry.", "Pulse total: {{KIT_COUNT}} of {{KIT_GOAL}} kits. Beating strong. Thank you for keeping it going with your support. 💜", "Feel the Pulse →"),
    ("OLI's {{MONTH}} promise: fulfilled 💜", "{{MONTH}} promise: fulfilled 💜", "We said we'd show up. We did.", "{{NAME}}, OLI's promise to Charlotte is simple: show up every month, pack kits, and get them to families who need them. {{MONTH}} {{YEAR}} fulfilled that promise: {{KIT_COUNT}} kits, {{VOLUNTEER_COUNT}} volunteers, Crisis Assistance Ministry distribution.", "Total promises fulfilled: {{KIT_COUNT}} of {{KIT_GOAL}} kits. Promise kept. Always. Thank you for keeping us accountable. 💜", "See the Fulfillment →"),
    ("Thank you for {{MONTH}}, {{NAME}} — from OLI 💜", "Thank you for being here in {{MONTH}} 💜", "Your support makes every month possible", "{{NAME}}, as {{MONTH}} {{YEAR}} wraps up, we want to say thank you — for following OLI, for your support, for caring about Charlotte families. Your presence in this community made {{KIT_COUNT}} kits and {{VOLUNTEER_COUNT}} volunteers possible.", "Total: {{KIT_COUNT}} of {{KIT_GOAL}} kits. None of it without you. Thank you for {{MONTH}}. Thank you for being here. 💜", "Stay With Us →"),
    ("OLI's {{MONTH}} dispatch — more kits, more love 💜", "More kits, more love — {{MONTH}} dispatch 💜", "The mission grows every single month", "{{NAME}}, OLI's {{MONTH}} {{YEAR}} dispatch is here: {{KIT_COUNT}} hygiene kits packed by {{VOLUNTEER_COUNT}} student volunteers, now reaching Charlotte families through Crisis Assistance Ministry. More kits, more love — every month.", "Running total: {{KIT_COUNT}} of {{KIT_GOAL}}. The love keeps growing. Thank you for reading, sharing, and caring. 💜", "Read the Full Dispatch →"),
    ("{{MONTH}} momentum at OLI 🚀", "{{MONTH}} momentum — we're moving 🚀", "Once a mission gets rolling it's hard to stop", "{{NAME}}, momentum is a real thing — and OLI has it. {{MONTH}} {{YEAR}} added {{KIT_COUNT}} kits and {{VOLUNTEER_COUNT}} volunteers to our running total. Charlotte families are feeling it through Crisis Assistance Ministry distribution.", "Running total: {{KIT_COUNT}} of {{KIT_GOAL}} kits. Momentum building. Thank you for being part of the force behind it. 🚀", "Keep the Momentum →"),
    ("Behind the scenes of OLI's {{MONTH}} 🎬", "Behind the scenes — {{MONTH}} at OLI 🎬", "What actually happens when we pack kits", "{{NAME}}, here's what {{MONTH}} {{YEAR}} looked like behind the scenes at OLI: {{VOLUNTEER_COUNT}} students gathering, sorting toothbrushes, toothpaste, soap, and lotion into kits, laughing, working, caring. {{KIT_COUNT}} kits is what comes out the other side.", "Those kits reach Charlotte families through Crisis Assistance Ministry. Total: {{KIT_COUNT}} of {{KIT_GOAL}}. Behind the scenes is where the magic happens. 🎬", "Go Behind the Scenes →"),
    ("OLI's {{MONTH}}: driven by students, powered by community 🧡", "Driven by students, powered by community 🧡", "{{MONTH}} {{YEAR}} — a true team effort", "{{NAME}}, OLI's model is simple: students drive the mission, the community powers it. In {{MONTH}} {{YEAR}}, {{VOLUNTEER_COUNT}} student volunteers packed {{KIT_COUNT}} kits — powered by donors and supporters exactly like you.", "Total kits powered: {{KIT_COUNT}} of {{KIT_GOAL}}. Students drive. Community powers. Thank you for your part. 🧡", "Power the Mission →"),
    ("{{MONTH}} wrap: OLI by the stats 📊", "{{MONTH}} wrap: OLI by the stats 📊", "The numbers that matter most this month", "{{NAME}}, OLI's {{MONTH}} {{YEAR}} stats are in: {{KIT_COUNT}} hygiene kits packed, {{VOLUNTEER_COUNT}} volunteers who gave their time, and families across Charlotte receiving supplies through Crisis Assistance Ministry. Stats with a soul.", "Running kit total: {{KIT_COUNT}} of {{KIT_GOAL}}. Stats tell the story. Thank you for making it a good one. 📊", "See All the Stats →"),
    ("OLI keeps going — {{MONTH}} roundup 💜", "OLI keeps going — {{MONTH}} roundup 💜", "Consistency is how we change the world", "{{NAME}}, OLI keeps going — that's the whole deal. {{MONTH}} {{YEAR}} roundup: {{KIT_COUNT}} kits, {{VOLUNTEER_COUNT}} volunteers, and kits reaching Charlotte families through Crisis Assistance Ministry. Same mission. Same dedication. Different month.", "Cumulative dedication: {{KIT_COUNT}} of {{KIT_GOAL}} kits. We keep going. Thank you for keeping up with us. 💜", "Keep Going With Us →"),
    ("{{MONTH}} at OLI — every kit has a name on it 💜", "Every kit has a name on it — {{MONTH}} at OLI 💜", "Not literally. But each one is meant for someone real.", "{{NAME}}, each of the {{KIT_COUNT}} kits OLI packed in {{MONTH}} {{YEAR}} was meant for a real Charlotte child — a real toothbrush for a real smile, real soap for real clean hands. {{VOLUNTEER_COUNT}} volunteers packed them with real care.", "Through Crisis Assistance Ministry, they reach real families. Total: {{KIT_COUNT}} of {{KIT_GOAL}}. Every kit has a name on it. 💜", "Pack a Kit →"),
    ("The OLI community showed out in {{MONTH}} 💜", "The OLI community showed out in {{MONTH}} 💜", "Charlotte showed up — and so did you", "{{NAME}}, the OLI community showed out in {{MONTH}} {{YEAR}} — {{VOLUNTEER_COUNT}} volunteers, {{KIT_COUNT}} kits, and an entire Charlotte community behind a student-led nonprofit doing real work. Showing out is what we do.", "Total kits from showing out: {{KIT_COUNT}} of {{KIT_GOAL}}. Thank you for being the kind of community that shows out. 💜", "Show Out With Us →"),
    ("{{MONTH}} news from OLI — it's all good 🌟", "All good news from OLI — {{MONTH}} {{YEAR}} 🌟", "Some months deliver nothing but good news", "{{NAME}}, here's all good news from OLI's {{MONTH}} {{YEAR}}: {{KIT_COUNT}} kits packed, {{VOLUNTEER_COUNT}} volunteers engaged, Charlotte families receiving hygiene kits through Crisis Assistance Ministry. No bad news. Just mission.", "Total good news: {{KIT_COUNT}} of {{KIT_GOAL}} kits. All good. Thank you for supporting something that delivers it. 🌟", "Get More Good News →"),
    ("OLI's {{MONTH}} update — building toward something big 💜", "Building toward something big — {{MONTH}} update 💜", "Every kit is a brick in something greater", "{{NAME}}, every OLI kit is a brick in something bigger: a community that takes care of its own. {{MONTH}} {{YEAR}} added {{KIT_COUNT}} bricks, laid by {{VOLUNTEER_COUNT}} volunteers. Charlotte families receive them through Crisis Assistance Ministry.", "Total bricks: {{KIT_COUNT}} of {{KIT_GOAL}} kits. The structure is rising. Thank you for supporting the build. 💜", "See What We're Building →"),
    ("From Charlotte with love — {{MONTH}} OLI update 💜", "From Charlotte with love — {{MONTH}} {{YEAR}} 💜", "This city is something special. So is this mission.", "{{NAME}}, OLI is Charlotte — born here, built here, doing its work here. {{MONTH}} {{YEAR}} update: {{KIT_COUNT}} kits packed by {{VOLUNTEER_COUNT}} student volunteers, distributed to Charlotte families through Crisis Assistance Ministry. From Charlotte with love.", "Total love packed: {{KIT_COUNT}} of {{KIT_GOAL}} kits. From Charlotte. With love. Always. 💜", "Spread the Love →"),
]

out = [{"id": f"newsletter-{i+1:03d}", "subject": t[0], "body": mkb(t[1], t[2], t[3], t[4], *(t[5:6] or ["See What's Ahead →"]))} for i, t in enumerate(T)]
path = os.path.join(os.path.dirname(__file__), "newsletter.json")
with open(path, "w", encoding="utf-8") as f:
    json.dump(out, f, indent=2, ensure_ascii=False)
print(f"Wrote {len(out)} newsletter templates to {path}")
