#!/usr/bin/env python3
import json, os

H = "<div style='font-family:Montserrat,Arial,sans-serif;max-width:600px;margin:0 auto;background:#f5f5f0;'><div style='background:linear-gradient(135deg,#7B5CF5,#9B7FF5);padding:28px 36px;text-align:center;'><img src='https://raw.githubusercontent.com/privi-doughnut/oneloveinitiative/main/OLI_LOGO.jpg' alt='OLI' style='width:64px;height:64px;border-radius:50%;object-fit:cover;border:3px solid rgba(255,255,255,0.3);'/><h1 style='color:#fff;font-size:18px;font-weight:800;margin:8px 0 0;letter-spacing:0.07em;'>ONE LOVE INITIATIVE</h1><p style='color:rgba(255,255,255,0.8);font-size:10px;margin:3px 0 0;letter-spacing:0.14em;text-transform:uppercase;'>Charlotte, NC &middot; Student-Led Nonprofit</p></div>"
F = "<div style='padding:16px 24px;background:#f5f5f0;text-align:center;border-top:1px solid #eee;'><p style='font-size:11px;color:#aaa;margin:0;'>2025 OLI &middot; <a href='https://oneloveinitative.org' style='color:#7B5CF5;text-decoration:none;'>Website</a> &middot; <a href='https://www.instagram.com/one.love.initiative/' style='color:#7B5CF5;text-decoration:none;'>Instagram</a> &middot; <a href='{{UNSUBSCRIBE_URL}}' style='color:#aaa;text-decoration:none;'>Unsubscribe</a></p></div></div>"

def mkb(hl, sub, p1, p2, cta, sg="The OLI Team"):
    return (H +
        "<div style='background:#fff;padding:32px 36px;'>"
        "<h2 style='color:#7B5CF5;font-size:22px;font-weight:800;margin:0 0 5px;line-height:1.3;'>" + hl + "</h2>"
        "<p style='color:#999;font-size:12px;font-style:italic;margin:0 0 18px;'>" + sub + "</p>"
        "<p style='color:#444;font-size:14px;line-height:1.7;margin:0 0 12px;'>" + p1 + "</p>"
        "<p style='color:#444;font-size:14px;line-height:1.7;margin:0 0 24px;'>" + p2 + "</p>"
        "<div style='text-align:center;'><a href='https://oneloveinitative.org' style='background:#7B5CF5;color:#fff;padding:11px 26px;border-radius:5px;font-size:13px;font-weight:700;text-decoration:none;'>" + cta + "</a></div>"
        "<p style='color:#888;font-size:12px;margin:22px 0 0;'>With love, <strong style='color:#7B5CF5;'>" + sg + "</strong></p>"
        "</div>" + F)

# (subject, headline, sub, p1, p2, cta)
T = [
    ("Welcome to One Love Initiative! 💜", "You're officially family now 💜", "Welcome to the One Love Initiative", "Hi {{NAME}} — we're so glad you found us! OLI is a student-led nonprofit in Charlotte packing hygiene kits for families in need. Our mission: 20,000 children's kits by summer 2025.", "Each kit: toothbrush, toothpaste, soap, lotion — delivered through Crisis Assistance Ministry to Charlotte families. You're part of this story now. 💜", "Explore Our Mission →"),
    ("20,000 kits. One summer. You're in. 🎯", "The mission just got stronger 🎯", "20,000 kits. One summer. Let's go.", "{{NAME}}, we're chasing 20,000 hygiene kits for Charlotte kids before summer ends. Every subscriber, volunteer, and share gets us closer. You just helped.", "Student-powered, community-driven, committed to the belief that hygiene is a right — not a luxury. Welcome to the movement. 🌱", "See Our Drive →"),
    ("A personal note from our founder 💌", "From our founder's desk 💌", "Prithivi here — welcome", "{{NAME}}, when I started OLI I never expected this many people to show up. But here you are — and it genuinely means everything to our team.", "Our goal: 20,000 hygiene kits for Charlotte children through Crisis Assistance Ministry. So glad you're here. — Prithivi, Founder 💜", "Join Our Journey →"),
    ("Charlotte just gained an amazing supporter 🌟", "One city. One love. One community. 🌟", "Charlotte shows up — and so do you", "{{NAME}}, Charlotte is a city that shows up for its people — and you just proved it. We're students packing hygiene kits for Charlotte families, one kit at a time.", "Together we're working toward 20,000 children's kits this summer through Crisis Assistance Ministry. You're part of something real. 🏙️", "See What We Do →"),
    ("Students are changing Charlotte — you said yes 💪", "Young people doing the work 💪", "Students building real change in Charlotte", "{{NAME}}, we're full-time students who decided waiting wasn't an option. One Love Initiative was born from that urgency — and it grows because of people like you.", "This summer: 20,000 hygiene kits for Charlotte kids. Your support is part of that race. 🎓", "Meet the Team →"),
    ("Your inbox just got more purposeful ✨", "Here's what being subscribed to OLI means ✨", "Your new source of good news", "{{NAME}}, from here you'll hear drive updates, impact stories, and ways to get involved. We don't spam — we share what matters.", "We're in our Children's Hygiene Kit Drive, aiming for 20,000 kits by summer's end. Every update is a step closer. 💜", "See Our Current Drive →"),
    ("Here's everything you need to know about OLI 📋", "OLI 101 — your quick start guide 📋", "Everything about us in one email", "{{NAME}}, OLI is a student-led nonprofit in Charlotte, NC, founded by Prithivi Vijayakumar in 2025. We pack hygiene kits and distribute them to families through Crisis Assistance Ministry.", "Current drive: Children's Hygiene Kits (toothbrush, toothpaste, soap, lotion). Goal: 20,000 kits. You're officially in the loop! 📦", "Explore the Full Story →"),
    ("You just joined a movement 🔥", "This is bigger than a mailing list 🔥", "Welcome to a community with purpose", "{{NAME}}, subscribing to OLI isn't just signing up for emails — it's joining a community that believes access to hygiene is a right, not a luxury.", "This summer we're mobilizing for 20,000 children's hygiene kits across Charlotte. You're part of the force making that happen. 🔥", "Get Involved →"),
    ("What's inside an OLI Kit? 📦", "The four items that say: someone cares 📦", "Inside every kit is a message", "{{NAME}}, every OLI Kit contains four simple things: a kids' toothbrush, kids' toothpaste, kid-friendly soap, and kid-friendly lotion. For a family in need, it's everything.", "We're packing 20,000 of these for Charlotte kids this summer through Crisis Assistance Ministry. Imagine a child opening one. That's our why. 💜", "Help Us Pack 20,000 →"),
    ("Big dreams, student hearts 💜", "Big dreams. Student hearts. 💜", "Welcome from three young people who decided to act", "{{NAME}}, OLI was started by a student who got tired of seeing need and doing nothing. That student is Prithivi — alongside Saket and Rishi, they built this from scratch.", "Zero budget. Zero backup. Just belief — and a growing community that now includes you. Thank you. 🌱", "Learn Our Story →"),
    ("One kit = 4 items = real impact 🧮", "The math of giving 🧮", "Let's talk numbers", "{{NAME}}, one OLI Kit: 4 hygiene items. Goal: 20,000 kits. That's 80,000 individual items going to Charlotte families through Crisis Assistance Ministry this summer.", "Every subscriber who shares, every volunteer who packs, every donor who gives multiplies that number. You just joined the equation. ➕", "See Our Progress →"),
    ("From Charlotte with love 👋", "Proudly Charlotte-based 👋", "Local students. Local mission. Local love.", "{{NAME}}, we're not a national org or corporate charity. We're students from Charlotte, working for Charlotte, driven by love for this community. Everything we do is personal.", "This summer: 20,000 kits to Charlotte families through Crisis Assistance Ministry. Welcome to the hometown team. 🏙️", "See What We're Building →"),
    ("Meet the team behind OLI 👋", "Three students. One mission. 👋", "The faces behind One Love Initiative", "{{NAME}}, OLI is run by Prithivi Vijayakumar (Founder), Saket Talap (Director of Operations), and Rishi Ramesh (Marketing). Between classes, they're building something that matters.", "Current push: 20,000 Children's Hygiene Kits for Charlotte families by summer 2025. Ambitious — we like it that way. 💜", "Follow Our Journey →"),
    ("3 ways to make a difference today 🚀", "3 things you can do right now 🚀", "You're here — here's how to go deeper", "{{NAME}}, now that you're subscribed: 1) Follow us on Instagram @one.love.initiative. 2) Share our mission with someone who cares. 3) Sign up to volunteer at an upcoming drive!", "We're driving toward 20,000 hygiene kits for Charlotte kids. Every action helps. 💜", "Get More Involved →"),
    ("The ripple effect starts here 🌊", "One small action creates waves 🌊", "You subscribed — now watch what happens", "{{NAME}}, you subscribed — which seems small. But you'll learn about a drive, tell a friend. They'll volunteer. A kit gets packed. A child smiles. That's a ripple effect.", "OLI is built on that idea. Welcome to the starting point. 20,000 kits and counting. 💜", "Start Your Ripple →"),
    ("Building something historic in Charlotte 🏗️", "Historic. Humble. Here. 🏗️", "You're early to something big", "{{NAME}}, we're in our founding year, already moving toward 20,000 Children's Hygiene Kits. We're building partnerships, hosting drives, and growing a community that cares.", "Looking back years from now, this moment — when OLI was small and scrappy — will feel significant. You're here at the beginning. 💜", "Be Part of History →"),
    ("Why hygiene kits? Our mission explained 💡", "Hygiene = dignity 💡", "The story behind our mission", "{{NAME}}, hygiene gets taken for granted — until it can't be. For families in hardship, a toothbrush or soap might simply be missing. That gap is where OLI steps in.", "Our partner Crisis Assistance Ministry connects us to those families. Goal: 20,000 kits. Your support makes it possible. 💜", "Learn More →"),
    ("You're officially OLI family now 🎊", "You're family now — welcome! 🎊", "The door is open and the energy is contagious", "{{NAME}}, this community is built on warmth. We celebrate every volunteer, every share, every dollar donated — and every subscriber too. So: welcome, officially!", "20,000 hygiene kits for Charlotte kids this summer. The energy is incredible. You're going to love being part of this. 💜", "Dive Right In →"),
    ("A warm hello from our team 🤗", "Hi from the OLI team 🤗", "One Love Initiative says hello", "{{NAME}}, hi! We're OLI — a nonprofit started by Charlotte students who wanted to turn good intentions into real action. We pack hygiene kits and get them to families in hardship.", "Our kit drive is live, targeting 20,000 kits by summer 2025. You'll hear from us with updates and ways to get involved. Glad you're here. 💜", "Explore Our Mission →"),
    ("The kit drive needs you 📅", "Charlotte's kids are counting on us 📅", "The moment to get involved is now", "{{NAME}}, thousands of Charlotte children lack access to basic hygiene. OLI's response: 20,000 hygiene kits assembled by student volunteers and delivered through Crisis Assistance Ministry.", "Every subscriber is a voice for this mission. Every volunteer is a pair of hands. You're already playing your part. 💜", "Join the Drive →"),
    ("Something special is happening here 💜", "Something is building in Charlotte 💜", "You showed up at exactly the right time", "{{NAME}}, something is building — a community, a movement, a belief that young people can change the world. You showed up right in the middle of it.", "Children's Hygiene Kit Drive. 20,000 kits. Crisis Assistance Ministry. And a community that now includes you. 💜", "Feel the Energy →"),
    ("The question that started everything 🤔", "It started with a question 🤔", "Why OLI exists — in one moment", "{{NAME}}, Prithivi asked a simple question: what can a student actually do right now to help? The answer he built is One Love Initiative — and it grows every day.", "His answer this summer: 20,000 Children's Hygiene Kits for Charlotte families through Crisis Assistance Ministry. Welcome to the ongoing answer. 💜", "Read Our Story →"),
    ("What 'One Love' really means to us 💜", "One Love — here's what that means 💜", "The name and the mission behind it", "{{NAME}}, 'One Love' isn't just a phrase. It's a commitment — to every family in Charlotte, to every child without basic hygiene, to the idea that we're all one community.", "One OLI Kit at a time, we're living that commitment. 20,000 kits by summer 2025. Welcome to the family. 💜", "See Our Mission →"),
    ("No fancy offices. Just love. 🏠", "No fancy offices. Just love. 🏠", "Grassroots from the ground up", "{{NAME}}, we don't have a big office or corporate sponsor. We have folding tables, student volunteers, and a deep belief that ordinary people can do extraordinary things.", "That belief is currently packing 20,000 hygiene kits for Charlotte families through Crisis Assistance Ministry. Welcome to the grassroots side of giving. 💜", "See How We Work →"),
    ("Imagine 20,000 kids smiling 😊", "Imagine 20,000 kids smiling 😊", "Close your eyes for a second...", "{{NAME}}, imagine 20,000 children in Charlotte, each holding a kit assembled by OLI volunteers — toothbrush, toothpaste, soap, lotion — all their own. That's what we're building.", "Through Crisis Assistance Ministry, those kits reach kids who genuinely need them. You subscribed today. You're part of building that image. 💜", "Help Make It Real →"),
    ("Your email = real impact for Charlotte families 📧", "Your email = real impact 📧", "Just by subscribing, you matter", "{{NAME}}, it sounds small — subscribing to a newsletter. But it tells us there's one more person who cares. One more voice. One more potential volunteer or donor or connector.", "Those things compound. OLI grew because of exactly this. Welcome — and thank you for caring. 💜", "Explore Our Impact →"),
    ("Before anything else — thank you 🙏", "Before anything else: thank you 🙏", "Your support means more than you know", "{{NAME}}, before we tell you about the drive or the kits — we just want to say thank you. Thank you for finding us. Thank you for subscribing. Thank you for caring.", "OLI is powered by people exactly like you. Let's make 20,000 kits happen together. 💜", "See What You're Supporting →"),
    ("Good things coming to your inbox 📬", "Good things are on the way 📬", "Your inbox just got a purpose upgrade", "{{NAME}}, we don't send fluff. Every OLI email is a real update from real students doing real work. Drive recaps, volunteer stories, milestone celebrations, behind-the-scenes moments.", "We're aiming for 20,000 hygiene kits this summer. That journey lands right here in your inbox. 💜", "See What's Coming →"),
    ("The most passionate team in Charlotte says hi 💜", "The most passionate team in Charlotte 💜", "Meet the people behind the mission", "{{NAME}}, we might be biased, but we truly believe OLI has the most passionate team in Charlotte. Three students — Prithivi, Saket, and Rishi — building something that matters.", "Currently racing toward 20,000 hygiene kits for Charlotte families. We're glad you met us. 💜", "Follow Our Journey →"),
    ("We pack love into cardboard boxes 📦", "Love in a cardboard box 📦", "That's basically what we do", "{{NAME}}, OLI in one sentence: we pack love into cardboard boxes and deliver them to families who need it. The boxes hold hygiene kits. The love is real.", "20,000 of those boxes. Charlotte families. Crisis Assistance Ministry. You. That's our mission. Welcome. 💜", "See Our Kits →"),
    ("Summer 2025 just got better 🌞", "Summer 2025 just got a purpose 🌞", "The season of change is here", "{{NAME}}, summer 2025 is already looking different in Charlotte — because OLI is here. 20,000 hygiene kits for kids before the season ends. You're part of it now.", "Drive dates, volunteer opportunities, and progress updates are all coming to your inbox. This summer is going to be something. 🌞", "Join the Summer Drive →"),
    ("OLI is a movement — step in 🔥", "Step into the movement 🔥", "This is more than a nonprofit", "{{NAME}}, OLI started as one student's idea and grew into a real movement — with drives, partnerships, volunteers, and families being helped. That's a movement.", "We're heading toward 20,000 hygiene kits this summer. You just stepped in. Now step forward. 🔥", "Get Involved →"),
    ("Grassroots, student-led, 100% heart 💜", "Grassroots. Student-led. All heart. 💜", "No polish. No pretense. Just purpose.", "{{NAME}}, we're not polished or professional. We're students who care deeply, work hard, and always act with the right intention. We think that's a good thing.", "That authenticity is driving us toward 20,000 hygiene kits through Crisis Assistance Ministry. Welcome to the real thing. 💜", "See Our Work →"),
    ("What to expect from OLI 📬", "Here's what's coming your way 📬", "Your new inbox experience, explained", "{{NAME}}, here's what you'll get: monthly drive recaps, volunteer calls, milestone updates, behind-the-scenes moments, and occasional heartwarming impact stories.", "We keep it real, concise, and focused: 20,000 Children's Hygiene Kits for Charlotte by end of summer. 💜", "See Our Latest Update →"),
    ("Your subscription means the world ❤️", "You have no idea how much this means 💜", "We don't take subscribers for granted", "{{NAME}}, every time someone new subscribes to OLI, we genuinely celebrate — not because of the number, but because it means one more person is paying attention.", "What we're doing: driving toward 20,000 hygiene kits for Charlotte kids through Crisis Assistance Ministry. Thank you. Really. 💜", "See What You Joined →"),
    ("Charlotte families are counting on all of us 👨‍👩‍👧‍👦", "Charlotte families are counting on us 👨‍👩‍👧‍👦", "They don't know your name. But they need you.", "{{NAME}}, somewhere in Charlotte, there's a family counting on us anyway — on volunteers, donors, and subscribers like you to show up for the mission.", "Goal: 20,000 hygiene kits delivered through Crisis Assistance Ministry before summer ends. Let's not let them down. 💜", "Join the Mission →"),
    ("The kit that changes a day 🎁", "One kit can change a day 🎁", "The power of something small", "{{NAME}}, it's easy to underestimate a hygiene kit. Until you imagine a child's morning without basic supplies — and then imagine it with them. That difference is what OLI creates.", "20,000 times over this summer. Through Crisis Assistance Ministry. Through people like you. Welcome. 💜", "See Our Impact →"),
    ("Welcome to OLI — it's personal 💜", "This is personal 💜", "For us, this isn't just a mission statement", "{{NAME}}, we know families in Charlotte are struggling. We know a hygiene kit is one small thing we can do. And we do it — 20,000 times this summer through Crisis Assistance Ministry.", "With people like you. Welcome — it's genuinely personal. 💜", "Learn Our Why →"),
    ("Real students. Real mission. Real impact. ✊", "Real students. Real mission. Real impact. ✊", "No fluff. Just the truth about what we do.", "{{NAME}}, here's the truth: we're students with limited resources trying to make something significant happen. 20,000 hygiene kits. Charlotte families. This summer.", "We have heart, partners at Crisis Assistance Ministry, and now — you. ✊", "See Our Progress →"),
    ("We're glad you're here — really 😊", "We're really glad you're here 😊", "This isn't a canned welcome email", "{{NAME}}, we know you get a lot of welcome emails. This one's different — we're not faceless. We're three students who genuinely care that you showed up.", "OLI is moving toward 20,000 hygiene kits for Charlotte kids. Your presence pushes us forward. Thank you. 💜", "Explore What We Do →"),
    ("OLI 101: everything in one email 📚", "OLI 101 📚", "Your comprehensive intro to One Love Initiative", "{{NAME}}, here's everything: OLI = student-led nonprofit = Charlotte, NC = hygiene kits for families = current drive = Children's Hygiene Kits = goal = 20,000 kits by summer 2025.", "Distribution: Crisis Assistance Ministry. Donate: Stripe. Volunteer: us. Follow: @one.love.initiative. You're briefed. Welcome. 💜", "Go Deeper →"),
    ("Behind every kit is a story 📖", "Behind every kit is a story 📖", "The human side of what we do", "{{NAME}}, when we pack a kit, we think about who opens it — a kid getting ready for school, a parent stretched too thin, a family navigating hardship with grace.", "That's the story behind every OLI Kit. 20,000 stories this summer through Crisis Assistance Ministry. You're now part of writing them. 💜", "Read Our Story →"),
    ("The math of giving 🔢", "The math of giving 🔢", "Let's crunch some numbers", "{{NAME}}, here's the math: 1 kit × 4 items × 20,000 kits = 80,000 hygiene items for Charlotte kids. Each assembled by a student volunteer. Each one representing a family helped.", "Your subscription = 1 more voice for this mission. 1 more ripple. The math works. 🔢", "See Our Numbers →"),
    ("Not a big org. Not a small dream. 💜", "Not a big org. Not a small dream. 💜", "Just the right size to make something real", "{{NAME}}, we're not a national charity with millions in funding. We're a student-led nonprofit with a big goal: 20,000 hygiene kits for Charlotte families by end of summer 2025.", "Small team. Huge mission. Growing community. You're part of that now. Welcome. 💜", "See What We're Building →"),
    ("Your inbox just joined the OLI family ✉️", "Your inbox just joined the family ✉️", "Expect good things from this address", "{{NAME}}, from oneloveinitiative.official@gmail.com to your inbox: welcome. We only send things that matter — drive updates, impact stories, volunteer calls, real news from our team.", "Mid-Children's Hygiene Kit Drive. Goal: 20,000 kits. Your inbox is now a window into that mission. 💜", "See Our Drive →"),
    ("Here's how we make impact together 🤝", "Here's how we do it together 🤝", "Our model for making change — and your role in it", "{{NAME}}, OLI's model is simple: students pack kits, Crisis Assistance Ministry distributes, Charlotte families are helped. It only works with community support — like yours.", "You're subscribed. That's step one. Volunteer, donate, share — those are next. 20,000 kits. This summer. 🤝", "Go Deeper →"),
    ("We started with nothing but a vision 💫", "Nothing but a vision — and look at us now 💫", "Our origin story in two paragraphs", "{{NAME}}, OLI started with zero budget, zero connections, and one student's belief that Charlotte deserved better. That student is Prithivi Vijayakumar — and this is what he built.", "We're now moving toward 20,000 hygiene kits through Crisis Assistance Ministry, with a growing community that includes you. 💫", "See Our Journey →"),
    ("A quick intro from the OLI team 👋", "Quick intro from the OLI team 👋", "We'll keep this short — we know you're busy", "{{NAME}}, quick version: OLI is a student nonprofit in Charlotte. We pack hygiene kits for families. Goal: 20,000 kits by summer. You just subscribed. We're thrilled.", "Longer version: our website. Even longer: come volunteer. Thank you for subscribing. 💜", "Visit Our Website →"),
    ("This is just the beginning 🌱", "This is just the beginning 🌱", "We're in the early chapters of something big", "{{NAME}}, OLI was founded in 2025. First year. Children's Hygiene Kit Drive is our first major push. You're subscribing in the early days of all of it.", "Being early to something is underrated. You'll watch this grow. 20,000 kits. You're in at chapter one. 🌱", "Be Part of the Story →"),
    ("Small nonprofit. Huge heart. 💜", "Small nonprofit. Huge heart. 💜", "Size doesn't determine impact", "{{NAME}}, we're small — and intentional. Every kit we pack, every family we reach, every drive we host is done with full attention and full heart. That's what small makes possible.", "Goal: 20,000 kits. Fuel: love and determination. You: very welcome. 💜", "See Our Mission →"),
    ("The OLI story begins with you 📖", "The OLI story includes you now 📖", "You're a character in this narrative", "{{NAME}}, One Love Initiative is writing a story about what young people can do when they decide to act. Every volunteer, donor, and supporter is a character in that story.", "You just joined the cast. 20,000 hygiene kits for Charlotte kids — your chapter starts now. 💜", "Read the Story →"),
    ("Your dose of good news starts now 📬", "Your dose of good news 📬", "We're here for the wins", "{{NAME}}, the world is full of heavy news. OLI is here for a different story — students who decided to act, communities that showed up, and kits that reached families who needed them.", "20,000 of those stories this summer. You'll hear about every milestone right here in your inbox. 💜", "See What's Happening →"),
    ("Hygiene = dignity — do you agree? 💜", "Hygiene = dignity 💜", "The belief that drives everything we do", "{{NAME}}, at the core of everything OLI does is a simple belief: access to hygiene is part of human dignity. It's not a luxury. When it's out of reach, we close the gap.", "20,000 Children's Hygiene Kits for Charlotte families this summer through Crisis Assistance Ministry. That belief in action. Welcome. 💜", "Join the Belief →"),
    ("What drives us, and why you get it 💡", "What drives us 💡", "The motivation behind One Love Initiative", "{{NAME}}, what drives OLI? The knowledge that thousands of Charlotte families face hardship — and that we, as students, can do something about it. That knowledge is uncomfortable to ignore.", "So we built a kit drive. Set a goal of 20,000. Found Crisis Assistance Ministry as our partner. And now we have a community that includes you. 💜", "See Our Why →"),
    ("The kit drive is more than kits 💭", "More than kits 💭", "What we're really building", "{{NAME}}, yes, we pack kits. But we're really building a community of students and supporters who believe in taking action. The kits are the medium. The message is: someone cares.", "20,000 kits. 20,000 messages to Charlotte families. Through Crisis Assistance Ministry. Welcome to the message-makers. 💜", "Explore Our Mission →"),
    ("OLI in 60 seconds 🎓", "OLI in 60 seconds 🎓", "The fastest orientation you'll get", "{{NAME}}, ready? OLI = student nonprofit. Charlotte, NC. Founded 2025. Drive: Children's Hygiene Kits. Contents: toothbrush, toothpaste, soap, lotion. Goal: 20,000 kits. Partner: Crisis Assistance Ministry.", "That's it. More details at our website — or come volunteer and see it firsthand. 💜", "Go See It →"),
    ("We see you as a partner, not a subscriber 🤝", "You're a partner, not just a subscriber 🤝", "How we think about the people who support us", "{{NAME}}, we could call you a subscriber. But we prefer partner — someone who chose to pay attention to what we're doing and give us a little bit of their time.", "That partnership is what OLI is built on. 20,000 hygiene kits. Charlotte families. Crisis Assistance Ministry. Partners like you. Welcome. 🤝", "Join as a Partner →"),
    ("Where OLI started and where it's going 🗺️", "Where we started and where we're headed 🗺️", "A brief history and a big future", "{{NAME}}, OLI started in 2025 with one student's idea and zero resources. Today we have a team, a plan, a goal of 20,000 kits, a distribution partner, and a growing community.", "Where we're going: bigger drives, more partnerships, more kits, more families helped. You're coming with us. 🗺️", "Follow the Journey →"),
    ("The honest truth about our nonprofit 💜", "The honest truth about OLI 💜", "No spin. No PR. Just the real story.", "{{NAME}}, here's the honest truth: we're students figuring it out as we go. We make mistakes. We learn fast. We care deeply. And we're building something real for Charlotte families.", "20,000 hygiene kits by summer. Crisis Assistance Ministry as our partner. An imperfect, passionate team. And now — you. Welcome to the honest version of OLI. 💜", "See Who We Really Are →"),
    ("You found us — we're so glad 🙌", "You found us 🙌", "The best discoveries are the ones you didn't plan", "{{NAME}}, however you found One Love Initiative — Google, Instagram, a friend, luck — we're so glad you landed here. OLI is one of those things that's better experienced than described.", "We're driving toward 20,000 hygiene kits for Charlotte families through Crisis Assistance Ministry. Stick around. You found something good. 💜", "Stay and Explore →"),
    ("Charlotte's kids deserve more — we agree 👧👦", "Charlotte's kids deserve more 👧👦", "That's why we're here", "{{NAME}}, Charlotte's children deserve access to basic hygiene. Full stop. When that access is lacking — due to hardship, circumstance, or resources — OLI is here to close the gap.", "20,000 hygiene kits. End of summer. Crisis Assistance Ministry. Your support. Together we make sure more of Charlotte's kids have what they deserve. 💜", "Support the Kids →"),
    ("Something magical is happening 🎯", "Something magical is happening in Charlotte 🎯", "You showed up at exactly the right moment", "{{NAME}}, it's hard to put into words, but something genuinely special is building at OLI. The energy, the community, the mission, the progress toward 20,000 kits — it just feels right.", "And you're here now, which makes it better. Welcome to the magic. 💜", "Be Part of It →"),
    ("From a folding table to your inbox 😄", "From a folding table to your inbox 😄", "Our humble, honest, real origin", "{{NAME}}, every OLI kit drive starts with a folding table, some student volunteers, and a very long to-do list. That's the reality. But the impact? That's as real as it gets.", "20,000 kids' hygiene kits for Charlotte families this summer, through Crisis Assistance Ministry, starting from that folding table. Welcome to the humble origin story. 💜", "See Our Process →"),
    ("Be part of the summer that changes Charlotte 🌞", "This summer changes things 🌞", "Make this your summer of purpose", "{{NAME}}, every summer has a story. This one is about 20,000 hygiene kits, student volunteers, Charlotte families, and a community that decided to act. Be part of that story.", "OLI is driving the mission. Crisis Assistance Ministry is the bridge. You're the community that makes it real. 🌞", "Join This Summer →"),
    ("Students + community + love = OLI 💜", "Students + community + love 💜", "The simple formula behind One Love Initiative", "{{NAME}}, here's our formula: take students who care, add a community that shows up, multiply by genuine love for this city — and you get One Love Initiative.", "Currently: 20,000 hygiene kits for Charlotte families through Crisis Assistance Ministry. You just joined the formula. 💜", "See the Result →"),
    ("Our mission is bold — it needs you 💪", "Bold mission. It needs you. 💪", "No bold mission was ever achieved alone", "{{NAME}}, 20,000 hygiene kits by end of summer 2025. Ambitious. But we can't get there alone — we need subscribers, volunteers, donors, and advocates.", "That's you. You're one of those people now. Thank you for being bold with us. 💪", "Join the Bold Work →"),
    ("Every kit tells a story 📖", "Every kit tells a story 📖", "We think about the recipient every time", "{{NAME}}, when our volunteers pack a kit, they think about who's receiving it. A child. A family. A moment of care in the middle of hardship. Every kit carries that intention.", "20,000 of those moments this summer. Through Crisis Assistance Ministry. Through people like you. Welcome. 💜", "Pack a Kit With Us →"),
    ("Welcome — we've been hoping you'd find us 💜", "We've been hoping you'd find us 💜", "You're exactly who we needed today", "{{NAME}}, we think about the people who haven't found OLI yet. Who are they? What would they do if they knew? You found us — and we're so glad.", "We're driving toward 20,000 hygiene kits for Charlotte families. With you in the community, that goal feels more reachable. 💜", "Explore What You Found →"),
    ("The community behind the cause 🤝", "The community behind the cause 🤝", "It takes a lot of people to make this happen", "{{NAME}}, OLI doesn't exist in a vacuum. Behind every kit is a student volunteer. Behind every drive is a community that showed up. Behind every delivery is Crisis Assistance Ministry.", "And now — behind this email — is you. A new member of the community that makes it all possible. Welcome. 🤝", "Meet the Community →"),
    ("How one email can start something real 📧", "One email. One ripple. 📧", "The downstream impact of small actions", "{{NAME}}, you signed up for OLI's newsletter. That's an email address. A small decision. But it leads somewhere — to learning about a drive, to volunteering, to changing a child's week.", "Small actions compound. That's how we get to 20,000 kits. Welcome to the compound effect. 💜", "See Where This Goes →"),
    ("OLI believes in people — starting with you 💜", "OLI believes in people 💜", "The human-centered philosophy behind our work", "{{NAME}}, at its core, OLI is about believing in people — that students can lead, communities can mobilize, families deserve dignity, and that you will show up.", "You subscribed. You showed up. 20,000 hygiene kits. Charlotte. This summer. And you. Welcome to belief-in-action. 💜", "See Our Impact →"),
    ("Welcome from One Love Initiative 🎉", "Welcome from One Love 🎉", "One Love Initiative is glad you're here", "{{NAME}}, welcome! From our small, passionate, student-run team in Charlotte to your inbox — we're genuinely glad you're here. OLI is on a mission and every person in this community helps.", "Current mission: 20,000 Children's Hygiene Kits for Charlotte families by summer 2025. Your inbox just became part of that push. 💜", "Join the Push →"),
    ("What's happening in Charlotte this summer? OLI. 🏙️", "What's happening in Charlotte this summer? OLI. 🏙️", "The answer is us — and it's a good one", "{{NAME}}, while some people are planning beach trips, OLI is planning something different: 20,000 hygiene kit assemblies, multiple drives, and real impact for Charlotte families.", "We don't want you to miss it. That's why you're getting this email. Welcome — summer 2025 is going to be a moment. 🏙️", "Be Part of the Moment →"),
    ("Chapter one starts now 📚", "Chapter one 📚", "The OLI story is being written right now", "{{NAME}}, OLI was founded in 2025, launched our first drive, and set a goal of 20,000 kits. That's chapter one. Chapter two involves more volunteers, more kits, more families helped.", "You subscribed at the start of chapter two. You'll see how this unfolds. We're so glad to have you along. 📚", "Read Chapter One →"),
    ("The power of one 🔋", "The power of one 🔋", "Why every single person matters", "{{NAME}}, OLI believes in the power of one. One subscriber. One volunteer. One kit. One family helped. These ones add up — to 20,000 kits, hundreds of volunteers, thousands of families.", "You are one. And one is exactly what we need. Thank you for being here. 💜", "See the Sum of Ones →"),
    ("Something real starts here 💜", "Something real starts here 💜", "Welcome — and brace yourself for good things", "{{NAME}}, this welcome email isn't a formality. It's the start of a real relationship — updates that matter, stories that move you, and ways to make actual impact in Charlotte.", "20,000 hygiene kits. Charlotte. Summer 2025. You and us. Let's go. 💜", "Let's Go →"),
    ("Simple kits. Huge impact. 💡", "Simple kits. Huge impact. 💡", "Why what we do matters more than it sounds", "{{NAME}}, 'hygiene kit' sounds modest. But give one to a child who doesn't have basic supplies and watch what happens — confidence for school, dignity for a family, relief for a parent.", "We're putting that impact in 20,000 hands this summer through Crisis Assistance Ministry. Welcome to something that sounds simple but means everything. 💜", "Learn About the Impact →"),
    ("You care about people — that's why you're here 💜", "You care about people 💜", "We can tell — and we appreciate it", "{{NAME}}, we know something about you: you care. Not everyone subscribes to a student nonprofit newsletter. The people who do are the ones who believe communities can get better.", "OLI is for people like that. 20,000 hygiene kits. Charlotte families. This summer. Welcome to the believers. 💜", "See Our Work →"),
    ("Young people building something — come watch 👀", "Young people building something real 👀", "Front-row seat to something that matters", "{{NAME}}, there's something inspiring about watching young people decide to act. OLI is that — students in Charlotte who didn't wait to graduate before making a difference.", "We're driving toward 20,000 kits this summer, building as we go. You've got a front-row seat now. Welcome to the audience — and the team. 💜", "Watch and Participate →"),
    ("OLI greets you with open arms 🤗", "Open arms, open mission 🤗", "Welcome — the more the merrier", "{{NAME}}, OLI has room for everyone. Volunteers, donors, advocates, followers, subscribers — all of it helps. We greet all of it with genuine gratitude and open arms.", "20,000 hygiene kits. Charlotte. Summer. You. Welcome to the open arms of One Love Initiative. 💜", "Come Right In →"),
    ("An honest welcome from three students 💜", "An honest welcome from three students 💜", "No PR polish. Just Prithivi, Saket, and Rishi.", "{{NAME}}, hi — we're Prithivi, Saket, and Rishi. We run OLI out of Charlotte, between classes and everything else. We pack kits, coordinate with Crisis Assistance Ministry, and grow this community.", "You just made that community a little bigger. We don't take that lightly. Genuinely — thank you. 💜", "Get to Know Us →"),
    ("The drive is live. The goal is set. 🎯", "The drive is live. The goal is set. 🎯", "And now you're in position to help", "{{NAME}}, OLI's Children's Hygiene Kit Drive is active right now. Goal: 20,000 kits by end of summer 2025. Student volunteers. Crisis Assistance Ministry. Community support.", "You subscribed at the right moment. There are ways to get involved — we'd love to tell you all about them. 🎯", "Get Involved Now →"),
    ("From Charlotte's living rooms to your inbox 🏠", "From Charlotte with love 🏠", "Humble beginnings, growing fast", "{{NAME}}, OLI started in Charlotte — probably at a kitchen table — with a student's idea and a conviction that something had to be done. It grew from there. Now it's in your inbox.", "We're heading toward 20,000 kits through Crisis Assistance Ministry, and every email we send makes the community bigger. Welcome to it. 💜", "Visit Our Home Page →"),
    ("We make kits. We change days. Welcome. 💜", "We make kits. We change days. 💜", "That's the short version of everything we do", "{{NAME}}, OLI's work is simple to describe: assemble hygiene kits, get them to families who need them through Crisis Assistance Ministry. But the impact? Anything but simple.", "One kit can change a child's morning, a parent's mood, a family's week. 20,000 kits this summer. Welcome to day-changing work. 💜", "See Our Kits →"),
    ("5 things to know about One Love Initiative 📌", "5 things about OLI 📌", "Your essential cheat sheet", "{{NAME}}, the five things you should know: 1) Student-led nonprofit in Charlotte. 2) Founded 2025. 3) Current drive: Children's Hygiene Kits. 4) Goal: 20,000 kits. 5) Partner: Crisis Assistance Ministry.", "Now you know the essentials. Everything else — the stories, the drives, the impact — comes to your inbox. 💜", "Dig Deeper →"),
    ("If love were a nonprofit — it's OLI 💜", "If love were a nonprofit 💜", "The philosophy behind the name", "{{NAME}}, the name 'One Love Initiative' isn't just branding. It's a genuine philosophy: that love is the reason to act, the method of action, and the outcome we're working toward.", "20,000 kits. Charlotte. Summer. Love in every box. Welcome to the movement built on love. 💜", "See Love in Action →"),
    ("We can't wait to share this journey 🚀", "The journey is just getting started 🚀", "And we're glad you're along for it", "{{NAME}}, OLI is in its first year and moving fast. 20,000 hygiene kits. Multiple drives. Growing partnerships. A community expanding every day. The journey has just started.", "You subscribed at a remarkable moment. We can't wait to share every milestone with you. 🚀", "Follow the Journey →"),
    ("Humble roots. Big mission. Warm welcome. 💜", "Humble roots. Big mission. 💜", "The real story of One Love Initiative", "{{NAME}}, we started humble. We're still humble. But our mission isn't — 20,000 hygiene kits for Charlotte's kids through Crisis Assistance Ministry by end of summer 2025. That's big.", "Humble team. Big dream. Growing fast. Welcome to all of it. 💜", "See Our Mission →"),
    ("Where students meet community need 💡", "Where students meet community need 💡", "OLI is the bridge between those two things", "{{NAME}}, there's a gap between the energy students have and the needs communities face. OLI was built to close that gap — channeling student power into real, tangible help.", "Right now, that channel is carrying 20,000 hygiene kits toward Charlotte families. Welcome to the bridge. 💜", "See How the Bridge Works →"),
    ("You joined — and that's already making a difference 🌱", "You're already making a difference 🌱", "Your presence counts — literally", "{{NAME}}, we track our community growth because it drives us. More subscribers = more potential volunteers, donors, advocates, and connectors. You joining today literally matters.", "We're heading toward 20,000 hygiene kits through Crisis Assistance Ministry. You just moved the needle. 🌱", "See Your Impact →"),
    ("Together we're building something that lasts 🏗️", "Building something that lasts 🏗️", "This is a long-term movement", "{{NAME}}, OLI isn't just one drive. We're building an organization — with infrastructure, partnerships, and community — that will serve Charlotte for years. This summer is just the beginning.", "20,000 kits. Crisis Assistance Ministry. A foundation for the future. You're part of building it. 🏗️", "Help Build It →"),
    ("Our family just got bigger 💜", "Our family just got bigger 💜", "Welcome — you're family now", "{{NAME}}, the OLI family is defined by shared values: belief in community, commitment to action, love for Charlotte, and a drive to help families in hardship. You share those values.", "Our family is working toward 20,000 hygiene kits this summer. Welcome to the warmest nonprofit family in Charlotte. 💜", "Join Family Events →"),
    ("What subscribing to OLI really means 📬", "What subscribing to OLI really means 📬", "More than an email address", "{{NAME}}, subscribing to OLI means being in the loop on a real mission. Drive updates, impact stories, volunteer opportunities, and the occasional heartfelt letter from our team.", "We're working toward 20,000 hygiene kits for Charlotte families. Your inbox is now a window into that work. 📬", "See What's in Your Inbox →"),
    ("Good humans find good causes — here you are 💜", "Good humans find good causes 💜", "And that's exactly what happened here", "{{NAME}}, we believe the people who subscribe to a student nonprofit's newsletter are genuinely good humans. They care. They act. They show up. That's you — and we're grateful.", "OLI needs good humans. 20,000 kits by summer. Charlotte. Crisis Assistance Ministry. Good humans making it happen. Welcome. 💜", "Be a Good Human With Us →"),
    ("This summer, Charlotte will remember 🌞", "Charlotte will remember this summer 🌞", "Something historic is happening right now", "{{NAME}}, this summer, OLI is setting a standard for what a student nonprofit can do. 20,000 hygiene kits. Charlotte families. Real impact.", "Years from now, when OLI is a household name in Charlotte, you'll remember subscribing at the start. 🌞", "Be Part of History →"),
    ("One hello. One amazing journey. 💜", "One hello. One amazing journey. 💜", "That's what this email is — and what comes next", "{{NAME}}, this email is a hello. But it's also the start of something — updates from Charlotte's most passionate student nonprofit. A front-row seat to 20,000 kits being packed and delivered.", "One email. One hello. One journey. Welcome to all of it. 💜", "Start the Journey →"),
    ("Student heart. Real mission. Welcome! 🎓", "Student heart. Real mission. 🎓", "What being student-led actually means for OLI", "{{NAME}}, student-led means full hearts, fresh eyes, and unlimited energy. It also means we're learning as we go — and we think that authenticity shows in everything we do.", "Current learning experience: delivering 20,000 hygiene kits to Charlotte families by summer's end. Come learn with us. 🎓", "Learn Along With Us →"),
    ("The drive, the mission, and you 🤝", "The drive, the mission, and you 🤝", "How you fit into the bigger picture", "{{NAME}}, the Children's Hygiene Kit Drive is live. The mission is 20,000 kits by summer 2025. Crisis Assistance Ministry is our distribution partner. And you? You're the community that makes it possible.", "Three pieces. One mission. Welcome to yours. 🤝", "See the Full Picture →"),
    ("Welcome, friend — the OLI community needs you 💜", "Welcome, friend 💜", "This is a community that genuinely needs you", "{{NAME}}, we don't say 'needs you' lightly. OLI grows when people care enough to subscribe, share, volunteer, and donate. Every person in this community matters.", "We're heading toward 20,000 hygiene kits through Crisis Assistance Ministry. You matter to that goal. Welcome, friend. 💜", "See How You Help →"),
    ("Welcome email done — now let's get to work 🎊", "Last formality over — let's get to work 🎊", "Welcome delivered. Mission awaiting.", "{{NAME}}, okay — welcome officially sent! Now for the good stuff: you're part of a community driving 20,000 hygiene kits to Charlotte families through Crisis Assistance Ministry this summer.", "No more formalities. You're in the family. Let's make an impact together. 🎊", "Jump Right In →"),
]

out = [{"id": f"welcome-{i+1:03d}", "subject": t[0], "body": mkb(t[1], t[2], t[3], t[4], t[5])} for i, t in enumerate(T)]
path = os.path.join(os.path.dirname(__file__), "welcome.json")
with open(path, "w", encoding="utf-8") as f:
    json.dump(out, f, indent=2, ensure_ascii=False)
print(f"Wrote {len(out)} welcome templates to {path}")
