import json, os

H = "<div style='font-family:Montserrat,Arial,sans-serif;max-width:600px;margin:0 auto;background:#f5f5f0;'><div style='background:linear-gradient(135deg,#7B5CF5,#9B7FF5);padding:28px 36px;text-align:center;'><img src='https://raw.githubusercontent.com/privi-doughnut/oneloveinitiative/main/OLI_LOGO.jpg' alt='OLI' style='width:64px;height:64px;border-radius:50%;object-fit:cover;border:3px solid rgba(255,255,255,0.3);'/><h1 style='color:#fff;font-size:18px;font-weight:800;margin:8px 0 0;letter-spacing:0.07em;'>ONE LOVE INITIATIVE</h1><p style='color:rgba(255,255,255,0.8);font-size:10px;margin:3px 0 0;letter-spacing:0.14em;text-transform:uppercase;'>Charlotte, NC &middot; Student-Led Nonprofit</p></div>"
F = "<div style='padding:16px 24px;background:#f5f5f0;text-align:center;border-top:1px solid #eee;'><p style='font-size:11px;color:#aaa;margin:0;'>2025 OLI &middot; <a href='https://oneloveinitative.org' style='color:#7B5CF5;text-decoration:none;'>Website</a> &middot; <a href='https://www.instagram.com/one.love.initiative/' style='color:#7B5CF5;text-decoration:none;'>Instagram</a> &middot; <a href='{{UNSUBSCRIBE_URL}}' style='color:#aaa;text-decoration:none;'>Unsubscribe</a></p></div></div>"

RESULTS = ("<div style='background:linear-gradient(135deg,#7B5CF5,#9B7FF5);border-radius:8px;padding:20px;margin:20px 0;'>"
    "<p style='color:rgba(255,255,255,0.8);font-size:10px;letter-spacing:0.15em;text-transform:uppercase;margin:0 0 10px;font-weight:600;text-align:center;'>Drive Results</p>"
    "<div style='display:flex;gap:10px;'>"
    "<div style='flex:1;background:rgba(255,255,255,0.15);border-radius:6px;padding:12px;text-align:center;'>"
    "<p style='color:#fff;font-size:22px;font-weight:800;margin:0 0 2px;'>{{KITS_COLLECTED}}</p>"
    "<p style='color:rgba(255,255,255,0.8);font-size:9px;margin:0;letter-spacing:0.1em;text-transform:uppercase;'>Kits Packed</p>"
    "</div>"
    "<div style='flex:1;background:rgba(255,255,255,0.15);border-radius:6px;padding:12px;text-align:center;'>"
    "<p style='color:#fff;font-size:22px;font-weight:800;margin:0 0 2px;'>{{VOLUNTEER_COUNT}}</p>"
    "<p style='color:rgba(255,255,255,0.8);font-size:9px;margin:0;letter-spacing:0.1em;text-transform:uppercase;'>Volunteers</p>"
    "</div>"
    "<div style='flex:1;background:rgba(255,255,255,0.15);border-radius:6px;padding:12px;text-align:center;'>"
    "<p style='color:#fff;font-size:22px;font-weight:800;margin:0 0 2px;'>{{DRIVE_LOCATION}}</p>"
    "<p style='color:rgba(255,255,255,0.8);font-size:9px;margin:0;letter-spacing:0.1em;text-transform:uppercase;'>Location</p>"
    "</div>"
    "</div>"
    "</div>")

def mkb(hl, sub, p1, p2, cta="See What's Next →", sg="The OLI Team"):
    return (H +
        "<div style='background:#fff;padding:32px 36px;'>"
        "<p style='color:#7B5CF5;font-size:10px;letter-spacing:0.15em;text-transform:uppercase;margin:0 0 8px;font-weight:600;'>Drive Recap — {{DRIVE_NAME}}</p>"
        "<h2 style='color:#333;font-size:22px;font-weight:800;margin:0 0 5px;line-height:1.3;'>" + hl + "</h2>"
        "<p style='color:#999;font-size:12px;font-style:italic;margin:0 0 18px;'>" + sub + "</p>"
        "<p style='color:#444;font-size:14px;line-height:1.7;margin:0 0 12px;'>" + p1 + "</p>"
        + RESULTS +
        "<p style='color:#444;font-size:14px;line-height:1.7;margin:0 0 24px;'>" + p2 + "</p>"
        "<div style='text-align:center;'><a href='https://oneloveinitative.org' style='background:#7B5CF5;color:#fff;padding:11px 26px;border-radius:5px;font-size:13px;font-weight:700;text-decoration:none;'>" + cta + "</a></div>"
        "<p style='color:#888;font-size:12px;margin:22px 0 0;'>With love, <strong style='color:#7B5CF5;'>" + sg + "</strong></p>"
        "</div>" + F)

# (subject, headline, sub, p1, p2, cta)
T = [
    ("We did it — {{DRIVE_NAME}} recap 🎉", "We did it — {{DRIVE_NAME}} recap! 🎉", "The numbers are in. The impact is real.", "{{NAME}}, {{DRIVE_NAME}} on {{DRIVE_DATE}} is in the books — and it was incredible. The OLI community showed up in force, packed hygiene kits with care, and made real impact for Charlotte families through Crisis Assistance Ministry.", "The mission keeps going — and you're part of why. Thank you. 💜", "See What's Next →"),
    ("{{DRIVE_NAME}} results are in — wow 🌟", "{{DRIVE_NAME}} results are in — and they're stunning 🌟", "Here's what the OLI community accomplished", "{{NAME}}, the {{DRIVE_NAME}} results are official: {{KITS_COLLECTED}} hygiene kits packed by {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}. Those kits are now on their way to Charlotte families through Crisis Assistance Ministry. Stunning.", "What you helped make possible is real. Thank you from the whole OLI team. 💜", "See the Full Impact →"),
    ("Thank you for showing up to {{DRIVE_NAME}} 💜", "Thank you for showing up to {{DRIVE_NAME}} 💜", "Your presence made the difference", "{{NAME}}, thank you for being part of {{DRIVE_NAME}} on {{DRIVE_DATE}}. Whether you volunteered, donated, or spread the word — you contributed to {{KITS_COLLECTED}} hygiene kits reaching Charlotte families through Crisis Assistance Ministry.", "Your presence made the difference. We couldn't do this without this community. 💜", "Stay Involved →"),
    ("{{DRIVE_NAME}}: {{KITS_COLLECTED}} kits. One community. 💜", "{{KITS_COLLECTED}} kits. One community. {{DRIVE_NAME}}. 💜", "The numbers tell a story. So does the feeling.", "{{NAME}}, here's the {{DRIVE_NAME}} story in numbers: {{KITS_COLLECTED}} kits packed, {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, and Charlotte families about to receive hygiene supplies through Crisis Assistance Ministry.", "The numbers tell the story. The feeling of being there told another one. Thank you for being part of both. 💜", "Be Part of the Next One →"),
    ("OLI {{DRIVE_NAME}} — mission accomplished 🎯", "Mission accomplished — {{DRIVE_NAME}} 🎯", "We set out to pack kits. We packed kits.", "{{NAME}}, mission accomplished: OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is complete. {{KITS_COLLECTED}} hygiene kits packed by {{VOLUNTEER_COUNT}} volunteers, now en route to Charlotte families through Crisis Assistance Ministry.", "Mission accomplished. Thank you for being part of the team that made it happen. 🎯", "See the Next Mission →"),
    ("OLI {{DRIVE_NAME}}: here's what you helped create 💜", "Here's what you helped create — {{DRIVE_NAME}} 💜", "Real kits. Real families. Real Charlotte impact.", "{{NAME}}, here's what you helped create through your support of OLI's {{DRIVE_NAME}}: {{KITS_COLLECTED}} children's hygiene kits, packed by {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, distributed to Charlotte families through Crisis Assistance Ministry.", "You helped create that. Let that land. Thank you. 💜", "Keep Creating →"),
    ("The {{DRIVE_NAME}} recap 🔢", "{{DRIVE_NAME}} recap — the full story 🔢", "Everything that happened, by the numbers and beyond", "{{NAME}}, here's the full {{DRIVE_NAME}} recap: on {{DRIVE_DATE}}, {{VOLUNTEER_COUNT}} volunteers gathered at {{DRIVE_LOCATION}} and packed {{KITS_COLLECTED}} hygiene kits for Charlotte children. Crisis Assistance Ministry will distribute them.", "The recap is good. The mission continues. Thank you for making this one count. 💜", "Continue the Mission →"),
    ("OLI {{DRIVE_NAME}}: Charlotte showed up 💜", "Charlotte showed up — {{DRIVE_NAME}} 💜", "And we couldn't be more grateful", "{{NAME}}, Charlotte showed up for {{DRIVE_NAME}} on {{DRIVE_DATE}} — {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}} proved it. {{KITS_COLLECTED}} hygiene kits are the proof, heading to Charlotte families through Crisis Assistance Ministry.", "This city shows up when it matters. Thank you for being part of that. 💜", "Keep Showing Up →"),
    ("OLI {{DRIVE_NAME}}: the best drive yet 🏆", "The best drive yet — {{DRIVE_NAME}} 🏆", "Every OLI drive has been better than the last", "{{NAME}}, OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} might have been our best yet: {{KITS_COLLECTED}} kits packed at {{DRIVE_LOCATION}} by {{VOLUNTEER_COUNT}} incredible volunteers. Crisis Assistance Ministry is distributing to Charlotte families.", "Best drive yet. Next one will be even better. Thank you for helping us keep raising the bar. 🏆", "Help Raise the Bar →"),
    ("{{KITS_COLLECTED}} kits. Done. — OLI {{DRIVE_NAME}} 💜", "{{KITS_COLLECTED}} kits. Done. — {{DRIVE_NAME}} 💜", "Simple. Powerful. Real.", "{{NAME}}, {{KITS_COLLECTED}} hygiene kits. Done. That's the OLI {{DRIVE_NAME}} summary — packed by {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}} on {{DRIVE_DATE}}, now heading to Charlotte families through Crisis Assistance Ministry.", "Simple. Powerful. Real. Thank you for supporting a team that delivers. 💜", "Support the Next Drive →"),
    ("OLI {{DRIVE_NAME}}: the Charlotte community delivered 💜", "The Charlotte community delivered — {{DRIVE_NAME}} 💜", "{{KITS_COLLECTED}} kits say it better than we ever could", "{{NAME}}, {{KITS_COLLECTED}} kits say it better than we ever could: the Charlotte community delivered at OLI's {{DRIVE_NAME}}. {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}} made it happen, and Crisis Assistance Ministry will get them to families in need.", "Delivered. Thank you for being part of the delivery. 💜", "Deliver Again →"),
    ("OLI {{DRIVE_NAME}}: from {{DRIVE_LOCATION}} with love 💜", "From {{DRIVE_LOCATION}}, with love — {{DRIVE_NAME}} 💜", "Every kit carries the care of the people who packed it", "{{NAME}}, every kit packed at {{DRIVE_NAME}} on {{DRIVE_DATE}} carries the care of the {{VOLUNTEER_COUNT}} volunteers who packed it at {{DRIVE_LOCATION}}. {{KITS_COLLECTED}} kits, all packed with intentional care, heading to Charlotte families through Crisis Assistance Ministry.", "From {{DRIVE_LOCATION}} with love. To Charlotte families with care. Thank you. 💜", "Keep the Love Going →"),
    ("{{DRIVE_NAME}} final count: {{KITS_COLLECTED}} kits 💜", "Final count: {{KITS_COLLECTED}} kits — {{DRIVE_NAME}} 💜", "The official tally is in. The results are outstanding.", "{{NAME}}, the official {{DRIVE_NAME}} final count: {{KITS_COLLECTED}} hygiene kits, packed by {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}} on {{DRIVE_DATE}}. Those kits are now with Crisis Assistance Ministry for distribution to Charlotte families.", "Outstanding. Thank you to every volunteer, donor, and supporter who made that number real. 💜", "Make the Next Count Even Higher →"),
    ("OLI {{DRIVE_NAME}} wrapped — here's the impact 💜", "{{DRIVE_NAME}} wrapped — here's the impact 💜", "When a drive wraps, the real work begins", "{{NAME}}, OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} has wrapped — and now the real work begins: Crisis Assistance Ministry distributing {{KITS_COLLECTED}} hygiene kits to Charlotte families. {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}} made it possible.", "The drive wrapped. The impact is just starting. Thank you for fueling both. 💜", "Stay for the Impact →"),
    ("OLI {{DRIVE_NAME}}: a day to remember 💜", "A day to remember — {{DRIVE_NAME}} 💜", "{{DRIVE_DATE}} will stick with everyone who was there", "{{NAME}}, {{DRIVE_DATE}} at {{DRIVE_LOCATION}} will stick with everyone who was there — the energy of {{VOLUNTEER_COUNT}} volunteers, the sound of {{KITS_COLLECTED}} kits being packed, the knowledge that Charlotte families would receive them through Crisis Assistance Ministry.", "A day to remember. Thank you for being part of making it memorable. 💜", "Create More Memories →"),
    ("OLI {{DRIVE_NAME}}: look what we built together 💜", "Look what we built together — {{DRIVE_NAME}} 💜", "{{KITS_COLLECTED}} kits is what community looks like", "{{NAME}}, {{KITS_COLLECTED}} kits is what community looks like — {{VOLUNTEER_COUNT}} people at {{DRIVE_LOCATION}} on {{DRIVE_DATE}}, working together, building something real for Charlotte families through Crisis Assistance Ministry.", "Look what we built. Look what you were part of. We're so proud of this community. 💜", "Keep Building →"),
    ("OLI {{DRIVE_NAME}} — the numbers speak for themselves 📊", "The numbers speak for themselves — {{DRIVE_NAME}} 📊", "No spin needed. The results are clear.", "{{NAME}}, no spin needed on OLI's {{DRIVE_NAME}} results: {{KITS_COLLECTED}} hygiene kits, {{VOLUNTEER_COUNT}} volunteers, {{DRIVE_LOCATION}}, {{DRIVE_DATE}}. Crisis Assistance Ministry is distributing to Charlotte families. The numbers speak for themselves.", "They speak loudly. Thank you for being part of the story behind them. 💜", "Be Part of the Next Story →"),
    ("OLI {{DRIVE_NAME}}: the kids will have their kits 🧒", "The kids will have their kits — {{DRIVE_NAME}} 🧒", "{{KITS_COLLECTED}} Charlotte children a little better off today", "{{NAME}}, because of {{DRIVE_NAME}} on {{DRIVE_DATE}}, {{KITS_COLLECTED}} Charlotte children will have hygiene kits — toothbrush, toothpaste, soap, lotion — through Crisis Assistance Ministry. {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}} made it happen.", "The kids will have their kits. That's what this is all about. Thank you. 🧒", "Help More Kids →"),
    ("OLI {{DRIVE_NAME}}: proud of every single one of you 💜", "Proud of every single one of you — {{DRIVE_NAME}} 💜", "The OLI team is proud to work with this community", "{{NAME}}, the OLI team is genuinely proud of what happened at {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}}: {{VOLUNTEER_COUNT}} volunteers, {{KITS_COLLECTED}} kits, and a community that showed what it's capable of.", "Those kits reach Charlotte families through Crisis Assistance Ministry. We're proud of every single one of you. 💜", "Make Us Proud Again →"),
    ("OLI {{DRIVE_NAME}}: Prithivi's thank you 💜", "Prithivi's personal thank you — {{DRIVE_NAME}} 💜", "From the OLI founder, with real gratitude", "{{NAME}}, I'm Prithivi — OLI's founder — and I want to thank you personally for what happened at {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}}. {{VOLUNTEER_COUNT}} volunteers, {{KITS_COLLECTED}} kits, Charlotte families served through Crisis Assistance Ministry.", "I started OLI because I believed Charlotte could do this. {{DRIVE_NAME}} proved me right. Thank you. — Prithivi 💜", "Keep Proving It →"),
    ("OLI {{DRIVE_NAME}}: from packing to people 💜", "From packing to people — {{DRIVE_NAME}} 💜", "The journey of a kit from your hands to a family's home", "{{NAME}}, here's the journey of each kit from OLI's {{DRIVE_NAME}}: packed by a volunteer at {{DRIVE_LOCATION}}, collected with {{KITS_COLLECTED}} others, handed to Crisis Assistance Ministry, and delivered to a Charlotte family who needed it.", "From your hands to their home. {{VOLUNTEER_COUNT}} volunteers made that journey possible. Thank you. 💜", "Start Another Journey →"),
    ("OLI {{DRIVE_NAME}}: this is what action looks like 🔥", "This is what action looks like — {{DRIVE_NAME}} 🔥", "Not talk. Kits. Real ones.", "{{NAME}}, this is what action looks like: OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} — {{VOLUNTEER_COUNT}} volunteers, {{KITS_COLLECTED}} kits, Charlotte families receiving hygiene supplies through Crisis Assistance Ministry. Action. Not talk.", "You were part of the action. Thank you for showing up. 🔥", "Take Action Again →"),
    ("OLI {{DRIVE_NAME}}: the community spoke 💜", "The community spoke — {{DRIVE_NAME}} 💜", "And what it said was: we care about Charlotte", "{{NAME}}, at OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}}, the community spoke loud: {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, {{KITS_COLLECTED}} hygiene kits packed, and Charlotte families being served through Crisis Assistance Ministry.", "The community said: we care. Thank you for being the voice of that. 💜", "Keep Speaking →"),
    ("OLI {{DRIVE_NAME}}: every kit matters 💜", "Every kit matters — {{DRIVE_NAME}} 💜", "{{KITS_COLLECTED}} kits. {{KITS_COLLECTED}} moments of care.", "{{NAME}}, every one of the {{KITS_COLLECTED}} kits from OLI's {{DRIVE_NAME}} matters — each toothbrush, each tube of toothpaste, each bar of soap, each bottle of lotion. Packed by {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, distributed by Crisis Assistance Ministry.", "{{KITS_COLLECTED}} moments of care for Charlotte families. Every single one matters. Thank you. 💜", "Create More Moments →"),
    ("OLI {{DRIVE_NAME}} complete — what's next? 💜", "{{DRIVE_NAME}} complete — what's next? 💜", "The drive is done. The mission never is.", "{{NAME}}, OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} is complete: {{KITS_COLLECTED}} kits, {{VOLUNTEER_COUNT}} volunteers, {{DRIVE_LOCATION}}. Crisis Assistance Ministry has the kits. Charlotte families will receive them. And the OLI mission continues.", "What's next? More drives. More kits. More Charlotte families served. Stay with us for it. 💜", "Stay for What's Next →"),
    ("OLI {{DRIVE_NAME}} results: beyond expectations 🌟", "Beyond expectations — {{DRIVE_NAME}} results 🌟", "We hoped for good. We got great.", "{{NAME}}, OLI's {{DRIVE_NAME}} went beyond expectations: {{KITS_COLLECTED}} hygiene kits packed by {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}} on {{DRIVE_DATE}}, with Crisis Assistance Ministry distributing to Charlotte families.", "We hoped for good. The community gave us great. Thank you for being the reason. 🌟", "Keep Exceeding Expectations →"),
    ("OLI {{DRIVE_NAME}}: the drive that keeps giving 🔄", "The drive that keeps giving — {{DRIVE_NAME}} 🔄", "The impact of {{DRIVE_DATE}} will last longer than one day", "{{NAME}}, OLI's {{DRIVE_NAME}} keeps giving long after {{DRIVE_DATE}}: {{KITS_COLLECTED}} kits distributed by Crisis Assistance Ministry mean weeks of hygiene for Charlotte families. The {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}} created lasting impact.", "The drive that keeps giving. Thank you for giving first. 🔄", "Give Again →"),
    ("OLI {{DRIVE_NAME}}: the OLI community is something special 💜", "The OLI community is something special 💜", "{{DRIVE_NAME}} proved it beyond any doubt", "{{NAME}}, OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} proved it beyond doubt: this community is something special. {{VOLUNTEER_COUNT}} people at {{DRIVE_LOCATION}}, {{KITS_COLLECTED}} kits packed, Charlotte families cared for through Crisis Assistance Ministry.", "Something special. You're part of it. Thank you for making OLI what it is. 💜", "Stay Special With Us →"),
    ("OLI {{DRIVE_NAME}}: small acts, big totals 💜", "Small acts, big totals — {{DRIVE_NAME}} 💜", "{{KITS_COLLECTED}} individual acts of packing that add up to everything", "{{NAME}}, {{KITS_COLLECTED}} is the total of thousands of small acts: individual toothbrushes placed, individual bars of soap packed, individual bottle of lotion closed. By {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, all adding up to Charlotte families helped through Crisis Assistance Ministry.", "Small acts. Big totals. Real impact. Thank you for contributing your small acts. 💜", "Small Act. Big Impact. →"),
    ("OLI {{DRIVE_NAME}}: Saket says thank you 🙌", "Saket says thank you — {{DRIVE_NAME}} 🙌", "From OLI's Director of Operations", "{{NAME}}, I'm Saket — OLI's Director of Operations — and I want to say thank you for making {{DRIVE_NAME}} on {{DRIVE_DATE}} run smoothly. {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, {{KITS_COLLECTED}} kits, crisis Assistance Ministry distribution. Flawless execution by an amazing community.", "The operations side of {{DRIVE_NAME}} was a joy to manage because of you. Thank you. — Saket 🙌", "Support Our Next Drive →"),
    ("OLI {{DRIVE_NAME}}: Rishi is spreading the word 📣", "Rishi is spreading the word about {{DRIVE_NAME}} 📣", "From OLI's Marketing Head", "{{NAME}}, I'm Rishi — OLI's Marketing Head — and I'm shouting from the rooftops about {{DRIVE_NAME}}: {{KITS_COLLECTED}} kits, {{VOLUNTEER_COUNT}} volunteers, {{DRIVE_LOCATION}}, and Charlotte families about to receive hygiene supplies through Crisis Assistance Ministry.", "I'm spreading the word. Help me spread it further. Share this with someone who needs to hear it. — Rishi 📣", "Share the Story →"),
    ("OLI {{DRIVE_NAME}} — a Charlotte story 🏙️", "A Charlotte story — {{DRIVE_NAME}} 🏙️", "This city wrote another great chapter", "{{NAME}}, Charlotte wrote another great chapter on {{DRIVE_DATE}}: OLI's {{DRIVE_NAME}} at {{DRIVE_LOCATION}}, {{VOLUNTEER_COUNT}} volunteers, {{KITS_COLLECTED}} kits, and a student-led nonprofit proving that Charlotte takes care of its own through Crisis Assistance Ministry.", "A Charlotte story. Thank you for being a character in it. 🏙️", "Keep Writing the Story →"),
    ("OLI {{DRIVE_NAME}}: honored to serve this community 💜", "Honored to serve this community — {{DRIVE_NAME}} 💜", "OLI is grateful for every volunteer and supporter", "{{NAME}}, OLI is honored — genuinely honored — to serve this community. {{DRIVE_NAME}} on {{DRIVE_DATE}} reminded us why: {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, {{KITS_COLLECTED}} kits, Charlotte families helped through Crisis Assistance Ministry.", "We're honored. Thank you for giving us the honor. 💜", "Honor Us With Your Support →"),
    ("OLI {{DRIVE_NAME}}: you showed up, Charlotte 💜", "You showed up, Charlotte — {{DRIVE_NAME}} 💜", "The city came through. Again.", "{{NAME}}, Charlotte came through at OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} — {{VOLUNTEER_COUNT}} volunteers showed up at {{DRIVE_LOCATION}}, packed {{KITS_COLLECTED}} hygiene kits, and created real impact for families through Crisis Assistance Ministry.", "You showed up, Charlotte. And Charlotte families will feel it. Thank you. 💜", "Show Up Again →"),
    ("OLI {{DRIVE_NAME}}: the drive that defined us 💜", "The drive that defined us — {{DRIVE_NAME}} 💜", "Drives like this are why OLI exists", "{{NAME}}, drives like {{DRIVE_NAME}} are why OLI exists — {{VOLUNTEER_COUNT}} people at {{DRIVE_LOCATION}} on {{DRIVE_DATE}}, packing {{KITS_COLLECTED}} hygiene kits for Charlotte families through Crisis Assistance Ministry. This is the definition of our mission.", "Defined by this drive. Built for the next one. Thank you. 💜", "Be There for the Next One →"),
    ("OLI {{DRIVE_NAME}}: impact delivered ✅", "Impact delivered — {{DRIVE_NAME}} ✅", "From your hands to Charlotte families", "{{NAME}}, impact delivered: OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} produced {{KITS_COLLECTED}} hygiene kits, packed by {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, now distributed to Charlotte families through Crisis Assistance Ministry. Delivered.", "Impact delivered. Thank you for helping make sure it arrived. ✅", "Deliver More Impact →"),
    ("OLI {{DRIVE_NAME}}: what {{VOLUNTEER_COUNT}} volunteers can do 💜", "What {{VOLUNTEER_COUNT}} volunteers can do — {{DRIVE_NAME}} 💜", "The answer is: {{KITS_COLLECTED}} kits and counting", "{{NAME}}, here's what {{VOLUNTEER_COUNT}} volunteers can do: pack {{KITS_COLLECTED}} hygiene kits at {{DRIVE_LOCATION}} on {{DRIVE_DATE}} and send them to Charlotte families through Crisis Assistance Ministry. That's the answer.", "{{VOLUNTEER_COUNT}} volunteers did that. You supported them. Thank you. 💜", "Support More Volunteers →"),
    ("OLI {{DRIVE_NAME}}: the mission grows stronger 💪", "The mission grows stronger — {{DRIVE_NAME}} 💪", "Each drive, OLI gets stronger. This one proves it.", "{{NAME}}, each OLI drive makes the mission stronger — and {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is the latest proof: {{KITS_COLLECTED}} kits, {{VOLUNTEER_COUNT}} volunteers, Charlotte families helped through Crisis Assistance Ministry.", "Stronger than before. Growing. Thank you for fueling the growth. 💪", "Fuel the Growth →"),
    ("OLI {{DRIVE_NAME}}: from the team to you 💜", "From the OLI team to you — {{DRIVE_NAME}} 💜", "A genuine thank you from Prithivi, Saket, and Rishi", "{{NAME}}, from the full OLI team — Prithivi, Saket, and Rishi — thank you for your role in making {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} a success. {{KITS_COLLECTED}} kits, {{VOLUNTEER_COUNT}} volunteers, Charlotte families served through Crisis Assistance Ministry.", "From us to you: thank you. From the kits to Charlotte families: care. It's all connected. 💜", "Stay Connected →"),
    ("OLI {{DRIVE_NAME}}: the recap you've been waiting for 💜", "The recap you've been waiting for — {{DRIVE_NAME}} 💜", "It's good. Very good.", "{{NAME}}, you've been waiting for the {{DRIVE_NAME}} recap — here it is: {{KITS_COLLECTED}} hygiene kits packed by {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}} on {{DRIVE_DATE}}, now distributed through Crisis Assistance Ministry to Charlotte families.", "Very good. You helped make it that way. Thank you. 💜", "Make the Next One Even Better →"),
    ("OLI {{DRIVE_NAME}}: the love was palpable 💜", "The love was palpable — {{DRIVE_NAME}} 💜", "You could feel the care in every kit packed", "{{NAME}}, the love was palpable at OLI's {{DRIVE_NAME}} — {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}} packing {{KITS_COLLECTED}} kits with genuine care. That care is going to Charlotte families through Crisis Assistance Ministry.", "You could feel it. We hope Charlotte families feel it too. Thank you. 💜", "Keep the Love Flowing →"),
    ("OLI {{DRIVE_NAME}}: kits + community = Charlotte wins 💜", "Kits + community = Charlotte wins — {{DRIVE_NAME}} 💜", "The OLI equation worked perfectly", "{{NAME}}, OLI's equation: kits + community = Charlotte wins. {{DRIVE_NAME}} solved it: {{KITS_COLLECTED}} kits, {{VOLUNTEER_COUNT}} community members at {{DRIVE_LOCATION}}, and Charlotte winning through Crisis Assistance Ministry distribution.", "Kits + community = Charlotte wins. Every time. Thank you for being the community. 💜", "Be the Community →"),
    ("OLI {{DRIVE_NAME}}: feel good about {{DRIVE_DATE}} 🌟", "Feel good about {{DRIVE_DATE}} — {{DRIVE_NAME}} 🌟", "You have every reason to", "{{NAME}}, feel good about {{DRIVE_DATE}} — because OLI's {{DRIVE_NAME}} at {{DRIVE_LOCATION}} made something real happen: {{KITS_COLLECTED}} hygiene kits heading to Charlotte families through Crisis Assistance Ministry, packed by {{VOLUNTEER_COUNT}} volunteers.", "Feel good. You have every reason. Thank you. 🌟", "Feel Good Again →"),
    ("OLI {{DRIVE_NAME}}: the results we dreamed of 💜", "The results we dreamed of — {{DRIVE_NAME}} 💜", "When the reality matches the vision", "{{NAME}}, OLI's {{DRIVE_NAME}} results matched our vision: {{KITS_COLLECTED}} hygiene kits, {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}} on {{DRIVE_DATE}}, Charlotte families receiving them through Crisis Assistance Ministry. When reality matches the dream.", "We dreamed of this. You made it real. Thank you. 💜", "Help Dream Bigger →"),
    ("OLI {{DRIVE_NAME}}: because of you 💜", "Because of you — {{DRIVE_NAME}} 💜", "{{KITS_COLLECTED}} kits exist because of people like you", "{{NAME}}, {{KITS_COLLECTED}} hygiene kits exist because of people like you: people who support OLI, who show up to drives like {{DRIVE_NAME}}, who spread the word, who believe in Charlotte. {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}} made it real.", "Because of you, Charlotte families have these kits through Crisis Assistance Ministry. Because of you. 💜", "Keep Being You →"),
    ("OLI {{DRIVE_NAME}}: we keep our promises 💜", "We keep our promises — {{DRIVE_NAME}} 💜", "OLI promised to show up. Here's the proof.", "{{NAME}}, OLI keeps its promises — and {{DRIVE_NAME}} on {{DRIVE_DATE}} is the proof. We promised hygiene kits for Charlotte families. We delivered: {{KITS_COLLECTED}} kits by {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, distributed through Crisis Assistance Ministry.", "We keep our promises. Thank you for trusting us to. 💜", "Trust Us Again →"),
    ("OLI {{DRIVE_NAME}} — the give was real 💜", "The give was real — {{DRIVE_NAME}} 💜", "Real volunteers. Real kits. Real Charlotte families.", "{{NAME}}, the give at OLI's {{DRIVE_NAME}} was real — {{VOLUNTEER_COUNT}} volunteers giving their time at {{DRIVE_LOCATION}}, {{KITS_COLLECTED}} kits giving hygiene to Charlotte families through Crisis Assistance Ministry on {{DRIVE_DATE}}.", "Real give. Real receive. Real Charlotte. Thank you. 💜", "Give Again →"),
    ("OLI {{DRIVE_NAME}}: the count that counts 🔢", "The count that counts — {{DRIVE_NAME}} 🔢", "{{KITS_COLLECTED}} is a number worth celebrating", "{{NAME}}, OLI's {{DRIVE_NAME}} produced a count that counts: {{KITS_COLLECTED}} hygiene kits. That number represents {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}} on {{DRIVE_DATE}}, and it reaches Charlotte families through Crisis Assistance Ministry.", "{{KITS_COLLECTED}}. A number worth celebrating. Thank you for helping make it happen. 🔢", "Add to the Count →"),
    ("OLI {{DRIVE_NAME}}: one drive, one city, one love 💜", "One drive, one city, one love — {{DRIVE_NAME}} 💜", "This is what the name means", "{{NAME}}, one drive: {{DRIVE_NAME}}. One city: Charlotte. One love: the care packed into {{KITS_COLLECTED}} hygiene kits by {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, distributed through Crisis Assistance Ministry.", "One Love Initiative. This is what the name means. Thank you for being part of it. 💜", "Live the Name →"),
    ("OLI {{DRIVE_NAME}}: what a team 💜", "What a team — {{DRIVE_NAME}} 💜", "{{VOLUNTEER_COUNT}} people came together. Look what happened.", "{{NAME}}, what a team — {{VOLUNTEER_COUNT}} people at OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} came together and produced {{KITS_COLLECTED}} hygiene kits for Charlotte families through Crisis Assistance Ministry.", "What a team. You're part of it. Thank you. 💜", "Stay on the Team →"),
    ("OLI {{DRIVE_NAME}}: driving toward 20,000 🎯", "Driving toward 20,000 — {{DRIVE_NAME}} 💜", "Every kit gets us closer to the goal", "{{NAME}}, OLI's goal is 20,000 hygiene kits for Charlotte families by end of summer 2025 — and {{DRIVE_NAME}} pushed us significantly closer. {{KITS_COLLECTED}} more kits through Crisis Assistance Ministry, packed by {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}.", "The goal is {{KITS_COLLECTED}} steps closer. Thank you for helping us drive there. 🎯", "Drive Toward 20K →"),
    ("OLI {{DRIVE_NAME}}: the recap that fills your heart 💜", "The recap that fills your heart — {{DRIVE_NAME}} 💜", "Some numbers just make you feel something", "{{NAME}}, {{KITS_COLLECTED}} kits. {{VOLUNTEER_COUNT}} volunteers. {{DRIVE_LOCATION}}. {{DRIVE_DATE}}. Crisis Assistance Ministry. Charlotte families. Those numbers fill the heart — because they represent real people helping real people in our city.", "Let your heart fill. You helped make those numbers. Thank you. 💜", "Fill More Hearts →"),
    ("OLI {{DRIVE_NAME}}: the power of showing up 💜", "The power of showing up — {{DRIVE_NAME}} 💜", "{{VOLUNTEER_COUNT}} people proved what showing up does", "{{NAME}}, {{VOLUNTEER_COUNT}} volunteers proved the power of showing up at OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}}: {{KITS_COLLECTED}} hygiene kits heading to Charlotte families through Crisis Assistance Ministry.", "The power of showing up is {{KITS_COLLECTED}} kits. Thank you for showing up — or supporting those who did. 💜", "Show Up Again →"),
    ("OLI {{DRIVE_NAME}}: the number we're most proud of 💜", "The number we're most proud of — {{DRIVE_NAME}} 💜", "Hint: it's {{KITS_COLLECTED}}", "{{NAME}}, at OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}}, the number we're most proud of is {{KITS_COLLECTED}} — the hygiene kits packed by {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, now distributed to Charlotte families through Crisis Assistance Ministry.", "{{KITS_COLLECTED}}. Our proudest number from {{DRIVE_NAME}}. You helped make it. 💜", "Help Us Beat It →"),
    ("OLI {{DRIVE_NAME}}: Charlotte's kindness counted 💜", "Charlotte's kindness counted — {{DRIVE_NAME}} 💜", "When kindness is counted, it becomes {{KITS_COLLECTED}}", "{{NAME}}, at OLI's {{DRIVE_NAME}}, Charlotte's kindness was literally counted: {{KITS_COLLECTED}} hygiene kits, the product of {{VOLUNTEER_COUNT}} volunteers' kindness at {{DRIVE_LOCATION}} on {{DRIVE_DATE}}, heading to Charlotte families through Crisis Assistance Ministry.", "Kindness counted. It came to {{KITS_COLLECTED}}. Thank you for adding your count to it. 💜", "Add to the Kindness →"),
    ("OLI {{DRIVE_NAME}}: a benchmark for future drives 💜", "A benchmark for future drives — {{DRIVE_NAME}} 💜", "OLI just set a new standard for itself", "{{NAME}}, OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} set a new benchmark: {{KITS_COLLECTED}} kits, {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, Charlotte families served through Crisis Assistance Ministry. Future drives aim for this and beyond.", "You helped set the benchmark. Thank you for raising the bar. 💜", "Help Us Exceed It →"),
    ("OLI {{DRIVE_NAME}}: the stats that inspire 📊", "The stats that inspire — {{DRIVE_NAME}} 📊", "Numbers that move you to do more", "{{NAME}}, here are OLI {{DRIVE_NAME}} stats that inspire: {{KITS_COLLECTED}} hygiene kits, {{VOLUNTEER_COUNT}} volunteers, {{DRIVE_LOCATION}}, {{DRIVE_DATE}}, and Charlotte families receiving care through Crisis Assistance Ministry.", "Inspired? Good. Channel that into the next drive. We'll be there. 📊 💜", "Stay Inspired →"),
    ("OLI {{DRIVE_NAME}} — a note of gratitude 💜", "A note of gratitude — {{DRIVE_NAME}} 💜", "Genuine, from the OLI heart", "{{NAME}}, a genuine note of gratitude from OLI: {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} was a success because of this community. {{KITS_COLLECTED}} kits for Charlotte families through Crisis Assistance Ministry. {{VOLUNTEER_COUNT}} volunteers who made it happen.", "Gratitude that's real. For impact that's real. Thank you. 💜", "Receive Our Gratitude →"),
    ("OLI {{DRIVE_NAME}}: the chapter that mattered 💜", "The chapter that mattered — {{DRIVE_NAME}} 💜", "Every OLI drive writes a new chapter. This one counts.", "{{NAME}}, OLI's story is written chapter by chapter — and {{DRIVE_NAME}} on {{DRIVE_DATE}} is a chapter that mattered: {{KITS_COLLECTED}} kits, {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, Charlotte families receiving care through Crisis Assistance Ministry.", "The chapter that mattered. You were part of writing it. 💜", "Write the Next Chapter →"),
    ("OLI {{DRIVE_NAME}}: the energy in that room 💜", "The energy in that room — {{DRIVE_NAME}} 💜", "{{VOLUNTEER_COUNT}} volunteers packed more than kits", "{{NAME}}, the energy in {{DRIVE_LOCATION}} on {{DRIVE_DATE}} was something else — {{VOLUNTEER_COUNT}} volunteers packing kits with intention, community building around a shared mission, {{KITS_COLLECTED}} hygiene kits heading to Charlotte families through Crisis Assistance Ministry.", "They packed kits. They also packed that room with energy. Thank you for being part of it. 💜", "Bring the Energy Again →"),
    ("OLI {{DRIVE_NAME}}: we did something real 💜", "We did something real — {{DRIVE_NAME}} 💜", "Not symbolic. Actual. {{KITS_COLLECTED}} kits real.", "{{NAME}}, OLI's {{DRIVE_NAME}} was not symbolic — it was actual. {{KITS_COLLECTED}} actual hygiene kits packed by {{VOLUNTEER_COUNT}} actual volunteers at {{DRIVE_LOCATION}} on {{DRIVE_DATE}}, reaching Charlotte families through Crisis Assistance Ministry.", "We did something real. You were part of something real. Thank you. 💜", "Do Something Real Again →"),
    ("OLI {{DRIVE_NAME}} — until next time 💜", "Until next time — {{DRIVE_NAME}} 💜", "The drive is done. The friendship isn't.", "{{NAME}}, OLI's {{DRIVE_NAME}} is wrapped — {{KITS_COLLECTED}} kits, {{VOLUNTEER_COUNT}} volunteers, {{DRIVE_LOCATION}}, {{DRIVE_DATE}}, Charlotte families served through Crisis Assistance Ministry. Until next time, carry the OLI spirit with you.", "Until next time. Keep caring. Keep showing up. 💜", "Stay Until Next Time →"),
    ("OLI {{DRIVE_NAME}}: faith in this city, restored 💜", "Faith in this city, restored — {{DRIVE_NAME}} 💜", "Charlotte proves it cares, every single drive", "{{NAME}}, if you ever doubted Charlotte's capacity for care — OLI's {{DRIVE_NAME}} restores faith. {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}} on {{DRIVE_DATE}}, {{KITS_COLLECTED}} kits for Charlotte families through Crisis Assistance Ministry.", "Faith restored. City proven. Thank you for being the proof. 💜", "Restore It Again →"),
    ("OLI {{DRIVE_NAME}}: impact is the right word 💜", "Impact is the right word — {{DRIVE_NAME}} 💜", "Not just activity. Real, measurable impact.", "{{NAME}}, impact is the right word for OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}}: {{KITS_COLLECTED}} hygiene kits reaching Charlotte families through Crisis Assistance Ministry — measurable, real, meaningful impact created by {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}.", "Impact is the right word. Thank you for creating it. 💜", "Create Impact Again →"),
    ("OLI {{DRIVE_NAME}}: together we changed things 💜", "Together we changed things — {{DRIVE_NAME}} 💜", "{{KITS_COLLECTED}} kits changed {{KITS_COLLECTED}} realities", "{{NAME}}, OLI's {{DRIVE_NAME}} changed {{KITS_COLLECTED}} realities for Charlotte children and families — hygiene supplies that change daily life, packed by {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, delivered through Crisis Assistance Ministry.", "Together we changed things. Thank you for being part of the together. 💜", "Change Things Together →"),
    ("OLI {{DRIVE_NAME}}: see you at the next one 💜", "See you at the next one — {{DRIVE_NAME}} 💜", "The best drives inspire the next one", "{{NAME}}, OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} inspired us — {{KITS_COLLECTED}} kits, {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, Charlotte families served through Crisis Assistance Ministry. The best drives inspire the next one.", "We'll see you at the next one. Keep your calendar open. Keep your heart ready. 💜", "See You There →"),
    ("OLI {{DRIVE_NAME}}: a moment of celebration 🎉", "A moment of celebration — {{DRIVE_NAME}} 🎉", "Take a moment. You deserve it.", "{{NAME}}, take a moment to celebrate: OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} produced {{KITS_COLLECTED}} hygiene kits for Charlotte families through Crisis Assistance Ministry, powered by {{VOLUNTEER_COUNT}} volunteers.", "You deserve a moment of celebration. You helped make this happen. 🎉", "Celebrate Again →"),
    ("OLI {{DRIVE_NAME}}: the work speaks for itself 💜", "The work speaks for itself — {{DRIVE_NAME}} 💜", "No marketing needed. Just the facts.", "{{NAME}}, OLI's {{DRIVE_NAME}} needs no marketing spin: {{KITS_COLLECTED}} hygiene kits, {{VOLUNTEER_COUNT}} volunteers, {{DRIVE_LOCATION}}, {{DRIVE_DATE}}, Charlotte families served through Crisis Assistance Ministry. The work speaks for itself.", "It speaks loudly. Thank you for being the work. 💜", "Let the Work Speak →"),
    ("OLI {{DRIVE_NAME}}: closing the loop on Charlotte families 💜", "Closing the loop on Charlotte families — {{DRIVE_NAME}} 💜", "From need to kit to family — the loop is closed", "{{NAME}}, OLI's {{DRIVE_NAME}} closed the loop for Charlotte families: need identified by Crisis Assistance Ministry, kits packed by {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}} on {{DRIVE_DATE}}, {{KITS_COLLECTED}} hygiene supplies delivered to families who needed them.", "Loop closed. Families helped. Thank you for being part of the circle. 💜", "Close Another Loop →"),
    ("OLI {{DRIVE_NAME}}: the numbers behind the mission 🔢", "The numbers behind the mission — {{DRIVE_NAME}} 🔢", "Every number is a person. Every person matters.", "{{NAME}}, OLI's {{DRIVE_NAME}} numbers: {{KITS_COLLECTED}} (kits packed), {{VOLUNTEER_COUNT}} (volunteers who showed up), {{DRIVE_LOCATION}} (where it happened), {{DRIVE_DATE}} (when it happened). Each number is a person. Each person matters.", "Crisis Assistance Ministry connects those numbers to Charlotte families. Thank you for being a number that matters. 💜", "Be a Number That Matters →"),
    ("OLI {{DRIVE_NAME}}: the momentum is real 🚀", "The momentum is real — {{DRIVE_NAME}} 🚀", "Drives like this build unstoppable missions", "{{NAME}}, drives like OLI's {{DRIVE_NAME}} build momentum — {{KITS_COLLECTED}} kits, {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, Charlotte families served through Crisis Assistance Ministry. Momentum that's hard to stop once it starts.", "The momentum is real. Thank you for being the force behind it. 🚀", "Keep the Momentum →"),
    ("OLI {{DRIVE_NAME}}: this is what we'll remember 💜", "This is what we'll remember — {{DRIVE_NAME}} 💜", "The memories that stick are the ones where you did something", "{{NAME}}, the memories that stick are the ones where you did something — and OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is exactly that. {{KITS_COLLECTED}} kits, {{VOLUNTEER_COUNT}} volunteers, Charlotte families helped through Crisis Assistance Ministry.", "This is what we'll remember. Thank you for making it memorable. 💜", "Make More Memories →"),
    ("OLI {{DRIVE_NAME}}: the way it's supposed to work 💜", "The way it's supposed to work — {{DRIVE_NAME}} 💜", "Community organizing at its most effective", "{{NAME}}, OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} is community organizing the way it's supposed to work: students lead, community volunteers, {{KITS_COLLECTED}} kits get packed at {{DRIVE_LOCATION}}, and Crisis Assistance Ministry distributes to Charlotte families.", "The way it's supposed to work. Thank you for making it work. 💜", "Make It Work Again →"),
    ("OLI {{DRIVE_NAME}}: powered by love, delivered with care 💜", "Powered by love, delivered with care — {{DRIVE_NAME}} 💜", "One Love Initiative delivers on its name", "{{NAME}}, OLI delivers on its name — One Love Initiative: powered by love from {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, {{KITS_COLLECTED}} kits delivered with care to Charlotte families through Crisis Assistance Ministry on {{DRIVE_DATE}}.", "Powered by love. Delivered with care. Thank you for the power and the care. 💜", "Power the Next Drive →"),
    ("OLI {{DRIVE_NAME}}: more than we hoped for 💜", "More than we hoped for — {{DRIVE_NAME}} 💜", "Sometimes the community exceeds every expectation", "{{NAME}}, OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} delivered more than we hoped: {{KITS_COLLECTED}} hygiene kits packed by {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, all heading to Charlotte families through Crisis Assistance Ministry.", "More than we hoped. Because of you. Thank you. 💜", "Exceed Expectations Again →"),
    ("OLI {{DRIVE_NAME}}: you're our favorite community 💜", "You're our favorite community — {{DRIVE_NAME}} 💜", "OLI is grateful for every single supporter", "{{NAME}}, OLI has one community — and after {{DRIVE_NAME}} on {{DRIVE_DATE}}, you're our absolute favorite. {{KITS_COLLECTED}} kits, {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, Charlotte families helped through Crisis Assistance Ministry.", "Our favorite community. Thank you for being it. 💜", "Stay Our Favorite →"),
    ("OLI {{DRIVE_NAME}}: children's hygiene = children's dignity 💜", "Children's hygiene = children's dignity — {{DRIVE_NAME}} 💜", "That's what {{KITS_COLLECTED}} kits represent", "{{NAME}}, OLI believes children's hygiene = children's dignity — and {{DRIVE_NAME}} on {{DRIVE_DATE}} packed {{KITS_COLLECTED}} units of dignity at {{DRIVE_LOCATION}} by {{VOLUNTEER_COUNT}} volunteers, delivered through Crisis Assistance Ministry.", "{{KITS_COLLECTED}} kids with a little more dignity. Thank you for caring about that. 💜", "Restore More Dignity →"),
    ("OLI {{DRIVE_NAME}}: grateful for every volunteer 💜", "Grateful for every volunteer — {{DRIVE_NAME}} 💜", "{{VOLUNTEER_COUNT}} people who showed up deserve recognition", "{{NAME}}, OLI is grateful for every one of the {{VOLUNTEER_COUNT}} volunteers who showed up to {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}}. Because of them, {{KITS_COLLECTED}} hygiene kits are reaching Charlotte families through Crisis Assistance Ministry.", "Every volunteer. Every kit. Every family. Grateful for all of it. 💜", "Volunteer at the Next Drive →"),
    ("OLI {{DRIVE_NAME}}: kit by kit, we change Charlotte 💜", "Kit by kit, we change Charlotte — {{DRIVE_NAME}} 💜", "Slow change is still change. And it adds up.", "{{NAME}}, kit by kit, OLI changes Charlotte — and {{DRIVE_NAME}} on {{DRIVE_DATE}} added {{KITS_COLLECTED}} kits to that change. {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, distributed through Crisis Assistance Ministry. Kit by kit.", "Kit by kit. Slow. Steady. Real. Thank you for helping change Charlotte. 💜", "Change Charlotte Kit by Kit →"),
    ("OLI {{DRIVE_NAME}}: the drive that gave us hope 💜", "The drive that gave us hope — {{DRIVE_NAME}} 💜", "Hope for Charlotte. Hope for OLI's mission.", "{{NAME}}, OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} gave us hope — hope that Charlotte communities can care for each other, that {{VOLUNTEER_COUNT}} people can show up at {{DRIVE_LOCATION}}, and that {{KITS_COLLECTED}} kits can reach families through Crisis Assistance Ministry.", "The drive gave us hope. You gave us the drive. Thank you. 💜", "Give Us Hope Again →"),
    ("OLI {{DRIVE_NAME}}: this is just the beginning 🚀", "This is just the beginning — {{DRIVE_NAME}} 🚀", "{{KITS_COLLECTED}} kits is a number we'll grow from", "{{NAME}}, {{KITS_COLLECTED}} hygiene kits from {{DRIVE_NAME}} is just the beginning — OLI is growing, our volunteer base (currently {{VOLUNTEER_COUNT}} strong at {{DRIVE_LOCATION}}) is expanding, and Charlotte families will be served through Crisis Assistance Ministry at greater scale.", "Just the beginning. Thank you for starting the journey with us. 🚀", "Grow With Us →"),
    ("OLI {{DRIVE_NAME}}: a new bar for OLI 💜", "A new bar for OLI — {{DRIVE_NAME}} 💜", "We just raised our own standard", "{{NAME}}, OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} raised our own bar: {{KITS_COLLECTED}} kits, {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, Charlotte families helped through Crisis Assistance Ministry. We now aim higher because this drive showed us we can.", "New bar. Higher aim. Thank you for helping us raise both. 💜", "Clear the New Bar →"),
    ("OLI {{DRIVE_NAME}}: the Charlotte difference 🏙️", "The Charlotte difference — {{DRIVE_NAME}} 🏙️", "What makes Charlotte unique is how it shows up", "{{NAME}}, what makes Charlotte different is how it shows up — and OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} is proof: {{VOLUNTEER_COUNT}} people at {{DRIVE_LOCATION}}, {{KITS_COLLECTED}} kits for Charlotte families through Crisis Assistance Ministry.", "The Charlotte difference. You are the Charlotte difference. Thank you. 🏙️", "Be the Difference →"),
    ("OLI {{DRIVE_NAME}}: building blocks for a better Charlotte 💜", "Building blocks for a better Charlotte — {{DRIVE_NAME}} 💜", "Each kit is a literal building block", "{{NAME}}, OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} laid {{KITS_COLLECTED}} building blocks for a better Charlotte — hygiene kits packed by {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, distributed to families through Crisis Assistance Ministry.", "{{KITS_COLLECTED}} building blocks. A stronger Charlotte. Thank you for building with us. 💜", "Keep Building Charlotte →"),
    ("OLI {{DRIVE_NAME}}: what love in action looks like 💜", "What love in action looks like — {{DRIVE_NAME}} 💜", "OLI proves love isn't passive", "{{NAME}}, love in action at OLI's {{DRIVE_NAME}} looked like this: {{VOLUNTEER_COUNT}} people at {{DRIVE_LOCATION}} on {{DRIVE_DATE}}, packing {{KITS_COLLECTED}} hygiene kits for Charlotte families, distributed through Crisis Assistance Ministry.", "Love in action. Not passive. Real. Thank you for acting with us. 💜", "Act With Love →"),
    ("OLI {{DRIVE_NAME}}: the drive Charlotte deserved 💜", "The drive Charlotte deserved — {{DRIVE_NAME}} 💜", "Charlotte families deserve care. OLI delivers it.", "{{NAME}}, Charlotte families deserve care — and OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} delivered: {{KITS_COLLECTED}} hygiene kits packed by {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, distributed through Crisis Assistance Ministry.", "The drive Charlotte deserved. Thank you for delivering it with us. 💜", "Deliver Again →"),
    ("OLI {{DRIVE_NAME}}: something to be proud of 💜", "Something to be proud of — {{DRIVE_NAME}} 💜", "Hold your head high. You helped do this.", "{{NAME}}, hold your head high: OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} produced {{KITS_COLLECTED}} hygiene kits for Charlotte families through Crisis Assistance Ministry. {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}} made it happen.", "Something to be proud of. You were part of it. Thank you. 💜", "Be Proud Again →"),
    ("OLI {{DRIVE_NAME}}: the mission is worth it 💜", "The mission is worth it — {{DRIVE_NAME}} 💜", "Every kit confirms: this is worth doing", "{{NAME}}, every kit at OLI's {{DRIVE_NAME}} confirms: this mission is worth it. {{KITS_COLLECTED}} kits, {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}} on {{DRIVE_DATE}}, Charlotte families receiving hygiene supplies through Crisis Assistance Ministry.", "Worth it. Every time. Thank you for believing in a mission that's worth it. 💜", "Keep Believing →"),
    ("OLI {{DRIVE_NAME}}: your generosity is incredible 💜", "Your generosity is incredible — {{DRIVE_NAME}} 💜", "The OLI community is among the most generous we know", "{{NAME}}, the OLI community's generosity is incredible — and {{DRIVE_NAME}} on {{DRIVE_DATE}} proved it once more: {{VOLUNTEER_COUNT}} generous volunteers at {{DRIVE_LOCATION}}, {{KITS_COLLECTED}} generous kits for Charlotte families through Crisis Assistance Ministry.", "Incredible generosity. Thank you for being that kind of generous. 💜", "Be Generous Again →"),
    ("OLI {{DRIVE_NAME}}: changing Charlotte, one kit at a time 💜", "Changing Charlotte, one kit at a time — {{DRIVE_NAME}} 💜", "OLI's formula is working", "{{NAME}}, OLI's formula: one kit at a time, change Charlotte. {{DRIVE_NAME}} on {{DRIVE_DATE}} added {{KITS_COLLECTED}} kits to that change, packed by {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, distributed through Crisis Assistance Ministry.", "One kit at a time. {{KITS_COLLECTED}} times. Changing Charlotte. Thank you. 💜", "Change Charlotte →"),
    ("OLI {{DRIVE_NAME}}: a drive that made news 📰", "A drive that made news — {{DRIVE_NAME}} 📰", "{{KITS_COLLECTED}} kits is a story worth telling", "{{NAME}}, OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} is a story worth telling: {{KITS_COLLECTED}} hygiene kits packed at {{DRIVE_LOCATION}} by {{VOLUNTEER_COUNT}} volunteers, heading to Charlotte families through Crisis Assistance Ministry.", "Tell that story. Share this email. Let Charlotte know what's happening in its own backyard. 📰 💜", "Tell the Story →"),
    ("OLI {{DRIVE_NAME}}: the numbers we'll tell our kids about 💜", "The numbers we'll tell our kids about — {{DRIVE_NAME}} 💜", "Someday this will be a story", "{{NAME}}, someday OLI's story will be told — and {{DRIVE_NAME}}'s numbers will be part of it: {{KITS_COLLECTED}} kits, {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}} on {{DRIVE_DATE}}, Charlotte families served through Crisis Assistance Ministry.", "Someday this will be a great story. Thank you for being part of writing it. 💜", "Write the Story →"),
    ("OLI {{DRIVE_NAME}}: fueled by the OLI community 💜", "Fueled by the OLI community — {{DRIVE_NAME}} 💜", "OLI runs on community. This drive proved it.", "{{NAME}}, OLI runs on community — and {{DRIVE_NAME}} on {{DRIVE_DATE}} proved it: {{VOLUNTEER_COUNT}} community members at {{DRIVE_LOCATION}}, {{KITS_COLLECTED}} kits, Charlotte families helped through Crisis Assistance Ministry. Fueled entirely by people who care.", "Fueled by community. Run by students. Powered by love. Thank you. 💜", "Fuel the Next Drive →"),
    ("OLI {{DRIVE_NAME}}: an afternoon that mattered 💜", "An afternoon that mattered — {{DRIVE_NAME}} 💜", "Some afternoons stay with you. {{DRIVE_DATE}} will.", "{{NAME}}, {{DRIVE_DATE}} at {{DRIVE_LOCATION}} will stay with everyone who was part of OLI's {{DRIVE_NAME}}: {{VOLUNTEER_COUNT}} volunteers, {{KITS_COLLECTED}} kits, and Charlotte families receiving hygiene supplies through Crisis Assistance Ministry.", "An afternoon that mattered. Thank you for making it one. 💜", "Make Another Matter →"),
    ("OLI {{DRIVE_NAME}}: well done, OLI community 💜", "Well done, OLI community — {{DRIVE_NAME}} 💜", "A genuine well done from the OLI founders", "{{NAME}}, well done — the OLI community packed {{KITS_COLLECTED}} hygiene kits at {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}}, with {{VOLUNTEER_COUNT}} volunteers making it happen. Crisis Assistance Ministry distributes to Charlotte families.", "Well done. Sincerely. From the OLI team. 💜", "Keep Doing Well →"),
    ("OLI {{DRIVE_NAME}}: proving Charlotte is great 🏙️", "Proving Charlotte is great — {{DRIVE_NAME}} 🏙️", "One drive at a time, Charlotte proves its greatness", "{{NAME}}, OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} proved Charlotte is great: {{VOLUNTEER_COUNT}} people at {{DRIVE_LOCATION}}, {{KITS_COLLECTED}} kits for Charlotte families through Crisis Assistance Ministry. Great cities take care of their own.", "Charlotte is great. You're part of why. Thank you. 🏙️", "Prove Charlotte is Great →"),
    ("OLI {{DRIVE_NAME}}: the recap your inbox deserved 💜", "The recap your inbox deserved — {{DRIVE_NAME}} 💜", "Good news for once. Lots of it.", "{{NAME}}, good news for your inbox: OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} produced {{KITS_COLLECTED}} hygiene kits, packed by {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, heading to Charlotte families through Crisis Assistance Ministry.", "Good news. You helped make it. Thank you. 💜", "Make More Good News →"),
    ("OLI {{DRIVE_NAME}}: thank you, thank you, thank you 💜", "Thank you, thank you, thank you — {{DRIVE_NAME}} 💜", "Some drives warrant three thank-yous", "{{NAME}}, three thank-yous for OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}}: thank you for supporting OLI, thank you to the {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, and thank you to everyone who helped make {{KITS_COLLECTED}} kits possible for Charlotte families through Crisis Assistance Ministry.", "Thank you. Thank you. Thank you. 💜", "Accept Our Gratitude →"),
    ("OLI {{DRIVE_NAME}}: the gift that reached Charlotte 🎁", "The gift that reached Charlotte — {{DRIVE_NAME}} 🎁", "Every kit is a gift. {{KITS_COLLECTED}} gifts delivered.", "{{NAME}}, OLI's {{DRIVE_NAME}} sent {{KITS_COLLECTED}} gifts to Charlotte families: hygiene kits packed by {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}} on {{DRIVE_DATE}}, wrapped with care, delivered through Crisis Assistance Ministry.", "{{KITS_COLLECTED}} gifts to Charlotte. Sent with love. Thank you for helping us give. 🎁", "Give Again →"),
    ("OLI {{DRIVE_NAME}}: this is what OLI is all about 💜", "This is what OLI is all about — {{DRIVE_NAME}} 💜", "Drives, kits, community, and Charlotte families", "{{NAME}}, OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} is exactly what we're all about: {{VOLUNTEER_COUNT}} volunteers at {{DRIVE_LOCATION}}, {{KITS_COLLECTED}} hygiene kits packed with care, distributed to Charlotte families through Crisis Assistance Ministry.", "This is OLI. Thank you for being part of what OLI is all about. 💜", "Be Part of OLI →"),
]

out = [{"id": f"postdrive-{i+1:03d}", "subject": t[0], "body": mkb(t[1], t[2], t[3], t[4], *(t[5:6] or ["See What's Next →"]))} for i, t in enumerate(T)]
path = os.path.join(os.path.dirname(__file__), "postdrive.json")
with open(path, "w", encoding="utf-8") as f:
    json.dump(out, f, indent=2, ensure_ascii=False)
print(f"Wrote {len(out)} post-drive templates to {path}")
