import json, os

H = "<div style='font-family:Montserrat,Arial,sans-serif;max-width:600px;margin:0 auto;background:#f5f5f0;'><div style='background:linear-gradient(135deg,#7B5CF5,#9B7FF5);padding:28px 36px;text-align:center;'><img src='https://raw.githubusercontent.com/privi-doughnut/oneloveinitiative/main/OLI_LOGO.jpg' alt='OLI' style='width:64px;height:64px;border-radius:50%;object-fit:cover;border:3px solid rgba(255,255,255,0.3);'/><h1 style='color:#fff;font-size:18px;font-weight:800;margin:8px 0 0;letter-spacing:0.07em;'>ONE LOVE INITIATIVE</h1><p style='color:rgba(255,255,255,0.8);font-size:10px;margin:3px 0 0;letter-spacing:0.14em;text-transform:uppercase;'>Charlotte, NC &middot; Student-Led Nonprofit</p></div>"
F = "<div style='padding:16px 24px;background:#f5f5f0;text-align:center;border-top:1px solid #eee;'><p style='font-size:11px;color:#aaa;margin:0;'>2025 OLI &middot; <a href='https://oneloveinitative.org' style='color:#7B5CF5;text-decoration:none;'>Website</a> &middot; <a href='https://www.instagram.com/one.love.initiative/' style='color:#7B5CF5;text-decoration:none;'>Instagram</a> &middot; <a href='{{UNSUBSCRIBE_URL}}' style='color:#aaa;text-decoration:none;'>Unsubscribe</a></p></div></div>"

COUNTDOWN = ("<div style='background:linear-gradient(135deg,#7B5CF5,#9B7FF5);border-radius:8px;padding:20px;margin:20px 0;text-align:center;'>"
    "<p style='color:rgba(255,255,255,0.8);font-size:10px;letter-spacing:0.15em;text-transform:uppercase;margin:0 0 6px;font-weight:600;'>Drive Details</p>"
    "<p style='color:#fff;font-size:16px;font-weight:800;margin:0 0 4px;'>{{DRIVE_NAME}}</p>"
    "<p style='color:rgba(255,255,255,0.9);font-size:13px;margin:0 0 4px;'>📅 {{DRIVE_DATE}}</p>"
    "<p style='color:rgba(255,255,255,0.9);font-size:13px;margin:0;'>📍 {{DRIVE_LOCATION}}</p>"
    "</div>")

def mkb(hl, sub, p1, p2, cta="Sign Up to Volunteer →", sg="The OLI Team"):
    return (H +
        "<div style='background:#fff;padding:32px 36px;'>"
        "<p style='color:#7B5CF5;font-size:10px;letter-spacing:0.15em;text-transform:uppercase;margin:0 0 8px;font-weight:600;'>Upcoming Drive</p>"
        "<h2 style='color:#333;font-size:22px;font-weight:800;margin:0 0 5px;line-height:1.3;'>" + hl + "</h2>"
        "<p style='color:#999;font-size:12px;font-style:italic;margin:0 0 18px;'>" + sub + "</p>"
        "<p style='color:#444;font-size:14px;line-height:1.7;margin:0 0 12px;'>" + p1 + "</p>"
        + COUNTDOWN +
        "<p style='color:#444;font-size:14px;line-height:1.7;margin:0 0 24px;'>" + p2 + "</p>"
        "<div style='text-align:center;'><a href='https://oneloveinitative.org' style='background:#7B5CF5;color:#fff;padding:11px 26px;border-radius:5px;font-size:13px;font-weight:700;text-decoration:none;'>" + cta + "</a></div>"
        "<p style='color:#888;font-size:12px;margin:22px 0 0;'>With love, <strong style='color:#7B5CF5;'>" + sg + "</strong></p>"
        "</div>" + F)

# (subject, headline, sub, p1, p2, cta)
T = [
    ("OLI Drive Alert: {{DRIVE_NAME}} is coming! 🚨", "{{DRIVE_NAME}} — it's happening! 🚨", "Mark your calendar right now", "{{NAME}}, OLI's next kit drive is official: {{DRIVE_NAME}}. We're gathering volunteers, collecting hygiene supplies, and packing kits for Charlotte families through Crisis Assistance Ministry. This is your invitation to be part of it.", "We need people who show up. Volunteers, donors, and supporters. Can we count on you? Details below. 💜", "Sign Up to Volunteer →"),
    ("{{DRIVE_NAME}} — volunteers needed! 🙋", "We need you at {{DRIVE_NAME}} 🙋", "One drive. Big impact. Your spot is open.", "{{NAME}}, OLI's {{DRIVE_NAME}} is on the calendar — and we're looking for volunteers who want to show up and make it count. This is a hands-on kit-packing event that makes a direct difference for Charlotte families.", "Every volunteer hour means more kits packed, more kids with hygiene supplies, and more Charlotte families supported through Crisis Assistance Ministry. Let's do this. 💜", "Claim Your Spot →"),
    ("Something big is coming from OLI 💜", "Something big is coming — {{DRIVE_NAME}} 💜", "And we need you in the room when it happens", "{{NAME}}, OLI is planning something big: {{DRIVE_NAME}}, a community kit drive to pack hygiene kits for Charlotte children and families. Student volunteers, community support, and real impact through Crisis Assistance Ministry.", "Your spot at this drive matters. Every pair of hands means more kits. More kits means more families served. Will you be there? 💜", "Reserve My Spot →"),
    ("Save the date: OLI {{DRIVE_NAME}} 📅", "Save the date — OLI {{DRIVE_NAME}} 📅", "The details are in. Your calendar is waiting.", "{{NAME}}, save the date — OLI's {{DRIVE_NAME}} is officially scheduled. We'll be gathering at {{DRIVE_LOCATION}} on {{DRIVE_DATE}} to pack hygiene kits for Charlotte families distributed through Crisis Assistance Ministry.", "We'd love to see you there. Whether you volunteer your time or spread the word — every action counts. Here are the full details. 💜", "Add to My Calendar →"),
    ("OLI is hosting {{DRIVE_NAME}} — will you join us? 💜", "Join us for {{DRIVE_NAME}} 💜", "A community drive that changes real lives", "{{NAME}}, OLI is hosting {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}}. We'll be packing children's hygiene kits — toothbrush, toothpaste, soap, lotion — for distribution to Charlotte families through Crisis Assistance Ministry.", "This is community action in the most direct form. Join us and pack a kit. 💜", "Join the Drive →"),
    ("Calling all volunteers — OLI {{DRIVE_NAME}} 📢", "Calling all volunteers for {{DRIVE_NAME}} 📢", "Your community needs you on {{DRIVE_DATE}}", "{{NAME}}, OLI is sending out the call: we need volunteers for {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}}. If you've ever wanted to do something real for Charlotte, this is it — show up, pack kits, make an impact.", "No experience needed. Just your time, your energy, and your heart. Through Crisis Assistance Ministry, the kits reach families who need them most. 💜", "Answer the Call →"),
    ("{{NAME}}, you're invited to OLI {{DRIVE_NAME}} 🎉", "You're officially invited — {{DRIVE_NAME}} 🎉", "Your presence would mean everything", "{{NAME}}, consider this your personal invitation to OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}}. We're packing hygiene kits — toothbrush, toothpaste, soap, lotion — for Charlotte children in need.", "Your presence matters. Every volunteer makes it possible to reach more families through Crisis Assistance Ministry. We'd be honored to have you. 💜", "Accept the Invitation →"),
    ("OLI {{DRIVE_NAME}}: let's pack 1,000 kits 🎯", "Let's pack 1,000 kits at {{DRIVE_NAME}} 🎯", "Big goals need big community — that means you", "{{NAME}}, OLI is setting a goal for {{DRIVE_NAME}}: as many kits as our volunteer crew can pack. Every kit is a child's toothbrush, toothpaste, soap, and lotion. Every kit matters to a Charlotte family receiving it through Crisis Assistance Ministry.", "The bigger our volunteer crew on {{DRIVE_DATE}} at {{DRIVE_LOCATION}}, the more kits we pack. Will you help us hit our goal? 💜", "Help Hit the Goal →"),
    ("Get ready — OLI {{DRIVE_NAME}} is almost here! ⏳", "Get ready — {{DRIVE_NAME}} is almost here! ⏳", "The countdown is on. Your spot is open.", "{{NAME}}, {{DRIVE_NAME}} is just around the corner — {{DRIVE_DATE}} at {{DRIVE_LOCATION}}. OLI is gearing up to pack hygiene kits for Charlotte families through Crisis Assistance Ministry, and we'd love for you to be there.", "Whether you're a returning OLI volunteer or brand new — welcome. Your time is the most valuable thing you can give. 💜", "Get Ready →"),
    ("One week until OLI {{DRIVE_NAME}}! 🗓️", "One week until {{DRIVE_NAME}}! 🗓️", "Are you registered? Here's everything you need to know.", "{{NAME}}, one week from today is OLI's {{DRIVE_NAME}} — {{DRIVE_DATE}} at {{DRIVE_LOCATION}}. We're counting down, checking volunteer registrations, and making sure everything is ready for a great kit-packing day.", "Not signed up yet? There's still time. Signed up? Share this with one friend. Double the volunteers = double the kits for Charlotte families through Crisis Assistance Ministry. 💜", "Share With a Friend →"),
    ("{{DRIVE_NAME}} prep starts now 🔧", "Prep starts now — {{DRIVE_NAME}} 🔧", "What to know before you show up", "{{NAME}}, OLI's {{DRIVE_NAME}} is on {{DRIVE_DATE}} at {{DRIVE_LOCATION}}, and prep starts now. Here's what you need to know: show up ready to pack kits, bring a friend, and leave knowing you made a difference for Charlotte families.", "Through Crisis Assistance Ministry, every kit you pack reaches a real family. Prep is simple — showing up is everything. 💜", "I'm Showing Up →"),
    ("OLI drive incoming — {{DRIVE_NAME}} 📦", "Drive incoming — {{DRIVE_NAME}} 📦", "Hygiene kits for Charlotte. Student-led. Community-powered.", "{{NAME}}, OLI's next drive is incoming: {{DRIVE_NAME}}, happening {{DRIVE_DATE}} at {{DRIVE_LOCATION}}. We'll pack children's hygiene kits — the kind of essential supplies that families in our community too often go without.", "Kits get distributed to Charlotte families through Crisis Assistance Ministry. Your hour of volunteering = real kits in real hands. 💜", "Pack Kits With Us →"),
    ("Don't miss OLI {{DRIVE_NAME}} 🚫⏰", "Don't miss {{DRIVE_NAME}} 🚫⏰", "This one is special — you'll want to be there", "{{NAME}}, mark it, set an alarm, tell a friend — OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is not one to miss. We're packing hygiene kits for Charlotte children through Crisis Assistance Ministry.", "We've had volunteers tell us kit drives are some of their favorite memories. Come make yours. 💜", "Set the Reminder →"),
    ("OLI is coming to {{DRIVE_LOCATION}} — {{DRIVE_DATE}} 📍", "OLI is coming to {{DRIVE_LOCATION}} 📍", "And we want you to be there when we arrive", "{{NAME}}, OLI is bringing the mission to {{DRIVE_LOCATION}} on {{DRIVE_DATE}}. {{DRIVE_NAME}} is our next kit drive — packing children's hygiene kits for Charlotte families distributed through Crisis Assistance Ministry.", "This is your chance to get involved in person, with your hands, making something real happen for your community. 💜", "Be There →"),
    ("Big things are happening at OLI — {{DRIVE_NAME}} 🌟", "Big things are happening — {{DRIVE_NAME}} 🌟", "And you're invited to be part of them", "{{NAME}}, big things are happening at OLI: {{DRIVE_NAME}} is scheduled for {{DRIVE_DATE}} at {{DRIVE_LOCATION}}. We're gathering our community to pack hygiene kits that will reach Charlotte families through Crisis Assistance Ministry.", "This is one of those moments. You can look back and say you were part of it. 💜", "Be Part of It →"),
    ("OLI needs your help for {{DRIVE_NAME}} 🤝", "We need your help for {{DRIVE_NAME}} 🤝", "No grand gesture — just show up", "{{NAME}}, OLI needs your help — and it's simple. Show up at {{DRIVE_LOCATION}} on {{DRIVE_DATE}} for {{DRIVE_NAME}}, help pack hygiene kits, and know that your time reaches Charlotte families through Crisis Assistance Ministry.", "No skills required. No prior experience needed. Just you, your energy, and a willingness to serve. 💜", "I'll Help →"),
    ("Volunteer at OLI {{DRIVE_NAME}} this {{DRIVE_DATE}} 💜", "Volunteer at {{DRIVE_NAME}} — {{DRIVE_DATE}} 💜", "An afternoon that changes Charlotte. And maybe you.", "{{NAME}}, OLI's {{DRIVE_NAME}} is {{DRIVE_DATE}} at {{DRIVE_LOCATION}}. Volunteer for an afternoon and help pack children's hygiene kits for Charlotte families distributed through Crisis Assistance Ministry.", "The volunteers who show up to OLI drives often come back — because they feel the impact. We'd love to have you experience that. 💜", "Volunteer Now →"),
    ("OLI {{DRIVE_NAME}}: packing kits for Charlotte 🏙️", "Packing kits for Charlotte — {{DRIVE_NAME}} 🏙️", "This city takes care of its own. Help us prove it.", "{{NAME}}, OLI is proving that Charlotte takes care of its own — and {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is the next proof point. We'll pack hygiene kits for children and families in our community.", "Crisis Assistance Ministry gets the kits where they need to go. You provide the hands that pack them. 💜", "Pack for Charlotte →"),
    ("The mission continues — OLI {{DRIVE_NAME}} is here 💜", "The mission continues — {{DRIVE_NAME}} 💜", "Every drive is a new chapter", "{{NAME}}, the OLI mission never stops — and {{DRIVE_NAME}} is the next chapter. {{DRIVE_DATE}} at {{DRIVE_LOCATION}}, we'll add more hygiene kits for Charlotte families to the story we're writing together.", "Each chapter is better than the last when more people show up. Join us. 💜", "Write the Next Chapter →"),
    ("Charlotte families need these kits — OLI {{DRIVE_NAME}} 💜", "Charlotte families need these kits 💜", "And we need you to help pack them", "{{NAME}}, Charlotte families — real ones, in our community — need hygiene kits. OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is how we meet that need, through Crisis Assistance Ministry distribution.", "Every volunteer pair of hands means more kits. More kits means more families helped. Help us help them. 💜", "Help Pack Kits →"),
    ("OLI {{DRIVE_NAME}} — community, kits, and love 💜", "Community, kits, and love — {{DRIVE_NAME}} 💜", "Everything OLI stands for, in one event", "{{NAME}}, OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is everything we stand for: community coming together, kits being packed with care, and love flowing from Charlotte students to Charlotte families.", "Crisis Assistance Ministry gets the kits to those families. You make it possible by showing up. 💜", "Show Up →"),
    ("Last chance to join OLI {{DRIVE_NAME}} ⚡", "Last chance — join {{DRIVE_NAME}} ⚡", "Spots are filling up. Don't miss out.", "{{NAME}}, OLI's {{DRIVE_NAME}} is almost full — and we'd hate for you to miss it. {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is when we pack hygiene kits for Charlotte families through Crisis Assistance Ministry.", "Last chance to claim your spot. Once volunteers max out, we can't take more. Don't be the one who missed it. ⚡", "Claim My Spot Now →"),
    ("OLI {{DRIVE_NAME}}: pack. serve. impact. 💜", "Pack. Serve. Impact. — {{DRIVE_NAME}} 💜", "Three words that describe one great afternoon", "{{NAME}}, OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is simple: you pack, you serve, and you create impact. Children's hygiene kits assembled by student and community volunteers, reaching Charlotte families through Crisis Assistance Ministry.", "Pack. Serve. Impact. Three things you can do on {{DRIVE_DATE}}. We hope to see you there. 💜", "Pack. Serve. Impact. →"),
    ("Students + community = OLI {{DRIVE_NAME}} 🤝", "Students + community = {{DRIVE_NAME}} 🤝", "The equation that's changing Charlotte", "{{NAME}}, OLI's equation is simple: student volunteers + community support = hygiene kits for Charlotte families. {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is that equation in action.", "Through Crisis Assistance Ministry, the kits reach families across our community. Add yourself to the equation. 💜", "Add Myself →"),
    ("OLI {{DRIVE_NAME}}: every kit starts with you 💜", "Every kit starts with you — {{DRIVE_NAME}} 💜", "Literal truth: without volunteers, no kits", "{{NAME}}, here's the literal truth: OLI kits don't pack themselves. Every hygiene kit for a Charlotte family starts with a volunteer's hands. {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is where those hands show up.", "Be the start of something good. Be the hands behind a kit. Through Crisis Assistance Ministry, it reaches someone who needs it. 💜", "Be the Start →"),
    ("OLI {{DRIVE_NAME}}: your 2 hours = real impact 🕐", "Your 2 hours = real impact — {{DRIVE_NAME}} 🕐", "The math on volunteering has never looked better", "{{NAME}}, two hours of your time at OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} equals hygiene kits for Charlotte children, distributed through Crisis Assistance Ministry to families who need them.", "Two hours. Real kits. Real families. Real Charlotte impact. The math is simple. The impact is not. 💜", "Give 2 Hours →"),
    ("OLI {{DRIVE_NAME}}: be on the right side of history 📖", "Be on the right side of history — {{DRIVE_NAME}} 📖", "The students who showed up will always remember it", "{{NAME}}, OLI students who volunteer at drives talk about it for months afterward. {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is one of those moments — the kind that stays with you.", "Charlotte families receive the kits through Crisis Assistance Ministry. You receive something too: the knowledge that you showed up when it mattered. 💜", "Show Up →"),
    ("Bring a friend to OLI {{DRIVE_NAME}} 👯", "Bring a friend — {{DRIVE_NAME}} 👯", "Better together. Always.", "{{NAME}}, OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is better with company. Bring a friend, a sibling, a classmate — whoever will join you in packing hygiene kits for Charlotte families through Crisis Assistance Ministry.", "Double the friends = double the fun = double the kits. Bring someone. Make it a memory. 💜", "Bring a Friend →"),
    ("OLI {{DRIVE_NAME}}: the drive that matters 💜", "The drive that matters — {{DRIVE_NAME}} 💜", "Not all drives are created equal. This one counts.", "{{NAME}}, OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} matters — because the hygiene kits packed there reach Charlotte children who need them through Crisis Assistance Ministry. Every drive matters. This one too.", "Show up for the drive that matters. Volunteer, donate items, or spread the word. All of it counts. 💜", "Make It Matter →"),
    ("OLI {{DRIVE_NAME}}: see you at {{DRIVE_LOCATION}} 💜", "See you at {{DRIVE_LOCATION}} — {{DRIVE_NAME}} 💜", "We're already looking forward to seeing you there", "{{NAME}}, OLI's {{DRIVE_NAME}} is locked in: {{DRIVE_DATE}} at {{DRIVE_LOCATION}}. We're packing hygiene kits for Charlotte families through Crisis Assistance Ministry, and we're looking forward to seeing you there.", "If you're in — let us know and share with a friend. If you're on the fence — this is your sign to say yes. 💜", "I'm In →"),
    ("OLI {{DRIVE_NAME}}: it all starts this {{DRIVE_DATE}} 🚀", "It all starts {{DRIVE_DATE}} — {{DRIVE_NAME}} 🚀", "The beginning of something great", "{{NAME}}, it all starts on {{DRIVE_DATE}} — OLI's {{DRIVE_NAME}} at {{DRIVE_LOCATION}}. Volunteers assemble. Kits get packed. Charlotte families receive hygiene supplies through Crisis Assistance Ministry. It all starts with showing up.", "The beginning of great things requires people willing to show up at the start. Are you one of those people? 💜", "Start Something Great →"),
    ("OLI is hosting a drive — are you in? 💜", "OLI is hosting a drive — are you in? 💜", "{{DRIVE_NAME}} — {{DRIVE_DATE}} — {{DRIVE_LOCATION}}", "{{NAME}}, OLI is hosting {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}}. We need volunteers to pack hygiene kits — toothbrush, toothpaste, soap, lotion — for Charlotte children distributed through Crisis Assistance Ministry.", "Are you in? One word. One click. One afternoon that makes a real difference. Are you in? 💜", "I'm In →"),
    ("Real impact. Real kits. OLI {{DRIVE_NAME}} 💜", "Real impact. Real kits. {{DRIVE_NAME}} 💜", "Not hypothetical impact — actual, physical kits", "{{NAME}}, OLI's impact is not hypothetical — it's physical. Actual kits, with actual toothbrushes, toothpaste, soap, and lotion, reaching actual Charlotte families through Crisis Assistance Ministry. {{DRIVE_NAME}} makes more of those kits happen.", "Join us on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} and make something real. 💜", "Make Something Real →"),
    ("OLI {{DRIVE_NAME}}: powered by people like you 💜", "Powered by people like you — {{DRIVE_NAME}} 💜", "The secret ingredient in every OLI kit", "{{NAME}}, the secret ingredient in every OLI kit is people — people like you who show up, care, and act. {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} needs that secret ingredient.", "Without people, no kits. Without kits, no families helped. Without you — the equation is incomplete. Be part of it. 💜", "Be the Secret Ingredient →"),
    ("OLI {{DRIVE_NAME}}: a morning/afternoon well spent 🌅", "A morning well spent — {{DRIVE_NAME}} 🌅", "Because some ways of spending time feel exactly right", "{{NAME}}, some ways of spending time just feel right — and volunteering at OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is one of them. Packing hygiene kits for Charlotte families. Laughing with other volunteers. Knowing you did something good.", "Crisis Assistance Ministry gets those kits to the families. You get the knowledge that you spent your time exactly right. 💜", "Spend Time Right →"),
    ("OLI {{DRIVE_NAME}} — spread the word! 📣", "Spread the word — {{DRIVE_NAME}} 📣", "The more people who know, the more kits we pack", "{{NAME}}, OLI's {{DRIVE_NAME}} is on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} — and we need your help spreading the word. The more volunteers we have, the more hygiene kits we pack, the more Charlotte families we serve through Crisis Assistance Ministry.", "Share this. Tag a friend. Post it. Tell people. Spread the word and multiply the impact. 💜", "Share With Friends →"),
    ("OLI {{DRIVE_NAME}}: a chance to serve Charlotte 💜", "A chance to serve Charlotte — {{DRIVE_NAME}} 💜", "Service is a gift you give your community", "{{NAME}}, service is one of the greatest things you can give your community — and OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is your next chance to do just that. Pack kits. Serve Charlotte.", "Every kit packed serves a Charlotte family through Crisis Assistance Ministry. Your service makes it possible. 💜", "Serve Charlotte →"),
    ("OLI's biggest drive yet — {{DRIVE_NAME}} 🏆", "Our biggest drive yet — {{DRIVE_NAME}} 🏆", "We're aiming higher this time. Help us get there.", "{{NAME}}, OLI is aiming for our biggest {{DRIVE_NAME}} yet — on {{DRIVE_DATE}} at {{DRIVE_LOCATION}}. More volunteers, more hygiene kits, more Charlotte families served through Crisis Assistance Ministry.", "Help us make it the biggest one yet. Sign up, bring friends, and show up ready to pack. 💜", "Make It the Biggest →"),
    ("OLI {{DRIVE_NAME}}: everyone is welcome 💜", "Everyone is welcome — {{DRIVE_NAME}} 💜", "You don't need to be a student. You just need to care.", "{{NAME}}, OLI welcomes everyone at {{DRIVE_NAME}} — students, adults, families, first-timers, and OLI regulars. If you care about Charlotte families having hygiene essentials, you belong at this drive.", "{{DRIVE_DATE}} at {{DRIVE_LOCATION}}. Everyone welcome. Hygiene kits for Charlotte families through Crisis Assistance Ministry. See you there. 💜", "Come as You Are →"),
    ("OLI {{DRIVE_NAME}} is almost here — are you ready? 💜", "Almost here — are you ready for {{DRIVE_NAME}}? 💜", "Prep, pack, and show up ready to make an impact", "{{NAME}}, OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is almost here. Here's how to prepare: bring your energy, bring a friend if you can, and show up ready to pack hygiene kits for Charlotte families.", "Everything else you need to know will be there. Crisis Assistance Ministry takes it from there. You just have to show up ready. 💜", "I'm Ready →"),
    ("Donate items for OLI {{DRIVE_NAME}} 🎁", "Donate items for {{DRIVE_NAME}} 🎁", "We need toothbrushes, toothpaste, soap, and lotion", "{{NAME}}, OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} runs on donated supplies — kids toothbrushes, kids toothpaste, kid-friendly soap, and kid-friendly lotion. If you can't volunteer your time, consider donating items.", "Every item donated is an item in a kit for a Charlotte child through Crisis Assistance Ministry. Donate items, volunteer time, or spread the word. All of it helps. 🎁", "Donate Items →"),
    ("OLI {{DRIVE_NAME}}: join the student-led mission 💜", "Join the student-led mission — {{DRIVE_NAME}} 💜", "A nonprofit run by students, powered by community", "{{NAME}}, OLI is entirely student-led — founded and run by young people who believe Charlotte should take care of its own. {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is that belief in action.", "Join the mission on {{DRIVE_DATE}}. Volunteer alongside students making a difference. Help Charlotte families through Crisis Assistance Ministry. 💜", "Join the Mission →"),
    ("OLI {{DRIVE_NAME}}: kits for kids 🧒", "Kits for kids — {{DRIVE_NAME}} 🧒", "Because every child deserves basic hygiene supplies", "{{NAME}}, every kit OLI packs goes to a child — a real Charlotte kid who deserves the basic hygiene supplies that too many families can't afford. {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is how we get those kits packed.", "Through Crisis Assistance Ministry, those kits reach the kids who need them most. Be part of that. 🧒", "Pack for Kids →"),
    ("OLI {{DRIVE_NAME}}: make a difference on {{DRIVE_DATE}} 💜", "Make a difference on {{DRIVE_DATE}} — {{DRIVE_NAME}} 💜", "Some days are different. This one can be yours.", "{{NAME}}, some days are just different — and {{DRIVE_DATE}} can be one of those for you. OLI's {{DRIVE_NAME}} at {{DRIVE_LOCATION}} is a chance to make a measurable difference for Charlotte families through Crisis Assistance Ministry.", "Show up. Pack kits. Leave knowing that day mattered. 💜", "Make {{DRIVE_DATE}} Different →"),
    ("OLI {{DRIVE_NAME}} prep: what to bring 🎒", "What to bring to {{DRIVE_NAME}} 🎒", "Everything you need to know before you arrive", "{{NAME}}, before you arrive at OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}}, here's what to bring: yourself, your energy, and a willingness to serve Charlotte families. Everything else will be there.", "Optional extras: bring a friend, bring extra item donations, bring good vibes. The kits you pack get to Charlotte families through Crisis Assistance Ministry. 🎒", "I'm Coming →"),
    ("This is your sign to volunteer — OLI {{DRIVE_NAME}} 🌟", "This is your sign to volunteer 🌟", "You've been looking for a reason. Here it is.", "{{NAME}}, if you've been looking for a reason to get involved with OLI, here it is: {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}}. Pack hygiene kits for Charlotte children, served through Crisis Assistance Ministry.", "You've been waiting for your sign. This is it. See you on {{DRIVE_DATE}}. 🌟", "This Is My Sign →"),
    ("OLI {{DRIVE_NAME}}: help us prepare Charlotte's kids 💜", "Help us prepare Charlotte's kids — {{DRIVE_NAME}} 💜", "Hygiene kits that change a child's daily life", "{{NAME}}, basic hygiene changes everything for a child — the confidence of a clean mouth, the comfort of fresh skin. OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} packs exactly that for Charlotte kids through Crisis Assistance Ministry.", "Help prepare Charlotte's kids. Pack a kit. Show up on {{DRIVE_DATE}}. 💜", "Prepare Charlotte's Kids →"),
    ("OLI's next chapter — {{DRIVE_NAME}} 📖", "The next chapter — {{DRIVE_NAME}} 📖", "OLI's story keeps getting better", "{{NAME}}, OLI's story is built chapter by chapter — each drive a new page, each kit a new sentence. {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is the next chapter, and we'd love for you to help write it.", "The kits reach Charlotte families through Crisis Assistance Ministry. You help write the chapter. 📖", "Write the Chapter →"),
    ("OLI {{DRIVE_NAME}}: come pack kits with us 💜", "Come pack kits with us — {{DRIVE_NAME}} 💜", "It's simple. It's meaningful. You'll love it.", "{{NAME}}, packing kits at OLI is simple — sort toothbrushes, toothpaste, soap, and lotion into bags — and remarkably meaningful. {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is your next chance to experience it.", "The kits reach Charlotte families through Crisis Assistance Ministry. You leave with a full heart. Come pack with us. 💜", "Pack With Us →"),
    ("OLI {{DRIVE_NAME}} — do something good on {{DRIVE_DATE}} 💜", "Do something good on {{DRIVE_DATE}} 💜", "An afternoon of action for Charlotte", "{{NAME}}, {{DRIVE_DATE}} is coming up — and OLI has the perfect plan: {{DRIVE_NAME}} at {{DRIVE_LOCATION}}, packing hygiene kits for Charlotte children distributed through Crisis Assistance Ministry. Do something good on {{DRIVE_DATE}}.", "It's a simple formula: show up, pack kits, do something good. That good reaches Charlotte families. 💜", "Do Something Good →"),
    ("OLI {{DRIVE_NAME}}: the countdown is on ⏱️", "The countdown is on — {{DRIVE_NAME}} ⏱️", "Every passing day is one closer to making a difference", "{{NAME}}, the countdown to OLI's {{DRIVE_NAME}} is officially on. {{DRIVE_DATE}} at {{DRIVE_LOCATION}} — that's when we pack hygiene kits for Charlotte families through Crisis Assistance Ministry.", "Every day closer is a day closer to making a difference. The countdown ends on {{DRIVE_DATE}}. Are you ready? ⏱️", "Start Counting Down →"),
    ("Charlotte is counting on OLI {{DRIVE_NAME}} 💜", "Charlotte is counting on {{DRIVE_NAME}} 💜", "And OLI is counting on people like you", "{{NAME}}, Charlotte families are counting on OLI to deliver hygiene kits through Crisis Assistance Ministry — and OLI is counting on volunteers like you to show up for {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}}.", "The chain of care runs from you to us to Crisis Assistance Ministry to Charlotte families. Don't break the chain. 💜", "Keep the Chain Going →"),
    ("OLI {{DRIVE_NAME}}: one event, lasting impact 💜", "One event, lasting impact — {{DRIVE_NAME}} 💜", "What happens on {{DRIVE_DATE}} matters beyond {{DRIVE_DATE}}", "{{NAME}}, OLI's {{DRIVE_NAME}} happens on {{DRIVE_DATE}} at {{DRIVE_LOCATION}}, but its impact lasts far beyond that day. The hygiene kits packed reach Charlotte families through Crisis Assistance Ministry over weeks and months.", "One event. Lasting impact. Be part of it on {{DRIVE_DATE}}. 💜", "Create Lasting Impact →"),
    ("OLI {{DRIVE_NAME}}: service with a smile 😊", "Service with a smile — {{DRIVE_NAME}} 😊", "The best volunteering feels like joy, not obligation", "{{NAME}}, the best thing about OLI kit drives? The people. Volunteers who show up happy, laugh while packing, and leave knowing they did something real. {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is that experience.", "Charlotte families receive the kits through Crisis Assistance Ministry. You receive the experience of service with a smile. 😊", "Smile and Serve →"),
    ("Volunteer at OLI {{DRIVE_NAME}} — no experience needed 💜", "No experience needed — just show up to {{DRIVE_NAME}} 💜", "First time? Perfect. We'll take care of the rest.", "{{NAME}}, never volunteered with OLI before? Perfect — {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is a great first time. No experience needed, no prior knowledge required. We'll walk you through everything.", "You pack the kits. Crisis Assistance Ministry gets them to Charlotte families. First-timers are some of our favorite volunteers. 💜", "Try It for the First Time →"),
    ("OLI {{DRIVE_NAME}}: every hour counts 🕐", "Every hour counts — {{DRIVE_NAME}} 🕐", "We're not asking for much. Just an hour or two.", "{{NAME}}, OLI isn't asking for a major commitment — just an hour or two at {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}}. In that time, you can help pack dozens of hygiene kits for Charlotte families through Crisis Assistance Ministry.", "Every hour you give counts. Even one. Even two. See you on {{DRIVE_DATE}}. 🕐", "Give an Hour →"),
    ("OLI is ready for {{DRIVE_NAME}} — are you? 💜", "OLI is ready for {{DRIVE_NAME}} — are you? 💜", "Supplies sourced. Volunteers coordinating. We need you.", "{{NAME}}, OLI is in full prep mode for {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}}. Supplies sourced. Logistics coordinated. Kits ready to be packed. The only thing missing is you.", "Crisis Assistance Ministry is ready to distribute the kits to Charlotte families. We're ready to pack. Are you ready to join us? 💜", "I'm Ready →"),
    ("OLI {{DRIVE_NAME}}: fill a kit, change a life 💜", "Fill a kit, change a life — {{DRIVE_NAME}} 💜", "It sounds simple because it is", "{{NAME}}, it's simple: at OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}}, you fill a hygiene kit — toothbrush, toothpaste, soap, lotion — and that kit reaches a Charlotte child through Crisis Assistance Ministry.", "Fill a kit. Change a life. Two things you can do on {{DRIVE_DATE}}. 💜", "Fill a Kit →"),
    ("OLI {{DRIVE_NAME}}: you make the kits possible 💜", "You make the kits possible — {{DRIVE_NAME}} 💜", "Without community support, there are no kits", "{{NAME}}, OLI kits don't happen without community — without volunteers who show up, donors who give, and supporters who spread the word. {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} depends on people like you.", "Charlotte families receive the kits through Crisis Assistance Ministry. You make that possible. Thank you in advance. 💜", "Make It Possible →"),
    ("OLI {{DRIVE_NAME}}: the drive that gives back 🔄", "The drive that gives back — {{DRIVE_NAME}} 🔄", "What you give multiplies on the way to Charlotte families", "{{NAME}}, what you give at OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} — your time, energy, donated items — multiplies before it reaches Charlotte families through Crisis Assistance Ministry.", "A few hours of your time = dozens of kits = dozens of families with hygiene essentials. The give-back is real. 🔄", "Give and Get Back →"),
    ("OLI {{DRIVE_NAME}}: be the change, Charlotte 💜", "Be the change, Charlotte — {{DRIVE_NAME}} 💜", "The change Charlotte needs starts at this drive", "{{NAME}}, Charlotte can be a place where every family has access to basic hygiene — and OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is how we build that reality, one kit at a time through Crisis Assistance Ministry.", "Be the change Charlotte needs. Show up on {{DRIVE_DATE}}. 💜", "Be the Change →"),
    ("OLI {{DRIVE_NAME}}: your community needs you 🏘️", "Your community needs you — {{DRIVE_NAME}} 🏘️", "Charlotte takes care of its own. Be part of that.", "{{NAME}}, Charlotte takes care of its own — and OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is one of the ways that happens. Hygiene kits packed by community volunteers, reaching families through Crisis Assistance Ministry.", "Your community needs you on {{DRIVE_DATE}}. Show up. 🏘️", "Show Up for Community →"),
    ("OLI {{DRIVE_NAME}}: student heart, community hands 💜", "Student heart, community hands — {{DRIVE_NAME}} 💜", "The best nonprofits combine both", "{{NAME}}, OLI has the student heart — the passion, the mission, the why. What makes us great is the community hands that join us. {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is where those hands show up.", "Together, student heart + community hands = hygiene kits for Charlotte families through Crisis Assistance Ministry. Be the hands. 💜", "Be the Hands →"),
    ("OLI {{DRIVE_NAME}}: here's why it matters 💜", "Here's why {{DRIVE_NAME}} matters 💜", "The case for showing up on {{DRIVE_DATE}}", "{{NAME}}, here's why OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} matters: Charlotte families lack access to basic hygiene supplies. Students and community members can change that. Crisis Assistance Ministry connects the effort to the need.", "That's the case. That's why it matters. That's why we hope to see you on {{DRIVE_DATE}}. 💜", "I Understand Why →"),
    ("OLI {{DRIVE_NAME}}: together we go further 💜", "Together we go further — {{DRIVE_NAME}} 💜", "The math of community is multiplicative, not additive", "{{NAME}}, OLI's community math: one volunteer packs more than they think. Ten volunteers pack exponentially more. A full community at {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} means kits for dozens of Charlotte families.", "Together we go further — through Crisis Assistance Ministry, we go further than we could alone. Come further with us. 💜", "Go Further Together →"),
    ("OLI {{DRIVE_NAME}}: mark the date ✅", "Mark the date — {{DRIVE_NAME}} ✅", "{{DRIVE_DATE}}. {{DRIVE_LOCATION}}. Be there.", "{{NAME}}, put it in your calendar, set an alarm, write it on your hand — OLI's {{DRIVE_NAME}} is {{DRIVE_DATE}} at {{DRIVE_LOCATION}}. We're packing hygiene kits for Charlotte families through Crisis Assistance Ministry.", "Marked? Good. Now bring a friend. ✅ 💜", "Mark My Calendar →"),
    ("OLI {{DRIVE_NAME}}: the Charlotte drive 🏙️", "The Charlotte drive — {{DRIVE_NAME}} 🏙️", "By Charlotte students, for Charlotte families", "{{NAME}}, OLI's {{DRIVE_NAME}} is a Charlotte drive through and through: organized by Charlotte students, volunteered by Charlotte community members, and benefiting Charlotte families through Crisis Assistance Ministry distribution.", "{{DRIVE_DATE}} at {{DRIVE_LOCATION}}. By Charlotte. For Charlotte. 🏙️ 💜", "Support Charlotte →"),
    ("OLI {{DRIVE_NAME}} — don't let it pass you by 💜", "Don't let {{DRIVE_NAME}} pass you by 💜", "This one is worth showing up for", "{{NAME}}, there are events worth clearing your schedule for — and OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is one of them. Packing kits for Charlotte families through Crisis Assistance Ministry is exactly that kind of thing.", "Don't let it pass you by. Show up. Pack kits. Leave proud. 💜", "Don't Miss It →"),
    ("OLI {{DRIVE_NAME}}: action over talk 🔥", "Action over talk — {{DRIVE_NAME}} 🔥", "OLI believes in kits, not just conversations", "{{NAME}}, OLI believes in action over talk — and {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is action. Hygiene kits packed by real people, reaching real Charlotte families through Crisis Assistance Ministry. Not talk. Kits.", "Come for the action. Stay for the impact. See you on {{DRIVE_DATE}}. 🔥", "Take Action →"),
    ("OLI {{DRIVE_NAME}}: a drive built on love 💜", "A drive built on love — {{DRIVE_NAME}} 💜", "One Love Initiative takes the name seriously", "{{NAME}}, One Love Initiative takes our name seriously — and {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is built on it. Love for Charlotte. Love for the families served through Crisis Assistance Ministry. Love poured into every kit.", "Built on love. Powered by community. Delivered through care. Come on {{DRIVE_DATE}}. 💜", "Come Build With Love →"),
    ("OLI {{DRIVE_NAME}}: an event worth attending 🌟", "An event worth attending — {{DRIVE_NAME}} 🌟", "Not just another thing on your calendar", "{{NAME}}, your calendar is full — we get it. But OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} isn't just another thing. It's a kit drive that reaches Charlotte families through Crisis Assistance Ministry. It's worth attending.", "Clear a few hours. Show up. Make it count. 🌟", "Make Room for It →"),
    ("OLI {{DRIVE_NAME}}: small community, big mission 💜", "Small community, big mission — {{DRIVE_NAME}} 💜", "The OLI team punches above its weight. So can you.", "{{NAME}}, OLI is a small team with a big mission — and {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is proof. A handful of dedicated students, powered by community support, packing kits for Charlotte families through Crisis Assistance Ministry.", "Small community, big mission. You make it bigger. Join us on {{DRIVE_DATE}}. 💜", "Make the Community Bigger →"),
    ("OLI {{DRIVE_NAME}}: new volunteers always welcome 💜", "New volunteers always welcome — {{DRIVE_NAME}} 💜", "Haven't volunteered with OLI before? Now's the time.", "{{NAME}}, if you've never volunteered with OLI, {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is the perfect entry point. No prior experience needed — just show up and we'll handle the rest.", "New volunteers are some of our best volunteers. The kits you pack reach Charlotte families through Crisis Assistance Ministry. First time doesn't mean small impact. 💜", "Be a New Volunteer →"),
    ("OLI {{DRIVE_NAME}} — Prithivi personally invites you 💜", "Prithivi personally invites you to {{DRIVE_NAME}} 💜", "The founder of OLI wants you at this drive", "{{NAME}}, I'm Prithivi — OLI's founder — and I'm personally inviting you to {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}}. This organization exists because Charlotte families need hygiene kits and students decided to act.", "Your presence at this drive is personal to me. Please come. Pack kits with us. Through Crisis Assistance Ministry, they reach those families. — Prithivi 💜", "Accept Prithivi's Invite →"),
    ("OLI {{DRIVE_NAME}}: your neighborhood needs this 🏘️", "Your neighborhood needs this — {{DRIVE_NAME}} 🏘️", "Kits reach Charlotte families right here in our community", "{{NAME}}, the families who receive OLI kits through Crisis Assistance Ministry are in your neighborhood — Charlotte families who need basic hygiene supplies. {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is how those kits get packed.", "Your neighborhood needs this. You can help provide it. {{DRIVE_DATE}} at {{DRIVE_LOCATION}}. 🏘️ 💜", "Help My Neighborhood →"),
    ("OLI {{DRIVE_NAME}}: let's set a new record 🏆", "Let's set a new record at {{DRIVE_NAME}} 🏆", "Push OLI's single-drive kit count higher than ever", "{{NAME}}, OLI wants to set a kit-packing record at {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}}. That means we need more volunteers than ever, all packing hygiene kits for Charlotte families through Crisis Assistance Ministry.", "Help us set the record. Bring friends. Show up with energy. Let's see what this community can do. 🏆", "Set the Record →"),
    ("OLI {{DRIVE_NAME}}: do this for Charlotte's kids 🧒", "Do this for Charlotte's kids — {{DRIVE_NAME}} 🧒", "Real kids. Real need. Real kits.", "{{NAME}}, Charlotte's kids deserve clean teeth, clean hands, and healthy skin. OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} packs the kits that make that possible, distributed through Crisis Assistance Ministry.", "Do this for Charlotte's kids. Show up on {{DRIVE_DATE}}. Pack a kit. 🧒", "Do It for the Kids →"),
    ("OLI {{DRIVE_NAME}}: the whole team will be there 💜", "The whole OLI team will be at {{DRIVE_NAME}} 💜", "Prithivi, Saket, Rishi — and hopefully you", "{{NAME}}, the whole OLI team — Prithivi, Saket, and Rishi — will be at {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}}, packing kits alongside volunteers for Charlotte families through Crisis Assistance Ministry.", "Come meet the team. Come pack kits. Come be part of OLI in person. The whole team will be there. 💜", "Meet the Team →"),
    ("OLI {{DRIVE_NAME}}: a day for giving 🎁", "A day for giving — {{DRIVE_NAME}} 🎁", "Give your time. Give your energy. Give a kit.", "{{NAME}}, OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is a day for giving: your time, your energy, and the hygiene kit you help pack for a Charlotte child through Crisis Assistance Ministry.", "Give something real on {{DRIVE_DATE}}. A kit is waiting to be packed. A family is waiting to receive it. 🎁", "Give Something Real →"),
    ("OLI {{DRIVE_NAME}}: together, we make it happen 💜", "Together, we make it happen — {{DRIVE_NAME}} 💜", "No one person packs all the kits. That's the point.", "{{NAME}}, no single person at OLI packs all the kits — that's the beauty of it. {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is a team effort, with every volunteer contributing to hygiene kits for Charlotte families through Crisis Assistance Ministry.", "Together, we make it happen. Together, more families are helped. Will you be one of the together? 💜", "Be Part of Together →"),
    ("OLI {{DRIVE_NAME}}: see the mission in action 💜", "See the mission in action — {{DRIVE_NAME}} 💜", "OLI in action is worth seeing", "{{NAME}}, OLI's mission is real — and seeing it in action is something. {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is your chance to see volunteers packing kits, the community coming together, and hygiene supplies heading to Charlotte families through Crisis Assistance Ministry.", "Come see the mission in action. Leave inspired. 💜", "See It in Action →"),
    ("OLI {{DRIVE_NAME}}: because kits don't pack themselves 💜", "Because kits don't pack themselves 💜", "Someone has to show up. Why not you?", "{{NAME}}, here's the unvarnished truth: hygiene kits for Charlotte families don't pack themselves. Someone has to show up at OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} and do it.", "Through Crisis Assistance Ministry, those kits reach families. But first, someone has to pack them. Why not you? 💜", "I'll Pack Them →"),
    ("OLI {{DRIVE_NAME}}: a student asks for your help 💜", "A student asks for your help — {{DRIVE_NAME}} 💜", "OLI is run by young people who believe in Charlotte", "{{NAME}}, OLI is run by students — young people who decided that Charlotte families deserved better and acted. {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is those students asking for your help to pack more kits.", "Your help reaches Charlotte families through Crisis Assistance Ministry. A student is asking. Will you help? 💜", "I'll Help the Students →"),
    ("OLI {{DRIVE_NAME}}: the drive you'll be glad you attended 💜", "The drive you'll be glad you attended 💜", "Some events you leave feeling good. This is one.", "{{NAME}}, OLI volunteers consistently leave kit drives feeling good — like they used their time well, connected with community, and made a real difference. {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is that experience.", "Charlotte families receive the kits through Crisis Assistance Ministry. You receive a day you'll be glad you said yes to. 💜", "Say Yes →"),
    ("OLI {{DRIVE_NAME}}: kits for every family 💜", "Kits for every family — {{DRIVE_NAME}} 💜", "OLI's vision: no Charlotte family without hygiene essentials", "{{NAME}}, OLI's vision is a Charlotte where no child goes without basic hygiene supplies — toothbrush, toothpaste, soap, lotion. {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is one step toward that vision.", "Crisis Assistance Ministry distributes the kits. You make the kits. One step at a time, we're getting there. 💜", "Build the Vision →"),
    ("OLI {{DRIVE_NAME}}: from the students who make it happen 💜", "From the students who make it happen 💜", "OLI is student-led — and proud of it", "{{NAME}}, OLI is student-led — and proud of it. {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is organized by students who believe in Charlotte's capacity for community care, powered by volunteers like you.", "From the students who make it happen to you — we'd love to have you at {{DRIVE_NAME}}. 💜", "Support the Students →"),
    ("OLI {{DRIVE_NAME}}: the best use of {{DRIVE_DATE}} 🌟", "The best use of {{DRIVE_DATE}} — {{DRIVE_NAME}} 🌟", "Bold claim. Justified claim.", "{{NAME}}, bold claim: OLI's {{DRIVE_NAME}} at {{DRIVE_LOCATION}} is the best use of {{DRIVE_DATE}}. Pack hygiene kits for Charlotte children through Crisis Assistance Ministry alongside a community of people who care. How does it get better?", "It doesn't. {{DRIVE_DATE}}. {{DRIVE_LOCATION}}. {{DRIVE_NAME}}. The best use of that day. 🌟", "Use the Day Well →"),
    ("OLI {{DRIVE_NAME}}: a mission worth joining 💜", "A mission worth joining — {{DRIVE_NAME}} 💜", "Not every mission is. This one is.", "{{NAME}}, not every cause asks for your time. OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} does — and it's a mission worth it. Hygiene kits for Charlotte children through Crisis Assistance Ministry, organized by students who show up every time.", "Worth it. Join it. {{DRIVE_DATE}} at {{DRIVE_LOCATION}}. 💜", "Join the Mission →"),
    ("OLI {{DRIVE_NAME}}: the kit drive for Charlotte 💜", "The kit drive for Charlotte — {{DRIVE_NAME}} 💜", "Everything we do, we do for this city", "{{NAME}}, everything OLI does, we do for Charlotte — and {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is the latest proof. Hygiene kits for Charlotte children and families, distributed through Crisis Assistance Ministry.", "For Charlotte. With love. On {{DRIVE_DATE}}. Come be part of it. 💜", "Do It for Charlotte →"),
    ("OLI {{DRIVE_NAME}}: show Charlotte what we're made of 💪", "Show Charlotte what we're made of — {{DRIVE_NAME}} 💪", "Student-led and community-powered", "{{NAME}}, OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is a chance to show Charlotte what our community is made of — students who lead, volunteers who show up, kits that reach families through Crisis Assistance Ministry.", "Let's show Charlotte. Together on {{DRIVE_DATE}}. 💪", "Show Charlotte →"),
    ("OLI {{DRIVE_NAME}}: an invitation from the OLI family 💜", "An invitation from the OLI family 💜", "We'd be honored to have you", "{{NAME}}, the OLI family — Prithivi, Saket, Rishi, and every volunteer who's ever packed a kit — invites you to {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}}. We'd be honored to have you join us.", "Kits reach Charlotte families through Crisis Assistance Ministry. You join the OLI family. Win-win. 💜", "Join the OLI Family →"),
    ("OLI {{DRIVE_NAME}}: hygiene is a right, not a luxury 💜", "Hygiene is a right, not a luxury — {{DRIVE_NAME}} 💜", "OLI believes every child deserves basic hygiene supplies", "{{NAME}}, OLI believes hygiene is a right — not a luxury. {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is how we act on that belief: packing hygiene kits for Charlotte children who go without, distributed through Crisis Assistance Ministry.", "Help us make the right a reality for more Charlotte kids. {{DRIVE_DATE}}. {{DRIVE_LOCATION}}. 💜", "Fight for the Right →"),
    ("OLI {{DRIVE_NAME}}: an afternoon you won't regret ✨", "An afternoon you won't regret — {{DRIVE_NAME}} ✨", "Ask any OLI volunteer what they thought afterward", "{{NAME}}, ask any OLI volunteer what they thought after a kit drive — every one will say some version of 'I'm glad I went.' {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} will be exactly that: an afternoon you won't regret.", "Kits for Charlotte families through Crisis Assistance Ministry. A memory you'll hold. Won't regret it. ✨", "I Won't Regret It →"),
    ("OLI {{DRIVE_NAME}}: kit-packing, community-building 🤝", "Kit-packing and community-building — {{DRIVE_NAME}} 🤝", "The two things that happen at every OLI drive", "{{NAME}}, two things always happen at OLI drives: kits get packed and community gets built. {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is no different — hygiene kits for Charlotte families through Crisis Assistance Ministry, alongside a growing OLI community.", "Come for the kits. Stay for the community. Return for both. 🤝", "Pack and Connect →"),
    ("OLI {{DRIVE_NAME}}: the next step in our mission 💜", "The next step in our mission — {{DRIVE_NAME}} 💜", "Every drive is a step forward for Charlotte", "{{NAME}}, OLI's mission is a series of steps — each drive a step forward. {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is the next step: more hygiene kits, more Charlotte families served through Crisis Assistance Ministry.", "Take the next step with us. {{DRIVE_DATE}} at {{DRIVE_LOCATION}}. 💜", "Take the Next Step →"),
    ("OLI {{DRIVE_NAME}}: students who give back 💜", "Students who give back — {{DRIVE_NAME}} 💜", "The OLI team leads by example", "{{NAME}}, OLI is proof that students give back — Prithivi, Saket, and Rishi built this nonprofit from scratch because they believed in Charlotte. {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is the latest act of giving back.", "Join the students who give back. Pack kits for Charlotte families through Crisis Assistance Ministry on {{DRIVE_DATE}}. 💜", "Give Back →"),
    ("OLI {{DRIVE_NAME}}: your impact starts on {{DRIVE_DATE}} 💜", "Your impact starts on {{DRIVE_DATE}} 💜", "The moment you show up, you're making a difference", "{{NAME}}, your OLI impact doesn't start when the kits are distributed — it starts the moment you show up at {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} and start packing. That's when the difference begins.", "From there, Crisis Assistance Ministry takes it to Charlotte families. Your impact starts on {{DRIVE_DATE}}. 💜", "Start My Impact →"),
    ("OLI {{DRIVE_NAME}}: help OLI reach its kit goal 🎯", "Help OLI reach its kit goal — {{DRIVE_NAME}} 🎯", "We're packing toward 20,000 kits. Every drive counts.", "{{NAME}}, OLI's goal is 20,000 hygiene kits for Charlotte families by end of summer 2025. {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} moves that number. Every kit packed through Crisis Assistance Ministry gets us closer.", "Help reach the goal. Volunteer on {{DRIVE_DATE}}. Pack kits. Move the number. 🎯", "Help Hit 20,000 →"),
    ("OLI {{DRIVE_NAME}}: a community event worth your time 💜", "A community event worth your time — {{DRIVE_NAME}} 💜", "OLI kit drives are the kind of events that stay with you", "{{NAME}}, OLI's {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} is a community event worth clearing your schedule for. Pack hygiene kits for Charlotte families through Crisis Assistance Ministry alongside neighbors who care.", "Community worth showing up for. Kits worth packing. Time well spent. 💜", "Spend Time Well →"),
    ("OLI {{DRIVE_NAME}}: the mission you can hold in your hands 💜", "The mission you can hold in your hands — {{DRIVE_NAME}} 💜", "Abstract missions become real when you pack a kit", "{{NAME}}, OLI's mission is tangible — you can hold it in your hands. Pack a hygiene kit at {{DRIVE_NAME}} on {{DRIVE_DATE}} at {{DRIVE_LOCATION}} and you're holding the mission: a toothbrush, toothpaste, soap, and lotion for a Charlotte child.", "Through Crisis Assistance Ministry, you hand that mission to a family. Come hold the mission. 💜", "Hold the Mission →"),
]

out = [{"id": f"predrive-{i+1:03d}", "subject": t[0], "body": mkb(t[1], t[2], t[3], t[4], *(t[5:6] or ["Sign Up to Volunteer →"]))} for i, t in enumerate(T)]
path = os.path.join(os.path.dirname(__file__), "predrive.json")
with open(path, "w", encoding="utf-8") as f:
    json.dump(out, f, indent=2, ensure_ascii=False)
print(f"Wrote {len(out)} pre-drive templates to {path}")
